### PR TITLE
static link the vcruntime due to some people not having latest vcruntime dll installed on their machine

### PR DESCRIPTION
**Pull request by xiaoxiao921**

### CODE REVIEW

**Comment by gir489returns** [comment]
Question. Why are we using the debug variant for release mode?

**Comment by xiaoxiao921** [comment]
it appends Debug only if the selected config is Debug

**Comment by gir489returns** [comment]
Our Debug build is busted, so I don't see any use case for using the D variant of the MSVC DLLs. I don't even know why we have the Debug build in the first place.

**Comment by xiaoxiao921** [comment]
Yeah it is busted but can still serve some use in case someone wanna debug some stuff that get completly optimized away, it's just that so far we've been lazy and never bothered fixing the asserts that debug builds produce, but it's doable

**Review by Yimura — APPROVED** [review]

**Review by Yimura — APPROVED** [review]

**Pull request merged**
