### PR TITLE
feat: heist editor

### PR DESCRIPTION
**Pull request by Aure7138**
Cayo Perico Heist & Diamond Casino Heist

- [ Prep Edit ] 

- [ Tunable Edit ] 

- [ Instant Heist Passed ] (maybe also work for some other heist too, haven't test)

Doomsday Heist & Apartment Heist & Auto Shop Contracts & Agency Vip Contract

- [ Prep Edit ] 

- [ Tunable Edit ] 

TODO

- [ Casino Editor ] 

- [ Outfit Editor ] 

- [ Business Editor ]

### CODE REVIEW

**Comment by yasmasdas** [comment]
i thought we wasnt adding recovery stuff like 
Cayo Perico Heist & Diamond Casino Heist

[ Prep Edit ]

[ Tunable Edit ]

[ Instant Heist Passed ] (maybe also work for some other heist too, haven't test)

Doomsday Heist & Apartment Heist & Auto Shop Contracts & Agency Vip Contract

[ Prep Edit ]

[ Tunable Edit ]

**Comment by TheGreenBandit** [comment]
You could add the classic heists,maybe special cargo options by settinng all of the following:
specialCargoBuyGlobalSignalTime: {('262145', '16690')}    GLOBAL Standard value 40000 
specialCargoBuyGlobalSignalTime: {('262145', '16691')}    GLOBAL Standard value 20000 
specialCargoBuyGlobalSignalTime: {('262145', '16692')}    GLOBAL Standard value 5000 
specialCargoSellGlobalSignalTime: {('262145', '16703')}    GLOBAL Standard value 40000 
specialCargoSellGlobalSignalTime: {('262145', '16704')}    GLOBAL Standard value 20000 
specialCargoSellGlobalSignalTime: {('262145', '16705')}    GLOBAL Standard value 5000 

To a high value. And you could also use:
specialCargoSourcingDeliveryTime: {('262145', '32554')}    GLOBAL Standard value: 48 tunable hash: joaat("warehouse_cargo_sourcing_time")

To set the delivery time to something near infinite so the player has time to do those

**Comment by Aure7138** [comment]
> i thought we wasnt adding recovery stuff like

The money earned from heists is cooled by the server, which means that completing multiple heists in a short period of time will not give you money

> **note these are 1.64 globals. May have to change 262145 to 262147**

I just checked the decompiled script tuneables_processing.c, 262145 did not change, but thanks for the reminder I will recheck the offset

**Comment by TheGreenBandit** [comment]
You should add options to disable the cooldown, time to do event, lobbysend things btw. Just a suggestion, nice pr though

**Comment by yasmasdas** [comment]
> "To a high value. And you could also use:
specialCargoSourcingDeliveryTime: {('262145', '32554')} GLOBAL Standard value: 48 tunable hash: joaat("warehouse_cargo_sourcing_time")
To set the delivery time to something near infinite, so the player has time to do those

Thats not what that does. That tunable controls the time it takes for staff to source cargo after telling them to do so.

To add to this you can set one of these` packed stats to 1 (they are all different warehouse indexes)
```
void func_177(bool bParam0, bool bParam1)//Position - 0xA192
{
	switch (bParam0)
	{
		case 0:
			func_128(32359, bParam1, -1);
			break;
		
		case 1:
			func_128(32360, bParam1, -1);
			break;
		
		case 2:
			func_128(32361, bParam1, -1);
			break;
		
		case 3:
			func_128(32362, bParam1, -1);
			break;
		
		case 4:
			func_128(32363, bParam1, -1);
			break;
	}
}

```
to start a cargo sourcing and fill your warehouse then to control the amount of cargo sourced this global was posted on unknowncheats
specialCargoSourcingAmount: {('1890428', '12')}    GLOBAL  

> "You should add options to disable the cooldown" 

This is detected in certain instances and I don't think if this "recovery" type pr is being added that cooldowns should be messed with
Messing with special cargo & business cooldowns probably should be fine but stuff like heists are not recommended

**Comment by Aure7138** [comment]
Add disable the cooldown is not very meaningful, after completing the same robbery, you still have to wait for a certain period of time to get money for the next same robbery

but yes, for diamond casino heist cooldown: [H3_COMPLETEDPOSIX](https://www.unknowncheats.me/forum/2934077-post415.html)
for cayo perico heist cooldown: can use H4_PROGRESS to force open the panel, feel free to use it in the stat editor

**Comment by TheGreenBandit** [comment]
> Add disable the cooldown is not very meaningful, after completing the same robbery, you still have to wait for a certain period of time to get money for the next same robbery

Yeah i meant the cooldown for crates, i didnt specify, my fault

**Comment by Yimura** [comment]
Probably won't be merging this as it falls under the recovery category or rather it makes recovery too accessible to users.

**Pull request closed without merging**
