### PR TITLE
fix(hooks): return types

### PR DESCRIPTION
**Pull request by ghost**
fixes a bunch of return types that were seemingly copied from IDA without manual verification

### CODE REVIEW

**Review by Yimura — APPROVED** [review]
Thanks for your contribution and fixing these things.

**Comment by xiaoxiao921** [comment]
The change for `RECEIVED_CLONE_CREATE` is clearly wrong, as the return function clearly returns 0 or 1 and an if statement depends on that. Now you could be right that the RECEIVED_CLONE_CREATE caller does indeed not check that return value then, but it feels terribly wrong to change the whole function definition just because the caller decided to discard the return value.

**Comment by maybegreat48** [comment]
The child function that the return function calls clobbers `rax`, and IDA thinks that it's returning that value. I would say that the evidence is inconclusive, but the fact that the return value isn't used by the caller makes me lean to a no

**Comment by xiaoxiao921** [comment]
My point was that in this specific case there is absolutly no harm on letting the function as is. (like every other changes in that PR), it's just for the sake of being correct but here the correct doesn't even matter?

**Comment by maybegreat48** [comment]
> the correct

There's no way to know for sure with the GTA dump alone

**Comment by ghost** [comment]
> The change for `RECEIVED_CLONE_CREATE` is clearly wrong, as the return function clearly returns 0 or 1 and an if statement depends on that. Now you could be right that the RECEIVED_CLONE_CREATE caller does indeed not check that return value then, but it feels terribly wrong to change the whole function definition just because the caller decided to discard the return value.

Blindly trusting IDA pseudocode is exactly why there were so many wrong types. Although in this specific instance you can make the argument that it is impossible to be 100% certain with just a game dump.
Even if it were to return a value, it isn't used, so why do you care?


> My point was that in this specific case there is absolutly no harm on letting the function as is. (like every other changes in that PR), it's just for the sake of being correct but here the correct doesn't even matter?

Why do you focus so hard on this specific instance where it doesn't make a difference instead of being happy that I've fixed much more than that where it can indeed break shit if R* uses the return value in a future update or changes the logic?

**Comment by xiaoxiao921** [comment]
@maybegreat48 Is that original function now being called fine here? https://github.com/YimMenu/YimMenu/pull/1834/files#diff-c40e2cdd806d2c4034c85d8fb885194da4d7c5f928d0da1e207010da625e1d2dR50

@MegaMemeMoment i've checked all functions you changed and you did make a potential future compat change for `network_player_mgr_init` and `send_non_physical_player_data`, but you did the opposite for `write_player_camera_data_node` and `write_player_game_state_data_node`, so i'm not sure really?

**Comment by gir489returns** [comment]
I guess if you want to be super paranoid you can always return __int64 from every function which would just copy RAX from the original call and return it to the original calle.

**Comment by ghost** [comment]
> @MegaMemeMoment i've checked all functions you changed and you did make a potential future compat change for `network_player_mgr_init` and `send_non_physical_player_data`, but you did the opposite for `write_player_camera_data_node` and `write_player_game_state_data_node`, so i'm not sure really?

Well those data node functions definitely do not return a value.

**Comment by xiaoxiao921** [comment]
> I've fixed much more than that where it can indeed break shit if R* uses the return value in a future update or changes the logic?

If the goal of this pr is to make the code more reliable for future updates, can you explain how doing the opposite for these data node functions achieves that?

**Comment by Yimura** [comment]
> If the goal of this pr is to make the code more reliable for future updates, can you explain how doing the opposite for these data node functions achieves that?

Well then we fix it by the time it comes around, R* has updated functions in the past. If it breaks it breaks.

**Comment by xiaoxiao921** [comment]
ooooh right right, so exactly what was the purpose of all this? 🤣

**Comment by ghost** [comment]
@xiaoxiao921 It's not only about making it more reliable, I simply like to have these be as accurate/correct as possible. And as I said before, these data node functions definitely do not return a value and most likely won't, so it really shouldn't matter.
I dislike just slamming random stuff in and calling it a day, and wanted to contribute my fixes/research to this project.

**Comment by maybegreat48** [comment]
> @maybegreat48 Is that original function now being called fine here? https://github.com/YimMenu/YimMenu/pull/1834/files#diff-c40e2cdd806d2c4034c85d8fb885194da4d7c5f928d0da1e207010da625e1d2dR50
> 
> @MegaMemeMoment i've checked all functions you changed and you did make a potential future compat change for `network_player_mgr_init` and `send_non_physical_player_data`, but you did the opposite for `write_player_camera_data_node` and `write_player_game_state_data_node`, so i'm not sure really?

Didn't see that. It's probably a good idea to revert that change. Some metrics can flag your account

**Pull request merged**
