### PR TITLE
feat(ScriptEventHandler): Block known malicious script events

### PR DESCRIPTION
**Pull request by mentolixite**
Aside from `Unknown6` (69874647), info was found at:
https://github.com/ccccloro/gta5-N0obMenu/blob/89a03d2f30bba4845f50e9bca69592fb9e19dac8/events.h#L225-L264

### CODE REVIEW

**Comment by mentolixite** [comment]
`CONTRIBUTING.md` says to use spaces instead of tabs, but I used the latter for consistency as the entire file uses them.

**Comment by Yimura** [comment]
Ye that's fine, the contribution.md file is one I reuse for other projects. As Visual Studio apparently defaults to hard tabs instead of spaces the contribution file is indeed incorrect on that part.

**Comment by mentolixite** [comment]
We should probably add a `.clang-format` file, VS has native support for it.

**Comment by Yimura** [comment]
Ye you're right, I personally am using ReSharper, I'll see if I can create a `.clang-format` file.

Though I'd like to make an issue/discussion about this specifically to discuss the coding style/naming scheme.

**Comment by mentolixite** [comment]
We also have to make sure that all files use LF, `src/hooks/script_event_handler.cpp` has CRLF line endings right now for example.

**Comment by maybegreat48** [comment]
It might be a good idea to block -1013679841 as well. Much more dangerous than it looks

**Comment by mentolixite** [comment]
Should we perhaps block all events that are in `freemodeEventsWithNoHandler`?

```cpp
//hashes with no handler in freemode.c
static Hash freemodeEventsWithNoHandler[] =
{
	-1013679841, -1386010354, -1787741241, 962740265,
	-143116395, -488349268, -1872092614, -317318371, 296518236, 911179316,
	665075435, 125492983, -10584126, -1766066400, -786546101, -1367466623,
	-1026787486, -1402943861, -980869764, -522517025, -980869764,
	194348342, -1672632969, 637990725, -39307858, 1915516637, -292927152,
	-1321808667, 193360559, 1474930020, 1216755327, 1213478059, -1208585385,
	1649958326, 1649958326, -1896924387, 1119864805, -2041535807, -978812630, //
	-1857108105, -1500178943, -660428494, 1474930020, -586564007
};
```

Using a proper hash list though, the original code iterates through it:

```cpp
for (int i = 0; i < sizeof(freemodeEventsWithNoHandler); i++)
{
	if ((Hash)data[0] == freemodeEventsWithNoHandler[i])
	{
		NotifyScriptCrashEx(sender_name, sender_id, data[0]);
		return true;
	}
}
```

**Comment by maybegreat48** [comment]
Not sure if these are actually a problem tbh, sent them to myself and everyone, no crash

**Comment by xM4ddy** [comment]
Recently I've been wondering about the possibility of parsing 2take1's SEPs (script event protections) that come as a .cfg file. Example from their site: https://gta.2take1.menu/resources/sep.cfg

**Comment by mentolixite** [comment]
> Not sure if these are actually a problem tbh, sent them to myself and everyone, no crash

Same for me.

> Recently I've been wondering about the possibility of parsing 2take1's SEPs (script event protections) that come as a .cfg file. Example from their site: https://gta.2take1.menu/resources/sep.cfg

Not sure if it's worth it, considering there are not many entries in it. I would just set up GitHub Actions to stay informed on any updates.

**Comment by xM4ddy** [comment]
Some are longer though and include more things but you may be right.

**Comment by xM4ddy** [comment]
https://pastebin.com/RZKQ3a1n

**Comment by mentolixite** [comment]
We definitely have to protect against those, I just got crashed:

```
[   INFO/script_event_handler.cpp:239]: Hash/Arg #0: -903578754
[   INFO/script_event_handler.cpp:242]: Arg #1: 16
[   INFO/script_event_handler.cpp:242]: Arg #2: 2056108439
[   INFO/script_event_handler.cpp:242]: Arg #3: 1
[   INFO/script_event_handler.cpp:242]: Arg #4: 0
[   INFO/script_event_handler.cpp:242]: Arg #5: 0
[   INFO/script_event_handler.cpp:242]: Arg #6: 0
[   INFO/script_event_handler.cpp:242]: Arg #7: 0
```

**Comment by maybegreat48** [comment]
Some more stuff
```c++
GiveCollectible = 995853474, // DLC_SUM20_HIDDEN_COLLECTIBLES xref
DisableRecording = -1211206539, // GET_FINAL_RENDERED_CAM_COORD
```

**Comment by Yimura** [comment]
@mentolixite are you going to commit the suggested changes on this PR?

**Comment by mentolixite** [comment]
Which ones, specifically?

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
If everything has been added then I'll go ahead and merge it all.

**Comment by KekN3t** [comment]
A 2t1 sep config with some stuff:
https://cdn.discordapp.com/attachments/950661181100666900/978240887274504232/sep.cfg
2t1 lua Crash/Kicks:
https://github.com/Disguild/Crashh/blob/main/Crashh1.0.lua
also check moist menu lua for more

**Comment by Yimura** [comment]
> A 2t1 sep config with some stuff: https://cdn.discordapp.com/attachments/950661181100666900/978240887274504232/sep.cfg 2t1 lua Crash/Kicks: https://github.com/Disguild/Crashh/blob/main/Crashh1.0.lua also check moist menu lua for more

@xM4ddy has already linked to the sep.cfg file you mentioned [here](https://github.com/Yimura/YimMenu/pull/219#issuecomment-1133741062).

**Comment by KekN3t** [comment]
Its a bit newer Version

**Comment by xM4ddy** [comment]
@mentolixite Are you planning to add any of the newer stuff to this PR?

**Comment by mentolixite** [comment]
I would do it in another PR, we have to investigate which specific events (and args) to block.

**Comment by xM4ddy** [comment]
Hmm, I'm kind of split on closing this thread; I half just want to say leave this one if that's the plan since this one now holds some helpful information.

**Comment by KekN3t** [comment]
There is a lot to do Protect, we should have a example Blocks for Sync crashes, Objekt, crashes, Model crashes..

**Comment by xM4ddy** [comment]
> There is a lot to do Protect, we should have a example Blocks for Sync crashes, Objekt, crashes, Model crashes..

Well I mean, I think this PR should just focus on blocking and testing SE's.

**Comment by KekN3t** [comment]
> > There is a lot to do Protect, we should have a example Blocks for Sync crashes, Objekt, crashes, Model crashes..
> 
> Well I mean, I think this PR should just focus on blocking and testing SE's.

Year, But for the Future stuff that wouldnt be bad tbh

**Comment by xM4ddy** [comment]
Moving to a discussion about crashes

**Pull request merged**
