### PR TITLE
feat(anticheat): Fix nullsub scanning in PE header

### PR DESCRIPTION
**Pull request by yubie-re**
Should fix uncommon crash after #2463 @gir489returns

### CODE REVIEW

**Comment by gir489returns** [comment]
Thise closes https://github.com/YimMenu/YimMenu/issues/2468

**Review by gir489returns — APPROVED** [review]

**Comment by maybegreat48** [comment]
Can't you simply create a empty function and use that instead? The AC doesn't check if the address is within the GTA module

**Comment by gir489returns** [comment]
> Can't you simply create a empty function and use that instead? The AC doesn't check if the address is within the GTA module

We already have one.

https://github.com/YimMenu/YimMenu/blob/062c95b3745ff622b60f4a7bb0c564639b6f2d90/src/native_hooks/all_scripts.hpp#L182

While the parameters are not the same, the compiler should still optimize it out to simple RETN block.

**Comment by yubie-re** [comment]
The reasoning behind scanning for a nullsub instead of implementing our own func is so the game won't crash when the DLL is uninjected, rather than evading ac checks.

**Comment by gir489returns** [comment]
> The reasoning behind scanning for a nullsub instead of implementing our own func is so the game won't crash when the DLL is uninjected, rather than evading ac checks.

Wouldn't that leave the game in a dirty state? Shouldn't we undo that?

**Comment by yubie-re** [comment]
It could be argued that allowing the AC to run again after uninjection could be dangerous. I figured that it is for the best that it stay patched even after uninjected, as it shouldn't effect much and may make stuff just a little bit safer

**Comment by lonelybud** [comment]
is it possible that to see these logs after player join the session? bcz i am seeing it after starting the game second time

`14:53:11.2458370][INFO/queue_dependency.cpp:63] Blocking AC Verifier 95bd58`

**Review by Yimura — APPROVED** [review]

**Pull request merged**
