### PR TITLE
feat(Outfit Editor): Add [+] & [-] buttons

### LINKED ISSUE #1402: [Request]: Improve "Outfit Editor".
### Problem

Is it only me or the current outfit editor is super complicated to use for creating custom outfits from scratch?
I mean you really have to type the number index of each stuff manually with the keyboard?

### Solution

I would like the devs to add a [+] or [-] clickable button on the menu to scroll trough the index of the selected outfit prop.
If that is not possible for some reasons to do, then maybe they can make the user's keyboard [+] and [-] keys to do the same behaviour?

### Reason

.

### Additional context

.

### PR DESCRIPTION
**Pull request by tupoy-ya**
fix(overlay): Don't show the separtor when there are no pools.

refactor(view_pv.cpp & view_spawn_vehicle.cpp): Intent with tabs instead of 8 spaces.

chore!: Update ImGui

This Pull Request updates ImGui to latest version.
It does not use the YimMenu fork of ImGui as it does not have any changes in it and is out of date.

image

- [x] Update ImGui.
- [x] Add +- buttons to outfit editor.
- [x] Change the size of `InputInt` in the outfit editor too look better.
- [x] Add ImGui Demo to debug options.
- [x] Test if everything is working.

Closes #1402

### CODE REVIEW

**Comment by Yimura** [comment]
Sounds good, there's no more need for the YimMenu fork really.

**Comment by Democles85** [comment]
> Sounds good, there's no more need for the YimMenu fork really.

So should I close my Request?

**Comment by Tayipc38** [comment]
This makes me think. The clothing shops must be accessing something to accompany these clothing indexes with display names. Could we try and do the same?

**Comment by tupoy-ya** [comment]
> This makes me think. The clothing shops must be accessing something to accompany these clothing indexes with display names. Could we try and do the same?

Yes, i just don't know where to put it on screen.
https://github.com/YimMenu/YimMenu/pull/624#issuecomment-1321160065

**Comment by Tayipc38** [comment]
> > This makes me think. The clothing shops must be accessing something to accompany these clothing indexes with display names. Could we try and do the same?
> 
> Yes, i just don't know where to put it on screen. [#624 (comment)](https://github.com/YimMenu/YimMenu/pull/624#issuecomment-1321160065)

Lol had no idea it was just natives. I believe it would require a drastically different approach to keep it user friendly.

**Comment by Tessio** [comment]
When a number arrives that represents a new generation clothing model, you simply cannot move forward, would there be a way to avoid this?

bug:
https://streamable.com/wo7zi1

**Comment by Democles85** [comment]
> When a number arrives that represents a new generation clothing model, you simply cannot move forward, would there be a way to avoid this?
> 
> bug: https://streamable.com/wo7zi1

From my understanding of what you are saying, is that you should be able to "scroll" infinitely the clothes IDs? Like when it goes to the last clothing piece, it should loop back to the first piece?

**Comment by Tessio** [comment]
> > When a number arrives that represents a new generation clothing model, you simply cannot move forward, would there be a way to avoid this?
> > bug: https://streamable.com/wo7zi1
> 
> From my understanding of what you are saying, is that you should be able to "scroll" infinitely the clothes IDs? Like when it goes to the last clothing piece, it should loop back to the first piece?

The Int Slider should scroll from 0 to the final ID, but when reaching a Gen9 clothing id "New generation, clothing that does not exist in the game" does not allow further scrolling of the slider.

In the video you can see how it reaches a number and it does not allow scrolling anymore, you would have to change the number manually to skip the id of the Gen9 clothing.

There just has to be a way to bypass the Gen9 models and still allow scrolling.

**Comment by Democles85** [comment]
> > > When a number arrives that represents a new generation clothing model, you simply cannot move forward, would there be a way to avoid this?
> > > bug: https://streamable.com/wo7zi1
> > 
> > 
> > From my understanding of what you are saying, is that you should be able to "scroll" infinitely the clothes IDs? Like when it goes to the last clothing piece, it should loop back to the first piece?
> 
> The Int Slider should scroll from 0 to the final ID, but when reaching a Gen9 clothing id "New generation, clothing that does not exist in the game" does not allow further scrolling of the slider.
> 
> In the video you can see how it reaches a number and it does not allow scrolling anymore, you would have to change the number manually to skip the id of the Gen9 clothing.
> 
> There just has to be a way to bypass the Gen9 models and still allow scrolling.

Understand, will look into that.

**Comment by tupoy-ya** [comment]
> When a number arrives that represents a new generation clothing model, you simply cannot move forward, would there be a way to avoid this?
> 
> bug: https://streamable.com/wo7zi1

I don't know how to fix this, but here are *all* the gen9 clothing IDs i could find manually:
```cpp
const inline std::unordered_set<std::uint32_t> gen9_berd   = {209, 210, 211, 212, 213, 226, 227, 229};
const inline std::unordered_set<std::uint32_t> gen9_m_uppr = {210};
const inline std::unordered_set<std::uint32_t> gen9_f_uppr = {243, 244};
const inline std::unordered_set<std::uint32_t> gen9_m_lowr = {144, 149, 150, 163, 164, 165, 166, 167, 168, 169, 170, 172, 174};
const inline std::unordered_set<std::uint32_t> gen9_f_lowr = {151, 157, 158, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 186, 189};
const inline std::unordered_set<std::uint32_t> gen9_m_feet = {102, 110, 129, 130, 131, 132, 133};
const inline std::unordered_set<std::uint32_t> gen9_f_feet = {106, 114, 133, 135, 136, 137, 138, 140};
const inline std::unordered_set<std::uint32_t> gen9_m_teef = {168, 169, 170, 173, 174};
const inline std::unordered_set<std::uint32_t> gen9_f_teef = {138, 139, 140, 143, 144};
const inline std::unordered_set<std::uint32_t> gen9_m_accs = {189, 192, 195, 196, 197, 198, 199};
const inline std::unordered_set<std::uint32_t> gen9_f_accs = {234, 237, 240, 241, 242, 243, 244, 245};
const inline std::unordered_set<std::uint32_t> gen9_m_decl = {140, 141, 142, 147, 163, 164, 166, 167, 168, 170, 171, 172, 181, 183, 184, 191, 192, 193, 194};
const inline std::unordered_set<std::uint32_t> gen9_m_jbib = {393, 414, 415, 416, 417, 418, 419, 420, 421, 454, 456, 457, 458, 461, 462, 463, 465, 466, 467, 468, 469, 471, 474, 477, 478, 479, 480, 483, 484, 485, 491, 492, 493, 496, 497, 498, 502, 503};
const inline std::unordered_set<std::uint32_t> gen9_f_jbib = {415, 441, 442, 443, 444, 445, 446, 447, 448, 449, 486, 488, 489, 490, 491, 492, 495, 496, 497, 499, 500, 501, 502, 503, 505, 509, 510, 512, 513, 514, 515, 516, 519, 521, 522, 530, 531, 532, 535, 536, 537, 542, 543};
```
All of this has been added manually so there could be mistakes.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
