### PR TITLE
(Add) Flying vehicle

### PR DESCRIPTION
**Pull request by Mystro69**
https://i.giphy.com/media/UPDKB6BOei1Z26mqec/giphy.webp

### CODE REVIEW

**Comment by Yimura** [comment]
It's fine to make mistakes, just fix it in a later commit, commits will be squashed anyways.

This is the 3rd PR you've opened, please refrain from opening any more PR's for the same feature!
https://github.com/Yimura/YimMenu/pull/167
https://github.com/Yimura/YimMenu/pull/168

**Comment by Mystro69** [comment]
> It's fine to make mistakes, just fix it in a later commit, commits will be squashed anyways.
> 
> This is the 3rd PR you've opened, please refrain from opening any more PR's for the same feature! #167 #168

I'm bad at using the pr system sorry

**Comment by Yimura** [comment]
Just don't remove your fork (Github Repo) before this has been merged, instead make a branch on that same repo and work on there.

**Comment by xM4ddy** [comment]
> I'm bad at using the pr system sorry

It confused the shit out of me too https://github.com/Yimura/YimMenu/pull/87

**Comment by Mystro69** [comment]
@Yimura can you check ?

**Comment by Yimura** [comment]
nah bro, I'm gaming with the boys

**Comment by xM4ddy** [comment]
Fix the conflicts and ill merge it

**Comment by xM4ddy** [comment]
Wait also what all is getting added I see instant brake and flying stuff?

**Comment by Mystro69** [comment]
> Wait also what all is getting added I see instant brake and flying stuff?

@xM4ddy  i can't opened multiple pull request so im added 3 thing in same pull request

**Comment by xM4ddy** [comment]
Flying vehicle doesn't seem to work just gives the notif that it failed. How is it intended to work?

**Comment by Mystro69** [comment]
> Flying vehicle doesn't seem to work just gives the notif that it failed. How is it intended to work?

taking control of the vehicle is not working fine (same in bring player) if you click 2 times it works
https://i.giphy.com/media/UPDKB6BOei1Z26mqec/giphy.webp

**Comment by Mystro69** [comment]
@Yimura

**Comment by Yimura** [comment]
Don't worry I saw your previous message.

image

**Review by LiamD-Flop — APPROVED** [review]

**Pull request merged**
