### PR TITLE
Allow all outfits.

### PR DESCRIPTION
**Pull request by gir489returns**

### CODE REVIEW

**Comment by gir489returns** [comment]
image

**Comment by yousef157** [comment]
I'm assuming this simply allows blacklisted clothing items on your character? Like nearly everything with the checkboard texture, certain invisible body parts, etc,.

**Comment by gir489returns** [comment]
> I'm assuming this simply allows blacklisted clothing items on your character? Like nearly everything with the checkboard texture, certain invisible body parts, etc,.

I have no idea about other components you mentioned, as I only tested it with the Juggarnaut suit, but I'd assume so. Originally when I implemented #1743 I mentioned that the is_tag_restricted function had to be hooked to do the Juggarnaut suit, but when I tried to port it at the time, I couldn't find it and just gave up. However, now that I have a better understanding of YimMenu and newer GTA V versions, it was a lot easier to figure out and defeat the new system, as before I probably would've just detoured the function and signatured it, but now it's a simple native hook + return false on the new native they added.

**Comment by D-Borkan** [comment]
most blacklist clothing still disappear 
and also logo crew  become disappear with this 
- so this maybe allow for some components

**Comment by gir489returns** [comment]
> most blacklist clothing still disappear and also logo crew become disappear with this
> 
> * so this maybe allow for some components

Upload some Persist Outfit JSONs so I can test and see why.

**Comment by D-Borkan** [comment]
try this
[b.json](https://github.com/YimMenu/YimMenu/files/13625068/b.json)
[m.json](https://github.com/YimMenu/YimMenu/files/13625069/m.json)

**Comment by gir489returns** [comment]
> try this [b.json](https://github.com/YimMenu/YimMenu/files/13625068/b.json) [m.json](https://github.com/YimMenu/YimMenu/files/13625069/m.json)

Thank you for your test cases. They helped me pin down the issue.

https://youtu.be/tsL375Oi6D4

**Comment by D-Borkan** [comment]
> > try this [b.json](https://github.com/YimMenu/YimMenu/files/13625068/b.json) [m.json](https://github.com/YimMenu/YimMenu/files/13625069/m.json)
> 
> Thank you for your test cases. They helped me pin down the issue.
> 
> https://youtu.be/tsL375Oi6D4

- That perfect , Great work

**Comment by gir489returns** [comment]
This branch has become contaminated by Git, and I can't commit scr_globals for some reason. I might have to create a new branch.

**Comment by D-Borkan** [comment]
> This branch has become contaminated by Git, and I can't commit scr_globals for some reason. I might have to create a new branch.

as you like

**Comment by gir489returns** [comment]
@D-Borkan A build has been made, can you test it and confirm your outfits now work without flickering?

**Comment by D-Borkan** [comment]
> @D-Borkan A build has been made, can you test it and confirm your outfits now work without flickering?

ok

**Comment by D-Borkan** [comment]
now is fully work,
* work only when menu is load and that normal

- so that is great work

**Comment by gir489returns** [comment]
@Yimura This is ready for merging.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
