### PR TITLE
(fix) Passive not working correctly

### LINKED ISSUE #2031: [Bug]: Passive Mode Toggle Not Functioning Properly
### Describe the bug

*I have attached a video showing the issues described, as well as my logs - I apologize in advance for the terrible compression, it took a lot of tweaking to get down to the 10MB limit for GitHub*

When toggling "Passive Mode", it does not place my character into Passive Mode fully.  The Weapon Wheel is disabled (as it should be), melee/punch is disabled (as it should be) and weapon cycling while in a vehicle is disabled (as it should be). 
 However, other players are still able to kill/make contact with me (which shouldn't be the case while in Passive Mode).  Also, while "Passive Mode" is toggled on in YimMenu, when opening the GTA Interactive Menu, "Disable Passive Mode" is greyed out, and a message is given saying, "Passive Mode is unavailable".

Once "Passive Mode" is disabled through YimMenu, other players are unable to kill/make contact with me (as if I'm now in Passive Mode).  Yet, the Weapon Wheel is enabled and melee/punch is re-enabled, yet I am unable to kill/make contact with other players.

Essentially, features are swapped.  Once "Passive Mode" is toggled on in YimMenu, all weapons and melee are disabled, but contact is still allowed by other players.  Yet, once "Passive Mode" is toggled off in YimMenu, all weapons and melee are re-enabled, but no physical contact is allowed towards or against other players.

The only way to fully deactivate Passive Mode once toggled "on" through YimMenu, is to toggle "off" in YimMenu, go to the GTA Interaction Menu, "Enable Passive Mode" then "Disable Passive Mode" and wait for the 30-second timer to count down.

### Steps To Reproduce

1.  Open YimMenu
2.  Go to "Self"
3.  Toggle "Passive Mode"

### Expected Behavior

Once toggled "on" (either by selecting the "Passive Mode" checkbox, or using a designated Hotkey), then Passive Mode should be enabled:

 - Kill/Physical Contact should be disabled (not working)
 - Weapon Wheel should be disabled (working)
 - Melee/Punch should be disabled (working)

Once toggled "off" (either by selecting the "Passive Mode" checkbox, or using a designated Hotkey), then Passive Mode should be disabled:

 - Kill/Physical Contact should be enabled (not working)
 - Weapon Wheel should be enabled (working)
 - Melee/Punch should be enabled (working)

### Logs and/or screenshots

```
<paste your logs here>
```

[cout.log](https://github.com/YimMenu/YimMenu/files/12447090/cout.log)

### Store

Steam

### Additional context

First off, I want to thank everyone who implemented the "Passive Mode" toggle into YimMenu so quickly.  I appreciate that very, very much!

Second, if you need me to add anything else, or provide any further details, please let me know and I'll be happy to help!

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

https://github.com/YimMenu/YimMenu/assets/142962424/7b97fc65-c87e-4c48-9b3d-d5e6fa075b3f

https://github.com/YimMenu/YimMenu/assets/142962424/b0209824-a517-42c2-a222-12e97b7cc29b

### PR DESCRIPTION
**Pull request by NjuuOwO**
I'm taking back, + 1 global was fucking things up
Fixes #2031

### CODE REVIEW

**Comment by NjuuOwO** [comment]
Disabling passive with Global_27371 didn't put ped flags 122 and 342 to its intended value (false)

**Comment by NjuuOwO** [comment]
Ready to merge, should work as intended.

**Comment by gir489returns** [comment]
Clearly it is not ready to merge, because you are still making commits.

**Comment by NjuuOwO** [comment]
sorry it's done now fs

**Review by Yimura — APPROVED** [review]

**Pull request merged**
