### PR TITLE
fix(core): Signal to the user whenever YimMenu is lacking needed OS privileges

### PR DESCRIPTION
**Pull request by xiaoxiao921**

### CODE REVIEW

**Comment by gir489returns** [comment]
What is holding this up?

**Comment by xiaoxiao921** [comment]
we can't repro

**Comment by gir489returns** [comment]
This should be invalidated by #2055 correct?

**Comment by Yimura** [comment]
Nope this one is here to see if some of the people having issues generating a cache could offer their insights on how their system is setup so we can look at a fix.

Sadly though no response and the guys that opened an issue about it just went with sharing a zip with a pre-generated cache.

**Comment by xiaoxiao921** [comment]
> This should be invalidated by #2055 correct?

I'm afraid it's entirely unrelated, what this pr attempted to fix was multiple users failing to generate a valid cache, `packfile.OpenPackfile` would just return false every time

**Comment by xiaoxiao921** [comment]
I've seen people saying it's due to steam version, could totally be that the rpf path we give is wrong

**Comment by WorthIessPricetag** [comment]
> Nope this one is here to see...

- I dont have cache since the 1.67 update
- Steam version
- Gta and Steam are installed on separate drives
- Setting the gta drive as default makes no difference
 
[NoCacheCout.log](https://github.com/YimMenu/YimMenu/files/12489156/NoCacheCout.log)

**Comment by gir489returns** [comment]
> > Nope this one is here to see...
> 
> * I dont have cache since the 1.67 update
> * Steam version
> * Gta and Steam are installed on separate drives
> * Setting the gta drive as default makes no difference
> 
> [NoCacheCout.log](https://github.com/YimMenu/YimMenu/files/12489156/NoCacheCout.log)

The commit hash you have in your logs is for something completely different.  https://github.com/xiaoxiao921/YimMenu/commit/e87931bf605cf967ac5b9d490bfa0dcb3c1bb168

Can you please try the DLL included with this PR or use this link?: https://nightly.link/YimMenu/YimMenu/actions/artifacts/826380980.zip

**Comment by WorthIessPricetag** [comment]
My bad

[cout.log](https://github.com/YimMenu/YimMenu/files/12489575/cout.log)

**Comment by gir489returns** [comment]
> My bad
> 
> [cout.log](https://github.com/YimMenu/YimMenu/files/12489575/cout.log)

Question. Is X: a networked drive or some kind of false drive that isn't a real HDD? X seems extremely high up on the letter chain. Usually networked drives start with Z and work downwards.

**Comment by WorthIessPricetag** [comment]
Its a plain ssd, i chose the letter X when installing.  

xxx

**Comment by tyackman** [comment]
[trimmed YimMenu log - E drive.txt](https://github.com/YimMenu/YimMenu/files/14656327/minimal.sex.-.E.drive.txt)
Cache fails to generate on a steam GTA install on my E drive SSD, but upon reinstalling the game on my boot (C) drive, it works just fine. The RPF files do exist in the correct directories though.

**Comment by Yimura** [comment]
> [E drive.txt](https://github.com/YimMenu/YimMenu/files/14656327/minimal.sex.-.E.drive.txt) Cache fails to generate on a steam GTA install on my E drive SSD, but upon reinstalling the game on my boot (C) drive, it works just fine. The RPF files do exist in the correct directories though.

Could you run the following command on your system with an admin prompt so we can get some information about the drives?
```bat
fsutil fsinfo ntfsinfo E:
```

This is my drive as an example:
```r
PS C:\Users\LocalAdmin> fsutil fsinfo ntfsinfo C:
NTFS Volume Serial Number :        0x500e818f0e816eb2
NTFS Version      :                3.1
LFS Version       :                2.0
Total Sectors     :                3.999.158.271  (  1,9 TB)
Total Clusters    :                  499.894.783  (  1,9 TB)
Free Clusters     :                  155.596.840  (593,6 GB)
Total Reserved Clusters :              1.291.076  (  4,9 GB)
Reserved For Storage Reserve :         1.280.425  (  4,9 GB)
Bytes Per Sector  :                512
Bytes Per Physical Sector :        4096
Bytes Per Cluster :                4096  (4 KB)
Bytes Per FileRecord Segment    :  1024
Clusters Per FileRecord Segment :  0
Mft Valid Data Length :            1,13 GB
Mft Start Lcn  :                   0x00000000000c0000
Mft2 Start Lcn :                   0x0000000000000002
Mft Zone Start :                   0x000000000b639400
Mft Zone End   :                   0x000000000b644420
MFT Zone Size  :                   176,13 MB
Max Device Trim Extent Count :     256
Max Device Trim Byte Count :       0xffffffff
Max Volume Trim Extent Count :     62
Max Volume Trim Byte Count :       0x40000000
Resource Manager Identifier :      7736F071-FE19-11ED-80FC-F65E69E48430
```

**Comment by tyackman** [comment]
[drive info E.txt](https://github.com/YimMenu/YimMenu/files/14656404/drive.info.E.txt)

**Comment by xiaoxiao921** [comment]
@WorthIessPricetag @tyackman Please try new Yimmenu.dll from https://github.com/YimMenu/YimMenu/pull/1859#issuecomment-1652119480

**Comment by tyackman** [comment]
[cout.txt](https://github.com/YimMenu/YimMenu/files/14879625/cout.txt) (https://nightly.link/YimMenu/YimMenu/actions/artifacts/1385123845.zip) And uh - Ignore my message above saying that it loads fine from my C drive - it in fact does not :(

**Comment by xesdoog** [comment]
Could this be a permission issue? I have my Steam and GTA on separate drives and I've never had a problem opening rpfs

image

Untitled-1

```powershell
NTFS Volume Serial Number :        0x6a7c75b17c7578a1
NTFS Version      :                3.1
LFS Version       :                2.0
Total Sectors     :                1,953,521,623  (931.5 GB)
Total Clusters    :                  244,190,202  (931.5 GB)
Free Clusters     :                   42,769,278  (163.2 GB)
Total Reserved Clusters :                  3,513  ( 13.7 MB)
Reserved For Storage Reserve :                 0  (  0.0 KB)
Bytes Per Sector  :                512
Bytes Per Physical Sector :        4096
Bytes Per Cluster :                4096  (4 KB)
Bytes Per FileRecord Segment    :  1024
Clusters Per FileRecord Segment :  0
Mft Valid Data Length :            345.50 MB
Mft Start Lcn  :                   0x00000000050a20d3
Mft2 Start Lcn :                   0x0000000002868a2a
Mft Zone Start :                   0x0000000009734380
Mft Zone End   :                   0x0000000009740ba0
MFT Zone Size  :                   200.13 MB
Max Device Trim Extent Count :     0
Max Device Trim Byte Count :       0
Max Volume Trim Extent Count :     62
Max Volume Trim Byte Count :       0x40000000
Resource Manager Identifier :      7D07DA9B-828C-1230-9C4A-00D861F9A61E

**Comment by TwystedMind** [comment]
I was assisting someone who was encountering the same issue with their installation as well.  The menu injected fine (using Xenos) and the interface could be brought up in game; however, the vehicle/object/ped lists were not populating and "Rebuild Cache" returned 0 assets for each class.  When I looked at her cout.log, the menu was failing to open all of the .rpfs just like what's happening here.

The failure to open from the game directory made me instantly think it was a permissions issue, I asked her to try launching Xenos using "Run As Administrator", and everything loaded properly 👌🏽

If this has already been suggested and tested here, then I apologize for wasting your time.  I just wanted to bring it up just in case - the thought never crossed my mind until I was staring at the cout.log that the issue was lack of permissions with the injector 🤦🏽‍♂️

**Comment by xiaoxiao921** [comment]
That makes a lot of sense, honestly I'm out of idea so it's probably the only thing left, funny how Windows work though, wasn't really aware modules could have different permission even though it's the same process.

**Comment by Yimura** [comment]
I'd think the module would inherit the permissions of the process that it is part of however it's possible that the module is inheriting the permissions from the process that called `CreateThread(Ex)`.

**Comment by tyackman** [comment]
Opening steam, rockstar games launcher, the game itself and the dll injector all with elevated privileges didnt seem to make a difference for me.

**Comment by Yimura** [comment]
@tyackman I don't remember if I asked you this before but do you have some other anti-virus installed (other than Windows Defender).

**Comment by tyackman** [comment]
> @tyackman I don't remember if I asked you this before but do you have some other anti-virus installed (other than Windows Defender).

Malwarebytes. Ill try disabling it.

**Comment by tyackman** [comment]
@Yimura I cant reproduce it now. Cache generates fine 🥴. With and without malwarebytes service.

**Comment by xiaoxiao921** [comment]
Related https://github.com/YimMenu/YimMenu/issues/3499

**Pull request closed without merging**
