### PR TITLE
A basic fonts system

### PR DESCRIPTION
**Pull request by oakboat**
I testd it with 2 fonts.
arial.ttf
image
and simehei.ttf
image
besides, zh_TW works well.
image

### CODE REVIEW

**Comment by Yimura** [comment]
You’re aware you could’ve continued pushing changes on the #939 PR?

**Comment by oakboat** [comment]
> You’re aware you could’ve continued pushing changes on the #939 PR?

sorry, i have no idea.

**Comment by Yimura** [comment]
Hello and thank you for taking the time to contribute to YimMenu.

I would prefer that core functionality like this be discussed beforehand, I'm currently not happy with how the UI is structured and would like to hold of on fundamental or large changes.

We can keep the PR open a little longer while I think about this.

**Comment by Yimura** [comment]
Probably won't support loading custom fonts until we've decided on reworking the UI.

**Pull request closed without merging**
