### PR TITLE
feat(cmake): embed git info in binary

### LINKED ISSUE #630: [Request]: Log the current commit hash YimMenu was built against
### Problem

We have no clear indication of what version of YimMenu people are using when their share their log file

### Solution

https://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable

### Reason

Easier debugging

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Yimura**
Embed the current commit hash, branch name and commit date into the YimMenu binary.
These are printed out on startup.

Preview:
image

Closes #630

### CODE REVIEW

**Comment by Yimura** [comment]
@tupoy-ya, I'm not too familiar with CMake if there's anything you would consider changing, please tell me.

**Comment by tupoy-ya** [comment]
We should probably use `add_compile_definitions` instead of creating a separate file for git info.

<details>
  <summary>Diff</summary>

```diff
diff --git a/scripts/git.cmake b/scripts/git.cmake
index 4b9d674..160b1b5 100644
--- a/scripts/git.cmake
+++ b/scripts/git.cmake
@@ -29,7 +29,9 @@ if(Git_FOUND)
         WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
         OUTPUT_VARIABLE GIT_BRANCH
         ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
-
-    # generate version.cpp
-    configure_file("${SRC_DIR}/version.cpp.in" "${SRC_DIR}/version.cpp" @ONLY)
-endif()
\ No newline at end of file
+        
+    add_compile_definitions(GIT_SHA1=\"${GIT_SHA1}\")
+    add_compile_definitions(GIT_DATE=\"${GIT_DATE}\")
+    add_compile_definitions(GIT_COMMIT_SUBJECT=\"${GIT_COMMIT_SUBJECT}\")
+    add_compile_definitions(GIT_BRANCH=\"${GIT_BRANCH}\")
+endif()
diff --git a/src/main.cpp b/src/main.cpp
index f3e6d53..15f3aef 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -8,7 +8,6 @@
 #include "renderer.hpp"
 #include "script_mgr.hpp"
 #include "thread_pool.hpp"
-#include "version.hpp"
 
 #include "backend/backend.hpp"
 #include "native_hooks/native_hooks.hpp"
@@ -59,7 +58,7 @@ BOOL APIENTRY DllMain(HMODULE hmod, DWORD reason, PVOID)
                        try
                        {
                                LOG(INFO) << "Yim's Menu Initializing";
-                               LOGF(INFO, "Git Info\n\tBranch:\t%s\n\tHash:\t%s\n\tDate:\t%s", version::GIT_BRANCH, version::GIT_SHA1, version::GIT_DATE);
+                               LOGF(INFO, "Git Info\n\tBranch:\t%s\n\tHash:\t%s\n\tDate:\t%s", GIT_BRANCH, GIT_SHA1, GIT_DATE);
 
                                g->load();
                                LOG(INFO) << "Settings Loaded.";
diff --git a/src/version.cpp.in b/src/version.cpp.in
deleted file mode 100644
index abed2d7..0000000
--- a/src/version.cpp.in
+++ /dev/null
@@ -1,9 +0,0 @@
-#include "version.hpp"
-
-namespace big
-{
-    const char* version::GIT_SHA1 = "@GIT_SHA1@";
-    const char* version::GIT_BRANCH = "@GIT_BRANCH@";
-    const char* version::GIT_DATE = "@GIT_DATE@";
-    const char* version::GIT_COMMIT_SUBJECT = "@GIT_COMMIT_SUBJECT@";
-};
\ No newline at end of file
diff --git a/src/version.hpp b/src/version.hpp
deleted file mode 100644
index 7655fee..0000000
--- a/src/version.hpp
+++ /dev/null
@@ -1,12 +0,0 @@
-#pragma once
-
-namespace big
-{
-    struct version
-    {
-        static const char* GIT_SHA1;
-        static const char* GIT_DATE;
-        static const char* GIT_COMMIT_SUBJECT;
-        static const char* GIT_BRANCH;
-    };
-}
```
</details>

**Comment by Yimura** [comment]
My intention making it like this is that it does not require a recompile of everything that uses it since only the .cpp file needs to be recompiled. Meanwhile using a define would require everywhere it's used for it be recompiled again.

**Comment by tupoy-ya** [comment]
Well i don't see much of an issue in compiling some extra files every commit, maybe it's because i'm used to partial compilation not working.

**Comment by GeopJr** [comment]
Should we also embed origin? `git remote get-url origin` (can error with `error: No such remote 'origin'` if there's no remote named "origin")

and also whether there have been any (uncommited) modifications? `git diff-index HEAD` or `git diff --name-only`

**Comment by tupoy-ya** [comment]
> Should we also embed origin? `git remote get-url origin` (can error with `error: No such remote 'origin'` if there's no remote named "origin")

That would be useful.

> and also whether there have been any (uncommited) modifications? `git diff-index HEAD` or `git diff --name-only`

I thought that's what `<hash>-dirty` means.

**Comment by GeopJr** [comment]
> I thought that's what `<hash>-dirty` means.

Only if they are tracked. I'm not sure if YimMenu can break significantly without modifying tracked files but here's an example: 

```
$ git clone https://github.com/YimMenu/YimMenu && cd YimMenu && touch test.txt && git describe --match=NeVeRmAtCh --always --abbrev=40 --dirty

Cloning into 'YimMenu'...
remote: Enumerating objects: 10005, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 10005 (delta 37), reused 69 (delta 32), pack-reused 9901
Receiving objects: 100% (10005/10005), 4.90 MiB | 302.00 KiB/s, done.
Resolving deltas: 100% (6309/6309), done.
4a22a997c598d542519f539a479b197c6710575e
```

**Comment by Yimura** [comment]
It already adds `-dirty` to the commit hash if there are any changes that haven't been committed.

**Comment by GeopJr** [comment]
> It already adds `-dirty` to the commit hash if there are any changes that haven't been committed.

see above reply, in the example I made `test.txt` yet the hash didn't get the `-dirty` suffix (since test.txt is not tracked)

**Comment by Yimura** [comment]
> see above reply, in the example I made `test.txt` yet the hash didn't get the `-dirty` suffix

Yeah it's because cmake needs to be ran again for the changes to reflect in the build.
We'll have to make some changes if we want to execute git before building.

**Pull request merged**
