### PR TITLE
add player icons highlights and friends in player list 

### PR DESCRIPTION
**Pull request by binded-zz**
adds icons for 
admin highlight default 
friends with highlight  green and icon for r* and db friends 
modders highlight  as of now blue
blocked users with a notfriend icon with a red highlight

proof

Screenshot 2023-05-02 211313

### CODE REVIEW

**Comment by binded-zz** [comment]
colors ?
im sure many will not like them as is 
maybe green blue for friends
oragne  for modders and 
red blocked 

i still dont know if  that works as i have not seen any toxic people when i was looking and testing but it should work as is

**Comment by ghost** [comment]
MY EYES............
sorry but I don't think anyone will approve this. besides, the UI is getting a rewrite soon apparently 
https://github.com/YimMenu/YimMenu/discussions/1286

**Comment by binded-zz** [comment]
know what your right fuck it no one wants friends in the menu and no one wants to be able to know with a glance
red alerts all  around for every thing and every one and shit 
no enemys 
ill leave this as is 
sorry to even bother to try to add any thing 
its there if you want it

**Comment by binded-zz** [comment]
Screenshot 2023-05-04 192132
with default gui color i think

**Pull request closed without merging**
