### PR TITLE
fixed get_player_rank and get_player_rp

### LINKED ISSUE #3226: [Bug]: get_player_rank and get_player_rp not working properly
### Describe the bug

When using get_player_rank or get_player_rp passing the player's own id as a parameter, -1 is returned.

It's only working with other player's id.

### Steps To Reproduce

1 - Create a lua script
2 - Enter the following code:

```lua
PlayerId = PLAYER.PLAYER_ID()

PlayerRank = network.get_player_rank(PlayerId)-- Not working properly, returns -1 when the PlayerId is yours
log.info("PlayerRank: " .. PlayerRank)

PlayerRp = network.get_player_rp(PlayerId)-- Not working properly, returns -1 when the PlayerId is yours
log.info("PlayerRp: " .. PlayerRp)
```

### Expected Behavior

Return the rank or rp of the player passed as a parameter, even if it is the id itself.

### Logs

There is nothing useful in the logs.

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by USBMenus**
fixed the network commands get_player_rank and get_player_rp so that when the user uses them on the local player it returns the correct values instead of -1

closes [#3226](https://github.com/YimMenu/YimMenu/issues/3226)

### CODE REVIEW

**Comment by lonelybud** [comment]
these changes wont actually fix #3226 bcz we dont add self pointer in player list.

https://github.com/YimMenu/YimMenu/blob/8bbab4c76531a905a885f667af34315516489534/src/services/players/player_service.cpp#L96

**Comment by xiaoxiao921** [comment]
> these changes wont actually fix #3226 bcz we dont add self pointer in player list.
> 
> https://github.com/YimMenu/YimMenu/blob/8bbab4c76531a905a885f667af34315516489534/src/services/players/player_service.cpp#L96

i'm curious what was the reasoning behind this, doesn't seem logical at all.

**Comment by lonelybud** [comment]
> i'm curious what was the reasoning behind this, doesn't seem logical at all.

there is `get_self` function to get self pointer since this pointer is needed extensively in code. To avoid duplication it might not have been to player list. We usually see this practice in code

**Comment by xiaoxiao921** [comment]
... What?

**Comment by lonelybud** [comment]
there is lot of things like processing in `assign_physical_index` where we dont want to run check on ourselves? just one example - 

https://github.com/YimMenu/YimMenu/blob/8bbab4c76531a905a885f667af34315516489534/src/hooks/player_management/assign_physical_index.cpp#L93

**Pull request closed without merging**
