### PR TITLE
feat(Ped): Play Animation

### LINKED ISSUE #187: 💡 [Animations]
**Is your feature request related to a problem? Please describe.**
👎

**Describe the solution you'd like**
   [Self]
         ↳ [Animations]

**Provide Reasoning**
They're always nice to have, for various reasons, and it would be safer and easier than loading an outdated SP ASI.

**Additional context**
_e.g. : Add a premade list, and/or "Play by name" + "Save & Load / Favorite" buttons._

### PR DESCRIPTION
**Pull request by Aure7138**
[Imgur](https://imgur.com/aoHEc4c)

### CODE REVIEW

**Comment by Aure7138** [comment]
There are too many animations in animDictsCompact.json and it will freeze the imgui interface

**Comment by Yimura** [comment]
You can try using the thread pool to handle parsing of the JSON file.

**Comment by Aure7138** [comment]
Not at load time, but at display time, I used data/animations.hpp instead

**Comment by Aure7138** [comment]
If all the animations in json are displayed, just display, without filtering, the interface is already very stuck

**Pull request closed without merging**
