### PR TITLE
fix(exception_handler): crash on unload

### LINKED ISSUE #1256: [Bug]: Yim Crashes on Unload
### Describe the bug

When clicking unload in online or story mode the game just freezes then crashes. Sometimes it unloads and the other times it freezes

### Steps To Reproduce

1. Enter online or story mode
2. unload
3. observe

### Expected Behavior

the menu to unload per usual

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11245020/cout.log)

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by Yimura**
Fixes #1256

### CODE REVIEW

**Comment by D-Borkan** [comment]
with this fix still .

but i used this old and work fine and no crash when unload

exception_handler::exception_handler()
	{
		m_exception_handler = AddVectoredExceptionHandler(1, &vectored_exception_handler);
	}

	exception_handler::~exception_handler()
	{
		RemoveVectoredExceptionHandler(m_exception_handler);
	}

and

class exception_handler final
	{
	public:
		exception_handler();
		virtual ~exception_handler();

	private:
		void* m_exception_handler;
	};

	extern LONG vectored_exception_handler(EXCEPTION_POINTERS* exception_info);

**Comment by xiaoxiao921** [comment]
SetUnhandledExceptionFilter return value should probably be stored and restored when needed

**Comment by D-Borkan** [comment]
work fine , I tested it now

**Comment by Yimura** [comment]
> work fine , I tested it now

It works? No crashes?

**Comment by D-Borkan** [comment]
> > work fine , I tested it now
> 
> It works? No crashes?

yes i tested both in sp and online and no crash when unload

**Comment by Yimura** [comment]
> yes i tested both in sp and online and no crash when unload

Epic! I'll merge it in master then, you'll have to wait a bit before the nightly build is updated.

**Pull request merged**
