### PR TITLE
feat(Vehicle): Added vehicle dirt control

### PR DESCRIPTION
**Pull request by Democles85**
image

### CODE REVIEW

**Comment by gir489returns** [comment]
Why isn't there a checkbox for enabling keep_vehicle_clean? Also, if you have Always Vehicle Repaired and keep_vehicle_clean on, they will both set the dirt level. Check for this collision.

**Comment by Democles85** [comment]
> Why isn't there a checkbox for enabling keep_vehicle_clean? Also, if you have Always Vehicle Repaired and keep_vehicle_clean on, they will both set the dirt level. Check for this collision.

I do have a checkbox for keep vehicle clean. I will add the check for that collision, thanks

Edit: The checkbox is in the main view for the Vehicle Controls, thought that would be better to have it there, and if you want to control the dirt level, you just use Fun Features.

**Review by Yimura — DISMISSED** [review]
Waiting for a PR on the translation repo before I add it.

**Comment by Democles85** [comment]
> Waiting for a PR on the translation repo before I add it.

Added it!

**Review by Yimura — APPROVED** [review]

**Pull request merged**
