### PR TITLE
Fix remove all weapons

### PR DESCRIPTION
**Pull request by tyackman**

### CODE REVIEW

**Comment by Aure7138** [comment]
I noticed you used fix for the title, did the original one not work or

**Comment by tyackman** [comment]
No, it did not work.

**Comment by Aure7138** [comment]
I remember that it is working for self, and it should be working for NPCs. If you are referring to players, just remind players that they can protect against this event

**Comment by tyackman** [comment]
Yes I am aware, it is for other players who do not block the event. Thank you.

**Comment by Adler-D3R** [comment]
This Native does not work on players. However, removing weapons one by one will work. The fix he provided should be working fine.

**Comment by Primexz** [comment]
Maybe we could check here if we run the function on ourselves or on other players.

**Comment by SkiddyToast** [comment]
Try this, there might be a check for players in the native:

```c++
// E9 ? ? ? ? 48 83 B8 B0 10 00 00 00 .add(1).rip()
using remove_all_weapons_event_trigger_t = void(*)(CPed* pPed);
```

**Pull request closed without merging**
