### PR TITLE
Nightly but better

### LINKED ISSUE #2787: [Request]: Add /Zi flag / .pdb to CI / nightly
### Problem

A bit annoying to having to locally compile the linked commit in cout.log issues

### Solution

zi flag in the build step will generate debug symbols in pdb file

### Reason

Allow to easily link back symbols through the .pdb file for easier debugging

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Closes #2787

### CODE REVIEW

**Review by Yimura — COMMENTED** [review]
This still will only partially help us as long as a user was using the latest version of YimMenu at the time (aka. no new nightly has been pushed).

**Comment by gir489returns** [comment]
> This still will only partially help us as long as a user was using the latest version of YimMenu at the time (aka. no new nightly has been pushed).

Should be able to tie the build he was using from the commit hash in their log.

**Comment by Yimura** [comment]
> Should be able to tie the build he was using from the commit hash in their log.

Still no PDB that's easily downloadable for said DLL in case of a new nightly being release which is what this PR was intending to solve.

**Comment by xiaoxiao921** [comment]
the pdb will show up in the artifact.

**Comment by Yimura** [comment]
> the pdb will show up in the artifact.

Yeah just noticed I'm mentally challenged...

**Review by Yimura — APPROVED** [review]

**Pull request merged**
