### PR TITLE
Fix crash reaction and add more translation key

### LINKED ISSUE #1841: [Bug]: Reaction options do not work for all crashes
### Describe the bug

reaction-Crash-kick/timeout/Add to player DB/block join is only effective for script event crash. For other crashes, a different reaction method is used in notify.hpp, where only log and notify work.

### Steps To Reproduce

1.Enable reaction-Crash-kick.
2.Yimmenu only detected and blocked the crash(TSE crashes are an exception).

### Expected Behavior

 Reaction options work for all crashes

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by sch-lda**
1.closes https://github.com/YimMenu/YimMenu/issues/1841
2.Add more translation keys
(Changes made to CMakeLists.txt will be removed in the last commit)

### CODE REVIEW

**Comment by gir489returns** [comment]
Can you explain the need for the CMake changes?

**Comment by sch-lda** [comment]
> Can you explain the need for the CMake changes?

Test Chinese translation. I'm building Yimmenu on a computer with Chinese Windows11

**Comment by gir489returns** [comment]
> > Can you explain the need for the CMake changes?
> 
> Test Chinese translation. I'm building Yimmenu on a computer with Chinese Windows11

Please remove them when you finalize this. Thank you.

**Comment by sch-lda** [comment]
image
I got it, thank you.

**Review by Yimura — APPROVED** [review]
Code looks good :+1:

In regards to the changes you did in the CMakeLists.txt file, was that necesarry to make the build work on Visual Studio / Visual Studio Code? Just wondering as some Chinese users have reported issues building YimMenu meanwhile the version from CI/nightly works perfectly fine without the extra changes to CMakeLists.txt.
Also on what are you building? Visual Studio or Visual Studio Code?

I've merged on the Translation repo, so they should be ready for when this gets merged.

**Comment by sch-lda** [comment]
> Code looks good 👍
> 
> In regards to the changes you did in the CMakeLists.txt file, was that necesarry to make the build work on Visual Studio / Visual Studio Code? Just wondering as some Chinese users have reported issues building YimMenu meanwhile the version from CI/nightly works perfectly fine without the extra changes to CMakeLists.txt. Also on what are you building? Visual Studio or Visual Studio Code?
> 
> I've merged on the Translation repo, so they should be ready for when this gets merged.

I am using Visual Studio 2022 on Windows11.  If I don't make changes to the CMakeLists.txt, the compilation cannot be completed, and I'm not sure of the reasons. This issue has been persistent for a long time since switched to CMAKE(When using Premake, g3log.hpp needs to be manually changed to UTF-8-withbom encoding.). If COMPILE_WARNING_AS_ERROR is not changed to OFF, there will be numerous different errors during compilation that will prevent it from proceeding. If the /utf-8 parameter is not added, Yimmenu will crash when the first Chinese notification pops up.
EDIT:  The issue of Yimmenu crashing when the first Chinese notification pops up first appeared in  testing Translation service branch

**Pull request merged**
