### PR TITLE
feat(Vehicle): Gift to self or other player

### LINKED ISSUE #169: Gifting vehicles
**Additional context**
Add a feature to gift vehicles to players.

### PR DESCRIPTION
**Pull request by mentolixite**
Closes #169.

### CODE REVIEW

**Comment by mentolixite** [comment]
Please note that the garage must be full, as mentioned by @SkiddyToast in #169.

**Comment by Yimura** [comment]
Maybe add an explanation for the user on how to use this feature, as I've seen many people ask how the gift vehicle feature works.

Aside from that I feel kind of iffy on adding this as it falls under the recovery section and I would like to stay away from that.

**Comment by mentolixite** [comment]
> Maybe add an explanation for the user on how to use this feature, as I've seen many people ask how the gift vehicle feature works.

Sure, where should I add it?

> Aside from that I feel kind of iffy on adding this as it falls under the recovery section and I would like to stay away from that.

What do you mean?

**Comment by xM4ddy** [comment]
> What do you mean?

Some cars can be sold for ~1m that you gift to people. YimMenu tries to avoid toxic and recovery options to not attract attention.

**Comment by mentolixite** [comment]
Oh, I thought there was a limit.

**Comment by xM4ddy** [comment]
Due to the mentioned reason it has been discussed and decided that  this feature no longer fits in the vision of YimMenu.

**Pull request closed without merging**
