### PR TITLE
Added proofs to vehicle menu and improved waterproof feature.

### LINKED ISSUE #331: [Bug]: Preview PV doesn't work if Spawn vehicle preview isn't enabled
### Describe the bug

Preview vehicle option for PV only works when preview option in spawn vehicle is enabled. Its not independent

### Steps To Reproduce

1. Enable preview for PV
2. Disable preview in Spawn tab
3. Hover over any vehicle in the PV vehicle list
4. Vehicle won't preview [Bug]

### Expected Behavior

PV should be previewed on hover

### Screenshots and/or Logs

```
<paste your logs here>
```
image

### Store

Epic Games

### Additional context

PV -> Personal vehicle

In step 2 if preview is enabled in spawn tab, vehicle in PV tab will be previewed on hover.

image

### Build

- [X] I used YimMenu unmodified

### PR DESCRIPTION
**Pull request by aa15032261**
- Added proofs section to vehicle menu that allows player to control damage bits. 
- Player can now drive or walk underwater with waterproof turned on.
- Added bring closest vehicle feature.
- Vehicle will not deform with collision proof on.
- Improved vehicle menu arrangement.
- Added plate changer in LSC.
- Updated LSC layout.
- Expanded wheel type feature.
- Fixed a bug where the mod section shows repetitive wheel mods.

### CODE REVIEW

**Comment by mentolixite** [comment]
Tested, everything appears to work fine. Driving on the sea bed is amazing!

On a somewhat unrelated note: could you add an option to change the vehicle's plate ID after it's already spawned?

**Comment by aa15032261** [comment]
> Tested, everything appears to work fine. Driving on the sea bed is amazing!
> 
> On a somewhat unrelated note: could you add an option to change the vehicle's plate ID after it's already spawned?

Thanks for the feedback. I've made some changes in the latest commit:
- Added plate changer in LSC.
- Updated LSC layout.
- Expanded wheel type feature.
- Fixed a bug where the mod section shows repetitive wheel mods.

image

**Comment by mentolixite** [comment]
Thanks!

Everything appears to work as intended and the entire Vehicle menu is MUCH better compared to before.

**Comment by aa15032261** [comment]
More changes:
- Fixed Issue #331.
- Added plate style feature to LSC.

**Review by Yimura — APPROVED** [review]
Code looks good, haven't had the change to test any of this yet.

~~Does this fix #331?~~ Nvm saw you fixed it

**Comment by Yimura** [comment]
One problem I've noticed is that people with an old vehicle cache won't be able to use the spawn feature.

**Pull request merged**
