### PR TITLE
Added G's Cache to ESP.

### PR DESCRIPTION
**Pull request by gir489returns**

### CODE REVIEW

**Comment by gir489returns** [comment]
image

This doesn't seem to be working.

**Comment by DayibBaba** [comment]
> This doesn't seem to be working.

The pools and the objects do not always behave as expected. There seems to be a discrepancy in what objects are harbored in the pools we access and what objects we observe in game.

**Comment by gir489returns** [comment]
@DayibBaba Do networked entities have their own pool?

**Comment by gir489returns** [comment]
@Yimura Is there something holding this PR up? I tested it again this morning, it works fine.

image
image
image

**Review by Yimura — APPROVED** [review]

**Pull request merged**
