### PR TITLE
Fix for GTA Build 3179

### LINKED ISSUE #2945: [Bug]: Game Crash
### Describe the bug

The Game crashes when injecting after latest rockstar update

### Steps To Reproduce

1. Start the game
2 Inject

### Expected Behavior

not to crash

### Logs and/or screenshots

```
Apparently, the log is too long to be pasted here so i will upload it here instead https://gist.github.com/poweromania/1abb97861ae4076a3f2ce52f48e2d4e9


```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by xiaoxiao921**
This most likely mean they changed things related to security this patch. Fix #2945

### CODE REVIEW

**Comment by poweromania** [comment]
This fixes the initial crashing problem, but the game will still crash if you try to join a session with "kick host durin join" active.

**Comment by TBNRkenhutt** [comment]
The file itself is fine. When i tired to inject it, is fine. But when i tried to spawn a vehicle or do anything, it'll crash the game.

**Comment by TBNRkenhutt** [comment]
> The file itself is fine. When i tired to inject it, is fine. But when i tried to spawn a vehicle or do anything, it'll crash the game.

The new problem is spawning vehicle, joining session with the menu, and doing anything related to the character

**Comment by xiaoxiao921** [comment]
Waiting on https://github.com/Yimura/GTAV-Classes/pull/169

**Review by Yimura — DISMISSED** [review]
Just the dependency to update and then it can be merged.

**Comment by JBoogieman** [comment]
I'm still pretty new to git and how everything works, does this mean latest pull or update is still being tested?

**Comment by kub0vvik** [comment]
where i can download this build yimmenu?

**Comment by JBoogieman** [comment]
> where i can download this build yimmenu?

I don't know if it is public yet. I still get the crashing with the original files and with the binaries provided I can get it to inject, but like someone said up before you can't tp, or spawn stuff.

**Comment by xiaoxiao921** [comment]
The pr is not done, not home so can't finish it right now

**Comment by Toasty8i** [comment]
> The pr is not done, not home so can't finish it right now
Can i build it myself?

**Comment by D-Borkan** [comment]
> > The pr is not done, not home so can't finish it right now
> 
> Can i build it myself?

as he said @xiaoxiao921 it's not done for yet , just wait

**Comment by ghost** [comment]
I really dont know how to even get the binarys provided here to work. Will the fix for this ultimatly be a new YimMenu.dll i can download and inject or do i have to rebuild the whole thing? I deleted all my folders of it cause i thought i did smth wrong

**Comment by TBNRkenhutt** [comment]
> I really dont know how to even get the binarys provided here to work. Will the fix for this ultimatly be a new YimMenu.dll i can download and inject or do i have to rebuild the whole thing? I deleted all my folders of it cause i thought i did smth wrong

It should be the same as usual but the dll file has to be changed to the binary one, and don't forget to remove the old dll file from the injector. The only thing you need to delete when you have problem with the YimMenu is the cache, if you delete other things, it might cause problem to the whole program

**Comment by ghost** [comment]
> > I really dont know how to even get the binarys provided here to work. Will the fix for this ultimatly be a new YimMenu.dll i can download and inject or do i have to rebuild the whole thing? I deleted all my folders of it cause i thought i did smth wrong
> 
> It should be the same as usual but the dll file has to be changed to the binary one, and don't forget to remove the old dll file from the injector. The only thing you need to delete when you have problem with the YimMenu is the cache, if you delete other things, it might cause problem to the whole program

ok i will try that. maybe i also build the whole thing wrong now. idk if i can get my additional scripts working again. Also there is no YimMenu discord right?

**Comment by TBNRkenhutt** [comment]
> > > I really dont know how to even get the binarys provided here to work. Will the fix for this ultimatly be a new YimMenu.dll i can download and inject or do i have to rebuild the whole thing? I deleted all my folders of it cause i thought i did smth wrong
> > 
> > 
> > It should be the same as usual but the dll file has to be changed to the binary one, and don't forget to remove the old dll file from the injector. The only thing you need to delete when you have problem with the YimMenu is the cache, if you delete other things, it might cause problem to the whole program
> 
> ok i will try that. maybe i also build the whole thing wrong now. idk if i can get my additional scripts working again. Also there is no YimMenu discord right?

Maybe you can clear everything out so YimMenu can rebuild everything and have a clean slate. Also I don't know about YimMenu discord, maybe there is, maybe there isn't.

**Comment by ghost** [comment]
> > > > I really dont know how to even get the binarys provided here to work. Will the fix for this ultimatly be a new YimMenu.dll i can download and inject or do i have to rebuild the whole thing? I deleted all my folders of it cause i thought i did smth wrong
> > > 
> > > 
> > > It should be the same as usual but the dll file has to be changed to the binary one, and don't forget to remove the old dll file from the injector. The only thing you need to delete when you have problem with the YimMenu is the cache, if you delete other things, it might cause problem to the whole program
> > 
> > 
> > ok i will try that. maybe i also build the whole thing wrong now. idk if i can get my additional scripts working again. Also there is no YimMenu discord right?
> 
> Maybe you can clear everything out so YimMenu can rebuild everything and have a clean slate. Also I don't know about YimMenu discord, maybe there is, maybe there isn't.

I did redo all the steps. deleted every folder that it has created. cloned the repo and rebuild via Visual studio. works and doesnt crash with the binarys provided up top but crashes when doing certan things. so gotta wait when the newest fix comes out

**Comment by TBNRkenhutt** [comment]
> > > > > I really dont know how to even get the binarys provided here to work. Will the fix for this ultimatly be a new YimMenu.dll i can download and inject or do i have to rebuild the whole thing? I deleted all my folders of it cause i thought i did smth wrong
> > > > 
> > > > 
> > > > It should be the same as usual but the dll file has to be changed to the binary one, and don't forget to remove the old dll file from the injector. The only thing you need to delete when you have problem with the YimMenu is the cache, if you delete other things, it might cause problem to the whole program
> > > 
> > > 
> > > ok i will try that. maybe i also build the whole thing wrong now. idk if i can get my additional scripts working again. Also there is no YimMenu discord right?
> > 
> > 
> > Maybe you can clear everything out so YimMenu can rebuild everything and have a clean slate. Also I don't know about YimMenu discord, maybe there is, maybe there isn't.
> 
> I did redo all the steps. deleted every folder that it has created. cloned the repo and rebuild via Visual studio. works and doesnt crash with the binarys provided up top but crashes when doing certan things. so gotta wait when the newest fix comes out

Yes, the dll file when injected is still fine, doing some things are fine, but when you mess with vehicle spawner or player settings, it'll just crashes itself.

**Comment by Rxann** [comment]
I am guessing you guys are having issues because this update is not included in the code you are trying to build 💀

**Comment by ghost** [comment]
Maybe yeah idk. Not at home so can’t confirm.
I just downloaded the binary’s provided above and use those as the dll instead of the latest Nightly release.
Can you enlighten me and tell me how I should’ve done it? :)
Also do you have any info on when this is gonna be merged into the main branch so it’s available to everyone via the main zip/clone?

**Comment by poweromania** [comment]
> Maybe yeah idk. Not at home so can’t confirm. I just downloaded the binary’s provided above and use those as the dll instead of the latest Nightly release. Can you enlighten me and tell me how I should’ve done it? :) Also do you have any info on when this is gonna be merged into the main branch so it’s available to everyone via the main zip/clone?

And that dll from the file above will only fix the injection crash but causes other crashes in the game. As of right now the issue has not been fixed.

**Comment by ghost** [comment]
Oh yeah just now OP made another change. And ik that the new DLL doesn’t fix the crashes. It only fixes the initial injection error.
I hope it gets fixed rather quick lol

**Comment by Yimura** [comment]
After code is added the link isn't immediately updated with a new DLL file, so obviously you won't spot any change. Give it 10 minutes before judging.

**Review by Yimura — APPROVED** [review]
Untested

**Comment by ghost** [comment]
Ok but the binary.zip in an earlier comment will than have these changes made just now? I will try these when I get home

**Comment by Yimura** [comment]
> Ok but the binary.zip in an earlier comment will than have these changes made just now? I will try these when I get home

If it works I'll merge it into master and build a new nightly as there's no reason to not immediately push an update with it being broken entirely.

For now be patient and don't bump the thread so often.

**Comment by xiaoxiao921** [comment]
Just tested the last build while playing online and everything seems to work.

**Pull request merged**
