### PR TITLE
feat(Session): Added local time modifiers

### PR DESCRIPTION
**Pull request by xM4ddy**

### CODE REVIEW

**Review by VolkerSchlegel — APPROVED** [review]
Looks good to me

**Comment by Yimura** [comment]
PR is still a draft, @xM4ddy needs to mark it as ready or tell us it's ready before it can be merged.

**Comment by xM4ddy** [comment]
whoops thats not right

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
@LiamD-Flop can you check if this feature works as intended, I'm not able to test it currently.

**Review by LiamD-Flop — APPROVED** [review]
Works as intended

**Review by GeopJr — APPROVED** [review]

**Pull request merged**
