### PR TITLE
Improve Aimbot

### PR DESCRIPTION
**Pull request by Sys0xdbg**
Todo
------
Fix aimbot  when in vehicle
[Video](https://www.youtube.com/watch?v=8g1ZiXLJ4E0)

### CODE REVIEW

**Comment by gir489returns** [comment]
What is the purpose of this? You're just recommitting the same changes as #2480.

**Comment by Sys0xdbg** [comment]
> What is the purpose of this? You're just recommitting the same changes as #2480.

Its not same. I switched to getting entity by screen distance & 
this issue is fixed:  #2655

**Comment by gir489returns** [comment]
You’re going to have to either make a squash commit that fixes this so I can see what you did, or you’re going to have to make a new PR. In its current state this is unacceptable.

**Comment by Sys0xdbg** [comment]
Okay

**Pull request closed without merging**
