### PR TITLE
fix(cache): fs::path.string() can throw when it try to convert windows utf16 wstring to multi byte std::string when user code page isnt utf8

### LINKED ISSUE #1640: [Bug]: Game crashes while updating cache
### Describe the bug

The DLL built from the latest version of the source code will cause the game to crash when updating the cache after injection

### Steps To Reproduce

1.Open game
2.Injection menu
3.Click to update cache

### Expected Behavior

Updating the cache should not cause the game to crash

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11980424/cout.log)

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Fixes #1640

### CODE REVIEW

**Comment by D-Borkan** [comment]
i tested this fix on both steam and apic and work fine without crash while update cache
but i notice the game freeze while update cache maybe 2-3 sec ,  i think is normal in this case

**Comment by xiaoxiao921** [comment]
Yeah the small freeze is "normal", we'll probably fix it at some point

**Comment by D-Borkan** [comment]
so this fix is ready to merge

**Review by Yimura — APPROVED** [review]
What a pain in the butt...

**Pull request merged**
