### PR TITLE
feat (player database): Add filters to database.

### PR DESCRIPTION
**Pull request by binded-zz**
feat. (player db): adds filters and a friends button

adds filters to player DB
removed all the other stuff no colors 
online/offline only

### CODE REVIEW

**Comment by binded-zz** [comment]
this does not depend on any other merges 
just the mods that i mad

**Comment by TheGreenBandit** [comment]
Instead of making multiple prs you can keep committing on the same branch as your pr to make necessary changes.

**Comment by binded-zz** [comment]
this one is different then the last one i had added code to filter if notify but rxan is not done with that 
this code here is the full thing all set to go every should be set to go unless i got confused and fucked some thing up along the way 

i started off wrong i dont know what im doing so its trial and error 
but im trying i be confusing the shit outta my self

**Comment by Yimura** [comment]
> this one is different then the last one i had added code to filter if notify but rxan is not done with that this code here is the full thing all set to go every should be set to go unless i got confused and fucked some thing up along the way
> 
> i started off wrong i dont know what im doing so its trial and error but im trying i be confusing the shit outta my self

No but still, any changes you make building upon the old code can still be pushed to the PR you opened first hand.
Opening new PR's and keeping on closing old ones because you made a simple incremental change, this is just bad Git etiquette.
This spams the repo with PR's that are just wasted and spams the people that are signed up for email notifications from the repository.

Please be mindful next time.

In regards to features, please try to master the basics a bit more like git for example (which is a core skill of any developer).
I'd prefer it if you experiment a bit more on your own, get used to the code base, make some features in your private fork of YimMenu, learn how to merge upstream from YimMenu/YimMenu into your fork to keep your stuff up-to-date.

Also your code doesn't follow the coding guidelines, please read through the [CONTRIBUTING.md](https://github.com/YimMenu/YimMenu/blob/master/CONTRIBUTING.md) file.

Also the UI you made ain't the prettiest, in its current state I wouldn't merge it.
image
(I took this screenshot from Matrix, didn't bother compiling it)

**Comment by binded-zz** [comment]
i only added the stuff under filter because some one said it was confusing i was going to leave it out the first time 
should that and the tooltips be removed 
idk 
maybe just remove every thing but for the filter green over red and thats it 
and that would solve the my eyes and stuff people keep saying

**Comment by Yimura** [comment]
> i only added the stuff under filter because some one said it was confusing i was going to leave it out the first time should that and the tooltips be removed idk maybe just remove every thing but for the filter green over red and thats it and that would solve the my eyes and stuff people keep saying

If I remember correctly they were specifically complaining about the order of players being completely random.
Currently the player list is grouped by online state and within those groups sorted alphabetically.
Personally this part doesn't require any modification, or at the least not implemented like this.

**Comment by binded-zz** [comment]
there not random at all look at the screen shots again they are alpha a-z just not the colors 
the list is sorta by state online a-z the spacer offline a-z and colors green online and grey off line 

and does the same sort for each filter online a-z offline a-z if they have that checked 
i think it might be best to just remove it all it will remove all confusion period 
ill look in to fixing what ever brackets i fucked up

**Comment by TheGreenBandit** [comment]
Change title to feat (player database): Add filters to database. The parentheses are for the subject you are changing. Afterwards is what u are doing to it.

**Comment by pierrelasse** [comment]
Idea: You can create groups and put players into the group. You can also select (multiple) the displayed groups from a drop-down menu.

**Comment by binded-zz** [comment]
wish i could help with that but the code and that part of the page has since been updated you can use this as a some what base 
there was nothing wrong with the code it self it worked with all of that stuff that i added removed to just a drop down box of a few groups mod, blocked, friends,  
there was just some stuff wrong with the PR formating  spacing and i think maybe the options i think the last option was supoost to be default option instead of like the 1-5  idk 
there was no interest in it 
and they just updated it and still didnt add any extra search 
its like another 20 lines or so or code 

mind you im no coder and it took me days and hours and no lie like 80 builds just to get where i got to

groups i dont even know how i  would add that again going to have to wait for some one to do it or make your own PR

**Comment by binded-zz** [comment]
closing this as things have changed and this no longer applies

**Pull request closed without merging**
