### PR TITLE
fix: Bool CMD hotkey toggle message showing translation key

### PR DESCRIPTION
**Pull request by Yimura**
Issue introduce when we added support for translations in commands.

### CODE REVIEW

**Review by tupoy-ya — APPROVED** [review]
Should work, didn't test.

Commands also check if translation is not empty, no idea if it is needed.
```cpp
std::string key;
if (key = g_translation_service.get_translation(m_label_hash); key.empty())
	key = m_label;
```

**Comment by Yimura** [comment]
The translation service just returns the key passed to it if it doesn't exist in the translation service.

Edit:
Never mind, only the string literal does that.
I'll instead just introduce the behaviour of returning the key passed to it.

Edit edit:
Not possible with how the translation service is coded, I will implement your code instead.

**Comment by Yimura** [comment]
I instead modified the translation service and added fallback key to the joaat version of the `translation_service::get_translation` function.

The string_view version of get_translation then passes the translation_key as a fallback key to the joaat version of get_translation, this way original behaviour is also preserved.

**Review by tupoy-ya — APPROVED** [review]
Looks good to me.

Didn't test.

**Pull request merged**
