### PR TITLE
Added more spam messages to the filter.

### PR DESCRIPTION
**Pull request by gir489returns**

### CODE REVIEW

**Comment by lonelybud** [comment]
why do they spam at such fast rate if you notice.

**Comment by lonelybud** [comment]
i have coded differently in my fork. It works like charm. It detects people as spammers who send a message atleast 56 character long and in a very short time. 
https://github.com/lonelybud/lonelyMenu/blob/aa9b02dd38322a5c81b1dc3d960b912634a47e52/src/hooks/protections/receive_net_message.cpp#L129

**Comment by gir489returns** [comment]
> i have coded differently in my fork. It works like charm. It detects people as spammers who send a message atleast 56 character long and in a very short time. https://github.com/lonelybud/lonelyMenu/blob/aa9b02dd38322a5c81b1dc3d960b912634a47e52/src/hooks/protections/receive_net_message.cpp#L129

I really like that idea, in fact, I'm gonna yoink it.

**Comment by lonelybud** [comment]
there are more features that can be added to yim like - `search bar above player list`, `somewhat improved protection logging algo`, `log who killed you`, `auto fill vehicle missiles`, `chat logging in imgui tab itself (you can translate and reply back)`, `improved token spoofing` etc. from my fork. This was one.

**Comment by lonelybud** [comment]
you can also color code spammer as yellow -
https://github.com/lonelybud/lonelyMenu/blob/aa9b02dd38322a5c81b1dc3d960b912634a47e52/src/views/players/view_players.cpp#L50-L51

**Review by Yimura — APPROVED** [review]

**Pull request merged**
