### PR TITLE
fixed bool_masked

### PR DESCRIPTION
**Pull request by Alice2333g**

### CODE REVIEW

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
Anyone able to confirm this is working as intended?

**Comment by gir489returns** [comment]
No, I don’t use this function.

**Comment by Alice2333g** [comment]
> 有人能够确认这是否按预期工作？

it should 1 size.

it not 8 size.

if size 8 set to 1 bit, the next 7 bits will all be false.

**Comment by gir489returns** [comment]
I don't understand why bit_count is statically declared. It should come from the user.

**Comment by Yimura** [comment]
> I don't understand why bit_count is statically declared. It should come from the user.

No clue I have never used these functions so I wouldn't be able to confirm if this is the correct usage.
At the least this way the function will behave in an expected behaviour, we should still look at changing this or adding another function to toggle multiple bits.

**Comment by xiaoxiao921** [comment]
> I don't understand why bit_count is statically declared. It should come from the user.

This is a helper function, looks like I wrote the 8 by mistake, it should be 1, so thanks for the PR

> > I don't understand why bit_count is statically declared. It should come from the user.
> 
> No clue I have never used these functions so I wouldn't be able to confirm if this is the correct usage. At the least this way the function will behave in an expected behaviour, we should still look at changing this or adding another function to toggle multiple bits.

Already provided, check the other helpers, like `get_masked_int_hash` (they can also call the native directly)

**Pull request merged**
