### PR TITLE
Added pointers for 3950.

### PR DESCRIPTION
**Pull request by gir489returns**
image

At least gets YimMenu in game. However, my account that I have been using has been banned, so I think Yim is detected again.

### CODE REVIEW

**Review by Yimura — APPROVED** [review]

**Comment by gir489returns** [comment]
Fixed an error OOB pointers. All of them should be correct now.

**Comment by YimMenuTheBest** [comment]
When trying to go online you will get this error with this PR

```
[19:15:52.0817328][FATAL/exception_handler.cpp:42] UNKNOWN_EXCEPTION: CODE: 3765269347
Dumping modules:
GTA5.exe Base Address: 0x7FF759EB0000 Size: 67215872
ntdll.dll Base Address: 0x7FF89E090000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FF89D010000 Size: 528384
KERNELBASE.dll Base Address: 0x7FF89BA30000 Size: 1638400
USER32.dll Base Address: 0x7FF89CCB0000 Size: 610304
win32u.dll Base Address: 0x7FF89BA00000 Size: 49152
GDI32.dll Base Address: 0x7FF89BE50000 Size: 57344
gdi32full.dll Base Address: 0x7FF89B5E0000 Size: 675840
msvcp_win.dll Base Address: 0x7FF89B540000 Size: 335872
ucrtbase.dll Base Address: 0x7FF89B700000 Size: 798720
PSAPI.DLL Base Address: 0x7FF89E040000 Size: 4096
WS2_32.dll Base Address: 0x7FF89D0E0000 Size: 290816
RPCRT4.dll Base Address: 0x7FF89DDD0000 Size: 880640
CRYPT32.dll Base Address: 0x7FF89B820000 Size: 1134592
WINTRUST.dll Base Address: 0x7FF89B990000 Size: 307200
VERSION.dll Base Address: 0x7FF890CA0000 Size: 12288
msvcrt.dll Base Address: 0x7FF89CBF0000 Size: 507904
DSOUND.dll Base Address: 0x7FFFCB740000 Size: 491520
IMM32.dll Base Address: 0x7FF89D3E0000 Size: 126976
advapi32.dll Base Address: 0x7FF89BF80000 Size: 434176
SHLWAPI.dll Base Address: 0x7FF89CFB0000 Size: 212992
sechost.dll Base Address: 0x7FF89D160000 Size: 446464
SHELL32.dll Base Address: 0x7FF89C2E0000 Size: 6848512
combase.dll Base Address: 0x7FF89D420000 Size: 2539520
bink2w64.dll Base Address: 0x7FFF9BAA0000 Size: 307712
ole32.dll Base Address: 0x7FF89D7B0000 Size: 909312
OLEAUT32.dll Base Address: 0x7FF89C0D0000 Size: 647168
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFF155A0000 Size: 96256
WININET.dll Base Address: 0x7FF87E100000 Size: 2113536
WINMM.dll Base Address: 0x7FF893B10000 Size: 114688
MF.dll Base Address: 0x7FF894D50000 Size: 372736
shcore.dll Base Address: 0x7FF89DF40000 Size: 684032
MFPlat.DLL Base Address: 0x7FF8942D0000 Size: 1503232
msdmo.dll Base Address: 0x7FFFCB7F0000 Size: 16384
MFReadWrite.dll Base Address: 0x7FFFCB9F0000 Size: 995328
PROPSYS.dll Base Address: 0x7FF896270000 Size: 692224
WTSAPI32.dll Base Address: 0x7FF89A2A0000 Size: 40960
d3d9.dll Base Address: 0x7FF83C5E0000 Size: 1306624
D3DCOMPILER_43.dll Base Address: 0x7FFFC0670000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF85ED30000 Size: 48128
ResampleDmo.DLL Base Address: 0x7FFFCB460000 Size: 503808
DINPUT8.dll Base Address: 0x7FFFBE6B0000 Size: 176128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FF89D950000 Size: 913408
bcrypt.dll Base Address: 0x7FF89AD90000 Size: 110592
IPHLPAPI.DLL Base Address: 0x7FF899F40000 Size: 122880
powrprof.dll Base Address: 0x7FF89A250000 Size: 77824
winmmbase.dll Base Address: 0x7FF86E780000 Size: 102400
cfgmgr32.dll Base Address: 0x7FF89B0F0000 Size: 221184
d3dx9_43.dll Base Address: 0x7FFF15030000 Size: 2280960
dwmapi.dll Base Address: 0x7FF897B70000 Size: 90112
OPENGL32.dll Base Address: 0x7FF812F10000 Size: 798720
dxcore.dll Base Address: 0x7FF898080000 Size: 131072
MFCORE.DLL Base Address: 0x7FF894730000 Size: 3026944
GLU32.dll Base Address: 0x7FF811460000 Size: 126976
UMPDC.dll Base Address: 0x7FF89A230000 Size: 36864
kernel.appcore.dll Base Address: 0x7FF89A4F0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FF89B4C0000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FF8941A0000 Size: 102400
MSASN1.dll Base Address: 0x7FF89B0D0000 Size: 36864
inputhost.dll Base Address: 0x7FF87BA80000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FF897610000 Size: 860160
CRYPTBASE.DLL Base Address: 0x7FF89ABE0000 Size: 12288
sdk_legacy_led_x64.dll Base Address: 0x7FFF14C30000 Size: 2592768
VCRUNTIME140_1.dll Base Address: 0x7FF8726C0000 Size: 15360
MSVCP140.dll Base Address: 0x7FF871020000 Size: 345600
VCRUNTIME140.dll Base Address: 0x7FF871200000 Size: 65024
ZLIB1.dll Base Address: 0x7FF84C120000 Size: 54784
CRYPTSP.dll Base Address: 0x7FF89ABC0000 Size: 57344
rsaenh.dll Base Address: 0x7FF89A450000 Size: 147456
mswsock.dll Base Address: 0x7FF89A970000 Size: 331776
windows.storage.dll Base Address: 0x7FF899330000 Size: 7032832
wintypes.dll Base Address: 0x7FF8991F0000 Size: 544768
dbghelp.dll Base Address: 0x7FF898AA0000 Size: 1646592
dbgcore.DLL Base Address: 0x7FF88F2A0000 Size: 131072
d3d12.dll Base Address: 0x7FF8498D0000 Size: 102400
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFF10E10000 Size: 7229440
WLDAP32.dll Base Address: 0x7FF89C060000 Size: 282624
Normaliz.dll Base Address: 0x7FF89CCA0000 Size: 4096
WINHTTP.dll Base Address: 0x7FF894C10000 Size: 987136
Secur32.dll Base Address: 0x7FF89A2C0000 Size: 12288
SSPICLI.DLL Base Address: 0x7FF89A750000 Size: 126976
uxtheme.dll Base Address: 0x7FF8979F0000 Size: 425984
AudioDevProps2.dll Base Address: 0x7FF8511F0000 Size: 630272
NSI.dll Base Address: 0x1F808B60000 Size: 8192
NahimicOSD.dll Base Address: 0x7FF811380000 Size: 433152
ProductInfo.dll Base Address: 0x7FF8852E0000 Size: 55808
dhcpcsvc6.DLL Base Address: 0x7FF894AD0000 Size: 28672
RTSSHooks64.dll Base Address: 0x180000000 Size: 677888
dhcpcsvc.DLL Base Address: 0x7FF894690000 Size: 69632
AudioDevProps2.dll Base Address: 0x7FF850EF0000 Size: 630272
clbcatq.dll Base Address: 0x7FF89C230000 Size: 471040
dxdiagn.dll Base Address: 0x7FFF9B890000 Size: 253952
d3d11.dll Base Address: 0x7FF898E40000 Size: 1867776
WMICLNT.dll Base Address: 0x7FF8956D0000 Size: 32768
DEVOBJ.dll Base Address: 0x7FF89B0A0000 Size: 110592
dxgi.dll Base Address: 0x7FF8990A0000 Size: 651264
wbemprox.dll Base Address: 0x7FF890F40000 Size: 28672
wbemcomn.dll Base Address: 0x7FF892700000 Size: 311296
napinsp.dll Base Address: 0x7FF86C3A0000 Size: 53248
pnrpnsp.dll Base Address: 0x7FF86C380000 Size: 69632
DNSAPI.dll Base Address: 0x7FF899F70000 Size: 737280
winrnr.dll Base Address: 0x7FF86C360000 Size: 32768
wshbth.dll Base Address: 0x7FF893D60000 Size: 45056
nlansp_c.dll Base Address: 0x7FF86C2A0000 Size: 81920
wbemsvc.dll Base Address: 0x7FF890C80000 Size: 8192
fastprox.dll Base Address: 0x7FF88FE10000 Size: 708608
amsi.dll Base Address: 0x7FF88F240000 Size: 57344
USERENV.dll Base Address: 0x7FF89AA60000 Size: 102400
profapi.dll Base Address: 0x7FF89B330000 Size: 90112
MpOav.dll Base Address: 0x7FF88F1C0000 Size: 204800
directxdatabasehelper.dll Base Address: 0x7FF893DF0000 Size: 196608
nvapi64.dll Base Address: 0x7FF88A7B0000 Size: 6290432
cryptnet.dll Base Address: 0x7FF8907B0000 Size: 139264
drvstore.dll Base Address: 0x7FF891A60000 Size: 1044480
wldp.dll Base Address: 0x7FF89AC70000 Size: 188416
D3D10_1.DLL Base Address: 0x7FFF9BA60000 Size: 147456
d3d10_1core.dll Base Address: 0x7FF8666A0000 Size: 12288
imagehlp.dll Base Address: 0x7FF89C040000 Size: 49152
nvspcap64.dll Base Address: 0x7FFF5E910000 Size: 2056192
ntmarta.dll Base Address: 0x7FF89A510000 Size: 147456
MSCTF.dll Base Address: 0x7FF89CE60000 Size: 1073152
rasadhlp.dll Base Address: 0x7FF894720000 Size: 8192
fwpuclnt.dll Base Address: 0x7FF893250000 Size: 294912
textinputframework.dll Base Address: 0x7FF878150000 Size: 1015808
WINSTA.dll Base Address: 0x7FF899ED0000 Size: 229376
nvldumdx.dll Base Address: 0x7FF88E8E0000 Size: 591872
nvgpucomp64.dll Base Address: 0x7FF888480000 Size: 29061632
nvwgf2umx.dll Base Address: 0x7FF87F030000 Size: 38347264
NvCamera64.dll Base Address: 0x7FFF105A0000 Size: 4240896
WindowsCodecs.dll Base Address: 0x7FF896A00000 Size: 1331200
HID.DLL Base Address: 0x7FF899C30000 Size: 24576
XINPUT9_1_0.dll Base Address: 0x7FF86EEB0000 Size: 8192
MessageBus.dll Base Address: 0x7FF884450000 Size: 5349888
d3dcompiler_47_64.dll Base Address: 0x7FFF14820000 Size: 3922944
nvcuda64.dll Base Address: 0x7FF868C80000 Size: 5758976
dcomp.dll Base Address: 0x7FF896FA0000 Size: 1769472
MMDevApi.dll Base Address: 0x7FF88F320000 Size: 462848
AudioSes.dll Base Address: 0x7FF887170000 Size: 1409024
ProductInfo.dll Base Address: 0x7FF851030000 Size: 56320
XAudio2_7.dll Base Address: 0x7FFF22BC0000 Size: 485376
resourcepolicyclient.dll Base Address: 0x7FF897E40000 Size: 36864
Windows.UI.dll Base Address: 0x7FF885A30000 Size: 966656
avrt.dll Base Address: 0x7FF8991B0000 Size: 8192
gpapi.dll Base Address: 0x7FF89AA00000 Size: 77824
WINNSI.DLL Base Address: 0x7FF897BA0000 Size: 16384
DPAPI.dll Base Address: 0x7FF89B160000 Size: 8192
socialclub.dll Base Address: 0x7FFF13870000 Size: 5133824
chrome_elf.dll Base Address: 0x7FFFC81C0000 Size: 676864
libcef.dll Base Address: 0x7FFEEB670000 Size: 109744128
COMDLG32.dll Base Address: 0x7FF89BE80000 Size: 778240
NETAPI32.dll Base Address: 0x7FF88E770000 Size: 49152
UIAutomationCore.DLL Base Address: 0x7FF867C90000 Size: 3063808
OLEACC.dll Base Address: 0x7FF88D270000 Size: 274432
COMCTL32.dll Base Address: 0x7FF88E790000 Size: 573440
DWrite.dll Base Address: 0x7FF8986D0000 Size: 1650688
WINSPOOL.DRV Base Address: 0x7FF88D2E0000 Size: 405504
USP10.dll Base Address: 0x7FF8393D0000 Size: 4096
dxva2.dll Base Address: 0x7FF839730000 Size: 102400
credui.dll Base Address: 0x7FFFCEF50000 Size: 65536
urlmon.dll Base Address: 0x7FF87BC90000 Size: 1298432
CRYPTUI.dll Base Address: 0x7FFFCEEF0000 Size: 278528
ncrypt.dll Base Address: 0x7FF89AD60000 Size: 114688
wevtapi.dll Base Address: 0x7FF894270000 Size: 282624
ESENT.dll Base Address: 0x7FF887BC0000 Size: 3145728
netutils.dll Base Address: 0x7FF899E50000 Size: 20480
srvcli.dll Base Address: 0x7FF892240000 Size: 57344
iertutil.dll Base Address: 0x7FF88E360000 Size: 557056
WKSCLI.DLL Base Address: 0x7FF893F20000 Size: 49152
SAMCLI.DLL Base Address: 0x7FF892400000 Size: 61440
NTASN1.dll Base Address: 0x7FF89AD20000 Size: 69632
MessageBus.dll Base Address: 0x7FFFB5870000 Size: 5349888
FirewallAPI.dll Base Address: 0x7FF899DA0000 Size: 385024
fwbase.dll Base Address: 0x7FF899D20000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FF88A670000 Size: 245760
wdmaud.drv Base Address: 0x7FF84D5D0000 Size: 200704
ksuser.dll Base Address: 0x7FF885D60000 Size: 8192
msacm32.drv Base Address: 0x7FF866480000 Size: 20480
MSACM32.dll Base Address: 0x7FF850ED0000 Size: 77824
midimap.dll Base Address: 0x7FF852760000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FF877650000 Size: 45056
CoreUIComponents.dll Base Address: 0x7FF8933A0000 Size: 2039296
gAf60PlRqLQKVWeepYTuQieFb.dll Base Address: 0x7FFEE9310000 Size: 29551104
D3DCOMPILER_47.dll Base Address: 0x7FF896BB0000 Size: 3043328
xinput1_4.dll Base Address: 0x7FF8883C0000 Size: 32768
schannel.DLL Base Address: 0x7FF89A340000 Size: 561152
ncryptsslp.dll Base Address: 0x7FF88CC90000 Size: 86016
mfsrcsnk.dll Base Address: 0x7FFF0E970000 Size: 1613824
CompPkgSup.DLL Base Address: 0x7FF8875B0000 Size: 167936
Windows.Media.dll Base Address: 0x7FFFCCDF0000 Size: 5029888
mp3dmod.dll Base Address: 0x7FFFB6290000 Size: 65536
Windows.ApplicationModel.dll Base Address: 0x7FF886F30000 Size: 720896
AppXDeploymentClient.dll Base Address: 0x7FF894550000 Size: 815104
Dumping registers:
RAX: 0x7FF898E7BBB1
RCX: 0x1F9F117D3D0
RDX: 0x4370DAD420
RBX: 0x7FFEEB3FD0A8
RSI: 0x4370DADC00
RDI: 0x19930520
RSP: 0x4370DADAA0
RBP: 0x1F9CF8EB480
R8:  0x7FF75B282C4A
R9:  0x4370DAD4C0
R10: 0x7FF75B1C644D
R11: 0x1F93C684098
R12: 0x3FFF
R13: 0x0
R14: 0x16
R15: 0x7FF759EB0000
Dumping stacktrace:
[0]	KERNELBASE.dll RaiseException
[1]	VCRUNTIME140.dll CxxThrowException
[2]	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\optional L: 54 std::_Throw_bad_optional_access
[3]	E:\Programation\Mod Menus\-YimMenu-\YimMenu\src\services\script_patcher\script_patch.cpp L: 58 big::script_patch::update
[4]	E:\Programation\Mod Menus\-YimMenu-\YimMenu\src\services\script_patcher\script_patcher_service.cpp L: 63 big::script_patcher_service::update_all_patches_for_script
[5]	E:\Programation\Mod Menus\-YimMenu-\YimMenu\src\services\script_patcher\script_patcher_service.cpp L: 80 big::script_patcher_service::on_script_load
[6]	E:\Programation\Mod Menus\-YimMenu-\YimMenu\src\hooks\script\init_native_tables.cpp L: 14 big::hooks::init_native_tables
[7]	GTA5.exe+0x161D2CD 0x7FF75B4CD2CD
[8]	GTA5.exe+0xA3C25B 0x7FF75A8EC25B
[9]	GTA5.exe+0xA50CEB 0x7FF75A900CEB
[10]	GTA5.exe+0x1648698 0x7FF75B4F8698
[11]	GTA5.exe+0x130E95A 0x7FF75B1BE95A
[12]	KERNEL32.DLL BaseThreadInitThunk
[13]	ntdll.dll RtlUserThreadStartBad optional access
```

**Comment by gir489returns** [comment]
I can't go online like I mentioned, I got banned, so someone else will have to fix it.

**Comment by Yimura** [comment]
This PR will supersede #2516 after it's merged.

**Review by Yimura — APPROVED** [review]

**Comment by HolyWurl** [comment]
> I can't go online like I mentioned, I got banned, so someone else will have to fix it.

I think actually trigger_event is E8 ? ? ? ? 90 EB 82 CC B5 CC add(1).rip()
If you use your sig, the previous parameters will not correspond. I think there are now five parameters, which can also be seen from freemode

**Comment by gir489returns** [comment]
> > I can't go online like I mentioned, I got banned, so someone else will have to fix it.
> 
> I think actually trigger_event is E8 ? ? ? ? 90 EB 82 CC B5 CC add(1).rip() If you use your sig, the previous parameters will not correspond. I think there are now five parameters, which can also be seen from freemode

That is not correct, what that is, is most likely SEND_TU_SCRIPT_EVENT which calls TRIGGER_SCRIPT_EVENT (you can see it at the bottom of the call stack).

**Comment by ToXicVibezz** [comment]
Yim is working for me and im online with now ! My only error was [19:55:22.9944032][FATAL/pointers.hpp:74 which i believe was MWL.

**Comment by HolyWurl** [comment]
E8 ? ? ? ? 90 EB 82 CC B5 CC add(1).rip():
X53UXGB~C(11N)6{FWQGKTR
84 C9 0F 84 ? ? ? ? 48 89 5C 24 ? 48 89 74 24:
{DD0TY26XCK7E$8W$Z0E$92
freemode call:
LJSUC1DW((T3X9 1%Y4C}W6

v5 = a1, v5 is sub_7FF7D2A2536C second parameter

**Comment by gir489returns** [comment]
0x71A6F836422FDD2B is the hash for SEND_TU_SCRIPT_EVENT which is what I said before.

**Comment by HolyWurl** [comment]
> 0x71A6F836422FDD2B is the hash for SEND_TU_SCRIPT_EVENT which is what I said before.
N1FX_HC` $H{4X7N8(B)A)T
Have you tried to make it work online?
Your function parameter 1 is group, 2 is a1, 3 is args, 4 is size of args

**Pull request merged**
