### PR TITLE
Bumped GTAV-Classes, removed unused declarations and other stuff

### LINKED ISSUE #631: YimMenu has been detected by the sigscanner!
It appears YimMenu has been detected by the sigscanner.
## How?
GTA has started using a new sigscanner and as such we cannot pinpoint what exactly is triggering the AC.
Thus, the old sigscanner we used in our Nightly build should no longer be trusted.

## Crash Log

```cpp
RAX: 0x1
RCX: 0x7FFA40503D44
RDX: 0x0
RBX: 0x2AA88F2A5E0
RSI: 0x12
RDI: 0x2AA973A8430
RSP: 0xEAC35E7A70
RBP: 0xEAC35FFAF0
R8:  0xEAC35E7A08
R9:  0x0
R10: 0x0
R11: 0x246
R12: 0xEAC35E7AF0
R13: 0x7FF6DAE13DC0
R14: 0x0
R15: 0x0

stack dump [0]	 GTA5.exe+0xA90D0B 0x7FF6D8D50D0B
stack dump [1]	 GTA5.exe+0xA90BFB 0x7FF6D8D50BFB
stack dump [2]	 GTA5.exe+0x12BC7F2 0x7FF6D957C7F2
stack dump [3]	 GTA5.exe+0x12C5642 0x7FF6D9585642
stack dump [4]	 KERNEL32.DLL+0x15550 BaseThreadInitThunk
stack dump [5]	 ntdll.dll+0x485B RtlUserThreadStart
```

### Alternative Crash Log
Same sigscanner but different system

```cpp
RAX: 0x1
RCX: 0x7FFA04A51804
RDX: 0x0
RBX: 0x167D6FBA660
RSI: 0x12
RDI: 0x167E6EBA970
RSP: 0x291BCE7920
RBP: 0x291BCFF9A0
R8:  0x291BCE78B8
R9:  0x0
R10: 0x0
R11: 0x246
R12: 0x291BCE79A0
R13: 0x7FF6C7B13DC0
R14: 0x0
R15: 0x0

stack dump [0]	 GTA5.exe+0xA90D0B 0x7FF6C5A50D0B
stack dump [1]	 GTA5.exe+0xA90BFB 0x7FF6C5A50BFB
stack dump [2]	 GTA5.exe+0x12BC7F2 0x7FF6C627C7F2
stack dump [3]	 GTA5.exe+0x12C5642 0x7FF6C6285642
stack dump [4]	 KERNEL32.DLL+0x1335D BaseThreadInitThunk
stack dump [5]	 ntdll.dll+0x67558 RtlUserThreadStart
```

## Identify

Easiest way to identify if a crash is caused by the sigscanner is looking at the stack dump, if you see `GTA5.exe+0xA90D0B`, you can be sure it's the sigscanner.
The register dump is in both cases very similar.

### PR DESCRIPTION
**Pull request by Yimura**
## Changes
 - Removed several unused function declarations in looped.hpp
 - Use `g_running` in system while loop
 - Bumped GTAV-Classes
 - Prevent sigscanner from running (credits to @brunph)

Fixes #631

### CODE REVIEW

**Comment by TheGreenBandit** [comment]
tried it, very laggy, crashing with nothing about crash in log

**Comment by Yimura** [comment]
> tried it, very laggy, crashing with nothing about crash in log

None of the changes I made in this PR should affect performance.

**Comment by 0xEmiil** [comment]
> > tried it, very laggy, crashing with nothing about crash in log
> 
> None of the changes I made in this PR should affect performance.

Work fine for me game feels the good i havent feel performance issues

**Comment by TheGreenBandit** [comment]
Huh i guess its just me, ill have to figure out issue

**Pull request merged**
