### PR TITLE
Multi-kick fix

### LINKED ISSUE #1973: [Bug]: Force session host option no longer works
### Describe the bug

Force session host option no longer works (with and without auto kick enabled)

GTA5 crashes right before it swoop down

### Steps To Reproduce

1. Try to join a session with the mentioned option active

### Expected Behavior

It would try and potentially fail to force me as session host, unless i cannot kick another modder with better kick protection

### Logs and/or screenshots

```
[23:53:38.0890832][DEBUG/logger.cpp:28] Using simple logger.
[23:53:40.9659207][INFO/main.cpp:65] Yim's Menu Initializing
[23:53:40.9659786][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	a47af68384040e6330b863dcf837026eaf4afcf4
	Date:	Sat Aug 12 20:45:28 2023
[23:53:40.9659988][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[23:53:40.9666647][INFO/main.cpp:69] Thread pool initialized.
[23:53:40.9686194][INFO/main.cpp:72] Settings Loaded.
[23:53:40.9686796][DEBUG/thread_pool.cpp:95] Thread 1736 executing settings.cpp:18
[23:53:40.9689431][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[23:53:40.9689508][INFO/pointers.cpp:1548] Loading pointers instance from cache
[23:53:40.9689517][INFO/pointers.cpp:1557] Pointers cache: Loading 181 fields from the cache
[23:53:40.9698703][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[23:53:42.5465972][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[23:53:42.5466136][INFO/pointers.cpp:1548] Loading pointers instance from cache
[23:53:42.5466167][INFO/pointers.cpp:1557] Pointers cache: Loading 5 fields from the cache
[23:53:42.5466478][INFO/main.cpp:75] Pointers initialized.
[23:53:42.5469350][INFO/main.cpp:78] Byte Patch Manager initialized.
[23:53:43.1853916][INFO/main.cpp:81] Renderer initialized.
[23:53:43.5145182][INFO/main.cpp:85] Fiber pool initialized.
[23:53:43.6401071][INFO/main.cpp:88] Translation Service initialized.
[23:53:43.6404600][INFO/main.cpp:91] Hooking initialized.
[23:53:43.6488509][DEBUG/gta_data_service.cpp:162] Loading data from cache.
[23:53:43.6488586][INFO/gta_data_service.cpp:174] Loading 1029 peds from cache.
[23:53:43.6490719][INFO/gta_data_service.cpp:192] Loading 815 vehicles from cache.
[23:53:43.6492572][INFO/gta_data_service.cpp:209] Loading 117 weapons from cache.
[23:53:43.6492592][INFO/gta_data_service.cpp:210] Loading 378 weapon components from cache.
[23:53:43.6492747][DEBUG/gta_data_service.cpp:168] Loaded all data from cache.
[23:53:43.6526870][INFO/tunables_service.cpp:21] Loading tunables from cache
[23:53:43.6527055][INFO/main.cpp:111] Registered service instances...
[23:53:43.6527749][DEBUG/thread_pool.cpp:95] Thread 1748 executing tunables_service.cpp:24
[23:53:43.6529467][INFO/main.cpp:132] Scripts registered.
[23:53:43.6746629][INFO/main.cpp:135] Hooking enabled.
[23:53:43.6747043][INFO/main.cpp:138] Dynamic native hooker initialized.
[23:53:43.6807405][INFO/lua_module.cpp:226] Loaded CasinoPacino.lua
[23:53:43.6855505][INFO/lua_module.cpp:226] Loaded YimNightClub_[unknowncheats.me]_.lua
[23:53:43.6855960][INFO/main.cpp:141] Lua manager initialized.
[23:53:43.6856713][DEBUG/thread_pool.cpp:95] Thread 1748 executing player_database_service.cpp:276
[23:54:26.3834761][INFO/backend.cpp:51] Starting script: Self
[23:54:26.3834949][INFO/backend.cpp:76] Starting script: Weapons
[23:54:26.3835052][INFO/backend.cpp:99] Starting script: Vehicles
[23:54:26.3835187][INFO/backend.cpp:115] Starting script: Miscellaneous
[23:54:26.3835249][INFO/backend.cpp:135] Starting script: Remote
[23:54:26.3835386][INFO/backend.cpp:150] Starting script: Ls customs
[23:54:26.3835455][INFO/backend.cpp:162] Starting script: Rainbow paint
[23:54:26.3836098][INFO/backend.cpp:174] Starting script: Disable Control Action
[23:54:26.3836155][INFO/backend.cpp:187] Starting script: World
[23:54:48.8394486][WARN/reaction.cpp:25] Received Modder Detection from Deep_Space65 (81962084)
[23:57:23.0929077][WARN/reaction.cpp:25] Received Remote Wanted Level On Other Players from TTVNEEKZ0 (182570210)
[23:58:26.9425433][WARN/reaction.cpp:25] Received Remote Wanted Level On Other Players from TTVNEEKZ0 (182570210)
[23:58:57.0104165][WARN/reaction.cpp:25] Received Sound Spam from Deep_Space65 (81962084)
[23:58:57.4543808][WARN/reaction.cpp:25] Received Sound Spam from Deep_Space65 (81962084)
[23:58:57.6564259][WARN/reaction.cpp:25] Received Sound Spam from Deep_Space65 (81962084)
[23:58:57.8582037][WARN/reaction.cpp:25] Received Sound Spam from Deep_Space65 (81962084)
[23:58:58.0655276][WARN/reaction.cpp:25] Received Sound Spam from Deep_Space65 (81962084)
[23:58:58.3161139][WARN/reaction.cpp:25] Received Sound Spam from Deep_Space65 (81962084)
[23:59:21.8374344][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[00:00:12.1432967][WARN/reaction.cpp:25] Received Remote Ragdoll from berryexe (173762278)
[00:00:12.3372224][WARN/reaction.cpp:25] Received Remote Ragdoll from berryexe (173762278)
[00:00:41.4490970][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:41.5422466][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:41.7450648][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:41.9603347][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:42.0009768][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:42.2040344][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:42.3926751][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:42.5854057][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:42.7907477][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:42.9993450][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:43.2472878][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:43.4562340][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:43.6397459][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:43.7072572][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:44.1018549][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:44.1510515][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:44.3526643][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:44.5460767][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:44.6611492][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:44.8594119][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:45.0565216][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:45.1053191][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:45.3030548][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:45.5110458][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:45.5571634][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:45.7497431][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:46.0025089][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:46.1085923][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:46.2634991][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:46.5012374][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:46.7064499][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:46.8716913][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:47.2648798][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:00:47.2656643][WARN/reaction.cpp:25] Received Request Control Event from berryexe (173762278)
[00:08:31.8852510][WARN/reaction.cpp:25] Received Spectate Others from III_lllll_III (143887850)
[00:15:23.4704274][WARN/reaction.cpp:25] Received Modder Detection from laoliu66654321 (217399382)
[00:16:08.2040046][WARN/reaction.cpp:25] Received Modder Detection from Brokegraph2773 (57944436)
[00:20:31.3111585][WARN/reaction.cpp:25] Received Modder Detection from expresbb4 (5546281)
[00:21:53.6325079][WARN/reaction.cpp:25] Received Modder Detection from GMoneyThatSavage (78517318)
[00:22:03.3296023][WARN/reaction.cpp:25] Received Modder Detection from Purps247 (212365169)
[00:23:54.9711836][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 122 bytes for reliable message, free space: 176. Trying to free some memory
[00:23:58.7249756][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 976. Trying to free some memory
[00:24:01.0025939][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 96 bytes for reliable message, free space: 1648. Trying to free some memory
[00:24:01.8481437][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 64. Trying to free some memory
[00:24:01.8482258][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 48. Trying to free some memory
[00:24:01.8482319][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 48. Failed to free some memory, clearing all messages (including reliables) for connection
[00:24:01.8485417][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 32. Trying to free some memory
[00:24:01.8485480][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 32. Failed to free some memory, clearing all messages (including reliables) for connection
[00:24:01.8488559][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 32. Trying to free some memory
[00:24:01.8488627][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 32. Failed to free some memory, clearing all messages (including reliables) for connection
[00:24:01.8491714][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 32. Trying to free some memory
[00:24:01.8491776][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 32. Failed to free some memory, clearing all messages (including reliables) for connection
[00:24:02.0398668][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 128. Trying to free some memory
[00:24:03.3655074][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 336. Trying to free some memory
[00:24:05.7909853][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 48. Trying to free some memory
[00:24:05.7910533][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 80. Trying to free some memory
[00:24:05.7910593][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 80. Failed to free some memory, clearing all messages (including reliables) for connection
[00:24:09.1623638][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 272. Trying to free some memory
[00:24:09.1624189][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 288. Trying to free some memory
[00:24:09.1624271][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 288. Failed to free some memory, clearing all messages (including reliables) for connection
[00:24:09.1629653][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 320. Trying to free some memory
[00:24:09.1629743][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 320. Failed to free some memory, clearing all messages (including reliables) for connection

```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1978: [Bug]: Multi-kick only partially functional
### Describe the bug

As of [a47af68](https://github.com/YimMenu/YimMenu/commit/a47af68384040e6330b863dcf837026eaf4afcf4) this function no longer works.

### Steps To Reproduce

1. Join public session
2. See a cheater try to do something to you
3. Decide to kick them using Multi-kick button
4. Use Multi-kick button to kick
5. Observe the person leave game, but immediately following the message of them leaving, the game freezes up and you have to force quit it.

### Expected Behavior

Ideally, the game would not freeze when kicking a malicious player

### Logs and/or screenshots

```
[21:36:59.4975009][DEBUG/logger.cpp:28] Using simple logger.
[21:37:02.3380434][INFO/main.cpp:65] Yim's Menu Initializing
[21:37:02.3380708][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	a47af68384040e6330b863dcf837026eaf4afcf4
	Date:	Sat Aug 12 20:45:28 2023
[21:37:02.3380816][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[21:37:02.3388533][INFO/main.cpp:69] Thread pool initialized.
[21:37:02.3413357][INFO/main.cpp:72] Settings Loaded.
[21:37:02.3414037][DEBUG/thread_pool.cpp:95] Thread 1784 executing settings.cpp:18
[21:37:02.3419519][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[21:37:02.3419584][INFO/pointers.cpp:1548] Loading pointers instance from cache
[21:37:02.3419599][INFO/pointers.cpp:1557] Pointers cache: Loading 181 fields from the cache
[21:37:02.3433765][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[21:37:04.0332192][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[21:37:04.0332355][INFO/pointers.cpp:1548] Loading pointers instance from cache
[21:37:04.0332383][INFO/pointers.cpp:1557] Pointers cache: Loading 5 fields from the cache
[21:37:04.0332599][INFO/main.cpp:75] Pointers initialized.
[21:37:04.0334688][INFO/main.cpp:78] Byte Patch Manager initialized.
[21:37:04.6449836][INFO/main.cpp:81] Renderer initialized.
[21:37:04.9124413][INFO/main.cpp:85] Fiber pool initialized.
[21:37:05.0363512][INFO/main.cpp:88] Translation Service initialized.
[21:37:05.0366669][INFO/main.cpp:91] Hooking initialized.
[21:37:05.0400598][DEBUG/gta_data_service.cpp:162] Loading data from cache.
[21:37:05.0400660][INFO/gta_data_service.cpp:174] Loading 1029 peds from cache.
[21:37:05.0402681][INFO/gta_data_service.cpp:192] Loading 815 vehicles from cache.
[21:37:05.0404435][INFO/gta_data_service.cpp:209] Loading 117 weapons from cache.
[21:37:05.0404449][INFO/gta_data_service.cpp:210] Loading 378 weapon components from cache.
[21:37:05.0404539][DEBUG/gta_data_service.cpp:168] Loaded all data from cache.
[21:37:05.0441985][INFO/tunables_service.cpp:21] Loading tunables from cache
[21:37:05.0442245][INFO/main.cpp:111] Registered service instances...
[21:37:05.0442969][DEBUG/thread_pool.cpp:95] Thread 1788 executing tunables_service.cpp:24
[21:37:05.0444323][INFO/main.cpp:132] Scripts registered.
[21:37:05.0625130][INFO/main.cpp:135] Hooking enabled.
[21:37:05.0625473][INFO/main.cpp:138] Dynamic native hooker initialized.
[21:37:05.0680298][INFO/lua_module.cpp:226] Loaded CasinoPacino.lua
[21:37:05.0718536][INFO/lua_module.cpp:226] Loaded YimNightClub_[unknowncheats.me]_.lua
[21:37:05.0719196][INFO/main.cpp:141] Lua manager initialized.
[21:37:05.0720058][DEBUG/thread_pool.cpp:95] Thread 1776 executing player_database_service.cpp:276
[21:37:49.9612980][INFO/backend.cpp:51] Starting script: Self
[21:37:49.9613241][INFO/backend.cpp:76] Starting script: Weapons
[21:37:49.9613358][INFO/backend.cpp:99] Starting script: Vehicles
[21:37:49.9613525][INFO/backend.cpp:115] Starting script: Miscellaneous
[21:37:49.9613577][INFO/backend.cpp:135] Starting script: Remote
[21:37:49.9613614][INFO/backend.cpp:150] Starting script: Ls customs
[21:37:49.9613640][INFO/backend.cpp:162] Starting script: Rainbow paint
[21:37:49.9613675][INFO/backend.cpp:174] Starting script: Disable Control Action
[21:37:49.9613718][INFO/backend.cpp:187] Starting script: World
[21:39:04.1455815][WARN/reaction.cpp:25] Received Send To Interior from Porknuts435 (233411927)
[21:40:11.5577666][WARN/reaction.cpp:25] Received Send To Interior from VladimireLenin (97715954)
[21:55:35.6759308][WARN/notify.hpp:30] Blocked rope crash from theo061997 (231858834)
[21:55:35.6759628][WARN/reaction.cpp:25] Received Crash from theo061997 (231858834)
```

### Store

Steam

### Additional context

In this circumstance, i kicked theo061997 and he was kicked. However, my game froze and I had to restart GTA 5 and join a new session afterward.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by ghost**
may close #1978
may close #1973

### CODE REVIEW

**Comment by ghost** [comment]
@twstagg can you check if the game crashes with force session host enabled? And the multi-kick itself. Can you test the artifact below?

**Comment by GTMoraes** [comment]
I find this rather odd. Force Host and Multi Kick have been working to me.        
But if there was something to be found broken, and it was fixed, so great!

**Comment by ghost** [comment]
> I find this rather odd. Force Host and Multi Kick have been working to me. But if there was something to be found broken, and it was fixed, so great!

There, the bug was that he used only the force session host and after he became one, the game was frozen. Although this does not happen with force script host. Perhaps the problem was really in that yield()

**Comment by ghost** [comment]
Generally it works fine

**Comment by BaiFeng666** [comment]
> Generally it works fine

image

after debugging, The error occurs in `m_net_game_player->is_host()`
Even though this looks like an error-free code

**Review by Yimura — APPROVED** [review]
What kind of testing did you do? Where you able to reproduce the issues some users were reporting?

**Comment by ghost** [comment]
the problem was when we send the first 3 types of kick and wait 700ms and after that we did a check, we can't do it because the player doesn't exist. It seems to me that this was the problem. After I removed the yield force session host works again

**Comment by xiaoxiao921** [comment]
not sure what was the original intent for the 700 ms delay (a comment would've been nice by the original implementer) but I doubt removing it is the proper fix here, simply checking for null the pointers sounds much more cleaner.

**Comment by BaiFeng666** [comment]
> What kind of testing did you do? Where you able to reproduce the issues some users were reporting?

I just using visual studio and attach to game, when I use <kick host when force host >, game will crash

**Comment by BaiFeng666** [comment]
> > What kind of testing did you do? Where you able to reproduce the issues some users were reporting?
> 
> I just using visual studio and attach to game, when I use , game will crash

use "kick host when force host"

**Comment by ghost** [comment]
> not sure what was the original intent for the 700 ms delay (a comment would've been nice by the original implementer) but I doubt removing it is the proper fix here, simply checking for null the pointers sounds much more cleaner.

This yield was in the `reaction.cpp` file it was most likely designed so that there would be some kind of gap in time between the reactions

**Comment by BaiFeng666** [comment]
> > not sure what was the original intent for the 700 ms delay (a comment would've been nice by the original implementer) but I doubt removing it is the proper fix here, simply checking for null the pointers sounds much more cleaner.
> 
> This yield was in the `reaction.cpp` file it was most likely designed so that there would be some kind of gap in time between the reactions

when i delete this code, game not crash, that's obviously not the way to write it, maybe it'll help

```
if (!player->is_host() && !g_player_service->get_self()->is_host())
				dynamic_cast<player_command*>(command::get(RAGE_JOAAT("desync")))->call(player, {});
```

**Pull request closed without merging**
