### PR TITLE
Convert MIPH to MPH

### PR DESCRIPTION
**Pull request by Rxann**
More standard version of miles per hour.

### CODE REVIEW

**Comment by gir489returns** [comment]
Should it be MPH not mph? 

image

On most dashboards, MPH is capitalized.

**Comment by rkwapisz** [comment]
> Should it be MPH not mph?
> 
> image
> 
> On most dashboards, MPH is capitalized.

In my car I see both in lowercase. In GTA I don't see any consistency. Sometimes it's capitalized, sometimes it's not. My personal preference would be lowercase mph, km/h, m/s just for coding consistency.

image

image

image

**Comment by gir489returns** [comment]
@rkwapisz Your car is using km/h which should stay the way it is. MPH is always capitalized in every car I've owned.

3000GT:

image

Corolla:

image

Camry:

image

86:

image

**Comment by Rxann** [comment]
> Should it be MPH not mph? 
> 
> 
> 
> image
> 
> 
> 
> On most dashboards, MPH is capitalized.

It is automatically capitalized, as it was this was before for miph and it was displayed as MIPH

**Comment by rkwapisz** [comment]
Sounds good to me.

Happy to see MIPH go away.

**Review by gir489returns — APPROVED** [review]

**Review by Yimura — APPROVED** [review]

**Pull request merged**
