### PR TITLE
Fix multiple crashes.

### LINKED ISSUE #3030: [Bug]: Another crash while joining
### Describe the bug

- Join a player using playerdb
- While joining get warnings that xy is a spammer
- Get very many errors in the console and freeze

### Steps To Reproduce

Idfk

### Expected Behavior

No errors, no spammer warnings because no one was sending a chat message in chat, no freeze

### Logs

```
[15:38:20.9644918][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	7a2540391291b4c35154fcc8ff25ba4df5df5a3b
	Date:	Wed May 1 10:54:28 2024
```

[errors.txt](https://github.com/YimMenu/YimMenu/files/15190685/errors.txt)
(I killed the game after it froze)

### Screenshots / Video

image

### Additional context

This happened two times in a row while joining the same player in the same session.
Would probably happen a third time.

There where also other "players" "spamming" with other weird generated names.

This is pretty weird. A player rejoining within 6 seconds.
Either rockstar optimized gta for a few seconds or something sussy is going on.
```
[15:39:17.5341632][INFO/assign_physical_index.cpp:39] Player left 'wqeqw3434wrweqre' freeing slot #29 with Rockstar ID: 250854872
[15:39:23.5863739][INFO/assign_physical_index.cpp:80] Player joined 'wqewqe234324qweq' allocating slot #29 with Rockstar ID: 250863196
```

### LINKED ISSUE #3032: [Bug]: Received Clone Crash
### Describe the bug

Going to be more proactive about reporting crashes since something funky is going on.

Was in a public session for a while until I got hit with this. Game didn't crash, though, and I was able to rejoin the session.

### Steps To Reproduce

Unknown exactly what triggered it, but stack trace suggests cloning.

### Expected Behavior

Clone handling without crashing.

### Logs

Last output before stack trace:
```
[20:24:43.3390424][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":2000,"char":{"slot":0,"cash":2321620,"bank":513712793,"evc":516034413,"pvc":0,"pxr":0.00000,"nonce":638502782779030008},"c":[-137.23596,-585.42725,211.76277],"pt":3197318994,"vct":0,"vcp":0,"mid":0,"action":"BADSPORT","cat":"GOOD_SPORT","ctx":{}
[20:24:43.3390706][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":2000,"char":{"slot":0,"cash":2321620,"bank":513712793,"evc":516034413,"pvc":0,"pxr":0.00000,"nonce":638502782779030008},"c":[-137.23596,-585.42725,211.76277],"pt":3197318994,"vct":0,"vcp":0,"mid":0,"action":"BADSPORT","cat":"GOOD_SPORT","ctx":{}
[20:28:06.9800156][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DIG; DATA: "gamer":"SC 133384834","action":"RTB","id":-8233441639964578291
[20:28:56.1993699][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
```

Trace

```
[0]     D:\Documents\GitHub\YimMenu\src\hooks\protections\received_clone_remove.cpp L: 8 big::hooks::received_clone_remove
[1]     GTA5.exe+0x16DC4F2 0x7FF643B3C4F2
[2]     GTA5.exe+0x16D3D44 0x7FF643B33D44
[3]     GTA5.exe+0x16D9414 0x7FF643B39414
[4]     GTA5.exe+0x1461FD5 0x7FF6438C1FD5
[5]     GTA5.exe+0x16D9541 0x7FF643B39541
[6]     GTA5.exe+0x1400D52 0x7FF643860D52
[7]     D:\Documents\GitHub\YimMenu\src\hooks\protections\receive_net_message.cpp L: 264 big::hooks::receive_net_message[8]     GTA5.exe+0x1400E05 0x7FF643860E05
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by gir489returns**
Closes #3030
Closes #3032

### CODE REVIEW

**Comment by gir489returns** [comment]
image

I'm still getting an exception on the line when opening the player menu.

**Comment by lonelybud** [comment]
also add the check for `sn_player` pointer - 

```C++
		for (uint32_t i = 0; i < gta_util::get_network()->m_game_session_ptr->m_player_count; i++)
			if (auto sn_player = gta_util::get_network()->m_game_session_ptr->m_players[i])
				if (sn_player && sn_player->m_player_data.m_peer_id_2 == frame->m_peer_id)
				{
					player = g_player_service->get_by_host_token(sn_player->m_player_data.m_host_token);

					if (!player)
						player = g_player_service->get_by_name(sn_player->m_player_data.m_name);
					break;
				}
```

**Comment by gir489returns** [comment]
@lonelybud I have no idea what the hell you are talking about.

**Comment by lonelybud** [comment]
> @lonelybud I have no idea what the hell you are talking about.

just edited can you check my comment again?

**Pull request merged**
