### PR TITLE
improve smart kick

### PR DESCRIPTION
**Pull request by lonelybud**
improvements

- safely kick player with godmode infraction
- only use desync when protection is enabled for self

### CODE REVIEW

**Review by Rxann — COMMENTED** [review]
Should something be done if they have desync protections aswell?

**Comment by lonelybud** [comment]
> Should something be done if they have desync protections aswell?

need to figure out

**Comment by Rxann** [comment]
> > Should something be done if they have desync protections aswell?
> 
> 
> 
> need to figure out

If they have attack w gmode or desync protections use the OOM

**Comment by rkwapisz** [comment]
Why OOM for "attack with god mode"?

Every menu has a god mode option, but not all of them have desync protections.

**Comment by xiaoxiao921** [comment]
What's even the point of using desync inside the smart kick if oom is stronger anyway?

**Comment by lonelybud** [comment]
> What's even the point of using desync inside the smart kick if oom is stronger anyway?

oom is blocked my most menus and will also let the target know who attacked him.

**Comment by lonelybud** [comment]
> Why OOM for "attack with god mode"?
> 
> Every menu has a god mode option, but not all of them have desync protections.

yes you are right. There is one exception where yim users dont spoof god mod and they will be marked with god mod infraction hmn then this pr is still ineffective bcz oom kick is blocked my the menus anyways

**Pull request closed without merging**
