### PR TITLE
Break SC hash / Fix crashes

### LINKED ISSUE #2830: [Bug]: Crashing
### Describe the bug

Crashes when entering or entered online ( Have'nt tested in Singleplayer)

### Steps To Reproduce

1. Go in  a server
2. While joining inject the Menu
3. Wait for a bit then it crashes

### Expected Behavior

play the game normally

### Logs and/or screenshots

[15:52:53.6405702][INFO/main.cpp:155] Settings Loaded.
[15:52:53.6420506][INFO/main.cpp:159] Yim's Menu Initializing
[15:52:53.6420639][INFO/main.cpp:160] Git Info
	Branch:	master
	Hash:	8d0ce1d306ff3b581552319adb15be11a57476f9
	Date:	Tue Mar 12 09:43:08 2024
[15:52:53.6422267][INFO/main.cpp:172] Windows 11 Home Version 22H2 (OS Build 22621.3296)
[15:52:53.6454694][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[15:52:53.6457241][INFO/main.cpp:180] Thread pool initialized.
[15:52:53.6460555][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[15:52:53.6460625][INFO/pointers.cpp:1830] Loading pointers instance from cache
[15:52:53.6460643][INFO/pointers.cpp:1839] Pointers cache: Loading 217 fields from the cache
[15:52:53.6460725][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[15:52:53.6461910][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[15:52:53.6461978][INFO/pointers.cpp:1830] Loading pointers instance from cache
[15:52:53.6461994][INFO/pointers.cpp:1839] Pointers cache: Loading 5 fields from the cache
[15:52:53.6462469][INFO/main.cpp:183] Pointers initialized.
[15:52:53.6462555][INFO/main.cpp:190] Disabled anticheat gameskeleton.
[15:52:53.6466718][INFO/main.cpp:193] Byte Patch Manager initialized.
[15:52:53.6484646][INFO/main.cpp:196] Renderer initialized.
[15:52:53.6572644][INFO/main.cpp:200] Fiber pool initialized.
[15:52:53.6580186][INFO/main.cpp:203] HTTP Client initialized.
[15:52:54.0094758][DEBUG/thread_pool.cpp:96] Thread 17764 executing font_mgr.cpp:103
[15:52:54.0104381][INFO/main.cpp:206] Translation Service initialized.
[15:52:54.0392032][INFO/main.cpp:209] Hooking initialized.
[15:52:54.0440202][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[15:52:54.0440339][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[15:52:54.0443904][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[15:52:54.0447590][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[15:52:54.0447652][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[15:52:54.0448040][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[15:52:54.0477944][DEBUG/thread_pool.cpp:96] Thread 17764 executing player_database_service.cpp:285
[15:52:54.0479617][INFO/main.cpp:230] Registered service instances...
[15:52:54.0481192][INFO/main.cpp:251] Scripts registered.
[15:52:54.1097176][INFO/main.cpp:254] Hooking enabled.
[15:52:54.1109793][INFO/main.cpp:257] Dynamic native hooker initialized.
[15:52:54.1113425][INFO/main.cpp:261] Lua manager initialized.
[15:52:54.1834752][INFO/backend.cpp:53] Starting script: Self
[15:52:54.1834909][INFO/backend.cpp:78] Starting script: Weapons
[15:52:54.1834984][INFO/backend.cpp:101] Starting script: Vehicles
[15:52:54.1835174][INFO/backend.cpp:117] Starting script: Miscellaneous
[15:52:54.1939815][INFO/backend.cpp:138] Starting script: Remote
[15:52:54.1940163][INFO/backend.cpp:153] Starting script: Ls customs
[15:52:54.1940207][INFO/backend.cpp:165] Starting script: Rainbow paint
[15:52:54.1940226][INFO/backend.cpp:177] Starting script: Disable Control Action
[15:52:54.1940254][INFO/backend.cpp:190] Starting script: World
[15:52:54.2039696][INFO/tunables_service.cpp:36] Loading tunables from cache
[15:52:54.2117664][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[15:53:06.5211821][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[15:53:06.5212339][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec
[15:53:10.9574393][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[15:53:13.4321764][FATAL/exception_handler.cpp:42] EXCEPTION_PRIV_INSTRUCTION
Dumping modules:
GTA5.exe Base Address: 0x7FF65B870000 Size: 67215872
ntdll.dll Base Address: 0x7FF8319D0000 Size: 1245184
aswhook.dll Base Address: 0x7FFFF3560000 Size: 48640
KERNEL32.DLL Base Address: 0x7FF831450000 Size: 528384
KERNELBASE.dll Base Address: 0x7FF82F0A0000 Size: 1638400
USER32.dll Base Address: 0x7FF830D60000 Size: 606208
win32u.dll Base Address: 0x7FF82F630000 Size: 49152
GDI32.dll Base Address: 0x7FF830330000 Size: 57344
gdi32full.dll Base Address: 0x7FF82EDC0000 Size: 675840
msvcp_win.dll Base Address: 0x7FF82EEE0000 Size: 335872
ucrtbase.dll Base Address: 0x7FF82EF80000 Size: 798720
PSAPI.DLL Base Address: 0x7FF831970000 Size: 4096
WS2_32.dll Base Address: 0x7FF830CE0000 Size: 290816
RPCRT4.dll Base Address: 0x7FF831330000 Size: 876544
VERSION.dll Base Address: 0x7FF8270A0000 Size: 12288
DSOUND.dll Base Address: 0x7FF806ED0000 Size: 491520
CRYPT32.dll Base Address: 0x7FF82F4C0000 Size: 1134592
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFFC6D90000 Size: 96256
msvcrt.dll Base Address: 0x7FF830020000 Size: 507904
advapi32.dll Base Address: 0x7FF82F980000 Size: 438272
WINTRUST.dll Base Address: 0x7FF82F450000 Size: 307200
sechost.dll Base Address: 0x7FF82FEC0000 Size: 458752
IMM32.dll Base Address: 0x7FF830F10000 Size: 126976
bink2w64.dll Base Address: 0x7FFFCE7C0000 Size: 307712
bcrypt.dll Base Address: 0x7FF82ED90000 Size: 110592
ole32.dll Base Address: 0x7FF830F50000 Size: 905216
SHLWAPI.dll Base Address: 0x7FF830C60000 Size: 212992
combase.dll Base Address: 0x7FF8315E0000 Size: 2535424
SHELL32.dll Base Address: 0x7FF8303F0000 Size: 6860800
OLEAUT32.dll Base Address: 0x7FF830250000 Size: 647168
WINMM.dll Base Address: 0x7FF827720000 Size: 114688
WININET.dll Base Address: 0x7FF80E0D0000 Size: 2113536
MF.dll Base Address: 0x7FF829620000 Size: 368640
shcore.dll Base Address: 0x7FF82F880000 Size: 684032
MFPlat.DLL Base Address: 0x7FF828E30000 Size: 1503232
MFReadWrite.dll Base Address: 0x7FFFD1140000 Size: 995328
msdmo.dll Base Address: 0x7FFFE2880000 Size: 16384
PROPSYS.dll Base Address: 0x7FF829C50000 Size: 692224
ResampleDmo.DLL Base Address: 0x7FF803D20000 Size: 503808
WTSAPI32.dll Base Address: 0x7FF82DBF0000 Size: 40960
d3d9.dll Base Address: 0x7FFFE4F60000 Size: 1306624
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF805D30000 Size: 48128
D3DCOMPILER_43.dll Base Address: 0x7FFFC6B20000 Size: 2423296
DINPUT8.dll Base Address: 0x7FF800DB0000 Size: 176128
IPHLPAPI.DLL Base Address: 0x7FF82D840000 Size: 122880
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FF82FA40000 Size: 913408
powrprof.dll Base Address: 0x7FF82DBA0000 Size: 77824
d3dx9_43.dll Base Address: 0x7FFFC6650000 Size: 2280960
winmmbase.dll Base Address: 0x7FF805FD0000 Size: 102400
cfgmgr32.dll Base Address: 0x7FF82EA00000 Size: 221184
dwmapi.dll Base Address: 0x7FF82C4E0000 Size: 90112
OPENGL32.dll Base Address: 0x7FFFD3960000 Size: 798720
dxcore.dll Base Address: 0x7FF82C370000 Size: 139264
MFCORE.DLL Base Address: 0x7FF829280000 Size: 3022848
GLU32.dll Base Address: 0x7FF80E970000 Size: 126976
UMPDC.dll Base Address: 0x7FF82DB80000 Size: 36864
kernel.appcore.dll Base Address: 0x7FF82DE40000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FF82ED10000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FF828CB0000 Size: 102400
MSASN1.dll Base Address: 0x7FF82E9E0000 Size: 36864
gameoverlayrenderer64.dll Base Address: 0x7FFFCA410000 Size: 996352
inputhost.dll Base Address: 0x7FF8154B0000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FF82B8D0000 Size: 864256
CRYPTBASE.DLL Base Address: 0x7FF82E510000 Size: 12288
windows.storage.dll Base Address: 0x7FF82CC70000 Size: 7041024
wintypes.dll Base Address: 0x7FF82CB30000 Size: 544768
dbghelp.dll Base Address: 0x7FF824FE0000 Size: 1646592
dbgcore.DLL Base Address: 0x7FF81DBE0000 Size: 131072
d3d12.dll Base Address: 0x7FF801300000 Size: 94208
CRYPTSP.dll Base Address: 0x7FF82E520000 Size: 57344
rsaenh.dll Base Address: 0x7FF82DDA0000 Size: 147456
uxtheme.dll Base Address: 0x7FF82C240000 Size: 425984
clbcatq.dll Base Address: 0x7FF82FF70000 Size: 471040
dxdiagn.dll Base Address: 0x7FFFE3670000 Size: 253952
d3d11.dll Base Address: 0x7FF82AE00000 Size: 1867776
DEVOBJ.dll Base Address: 0x7FF82E9B0000 Size: 110592
dxgi.dll Base Address: 0x7FF82C3D0000 Size: 651264
WMICLNT.dll Base Address: 0x7FF829C20000 Size: 32768
wbemprox.dll Base Address: 0x7FF824E90000 Size: 28672
wbemcomn.dll Base Address: 0x7FF81C1F0000 Size: 311296
imagehlp.dll Base Address: 0x7FF8310F0000 Size: 49152
wbemsvc.dll Base Address: 0x7FF824550000 Size: 8192
fastprox.dll Base Address: 0x7FF824570000 Size: 708608
amsi.dll Base Address: 0x7FF823D60000 Size: 57344
USERENV.dll Base Address: 0x7FF82E3B0000 Size: 102400
profapi.dll Base Address: 0x7FF82EC40000 Size: 90112
aswAMSI.dll Base Address: 0x7FF823C70000 Size: 550912
gpapi.dll Base Address: 0x7FF82E350000 Size: 77824
directxdatabasehelper.dll Base Address: 0x7FF828B80000 Size: 196608
cryptnet.dll Base Address: 0x7FF825D80000 Size: 139264
WINNSI.DLL Base Address: 0x7FF82C2F0000 Size: 16384
NSI.dll Base Address: 0x7FF830C50000 Size: 8192
steam_api64.dll Base Address: 0x6C170000 Size: 110592
steamclient64.dll Base Address: 0x7FFFBE300000 Size: 16407552
tier0_s64.dll Base Address: 0x7FFFCA270000 Size: 253952
vstdlib_s64.dll Base Address: 0x7FFFE3AB0000 Size: 284160
Secur32.dll Base Address: 0x7FF82DC10000 Size: 12288
MSWSOCK.dll Base Address: 0x7FF82E2C0000 Size: 331776
SSPICLI.DLL Base Address: 0x7FF82E0A0000 Size: 155648
nvapi64.dll Base Address: 0x7FF81C900000 Size: 5629440
drvstore.dll Base Address: 0x7FF825C20000 Size: 1044480
wldp.dll Base Address: 0x7FF82E5C0000 Size: 188416
D3D10_1.DLL Base Address: 0x7FFFF6300000 Size: 147456
d3d10_1core.dll Base Address: 0x7FF829F30000 Size: 12288
nvspcap64.dll Base Address: 0x7FFFC9F90000 Size: 2056192
ntmarta.dll Base Address: 0x7FF82DE60000 Size: 147456
MSCTF.dll Base Address: 0x7FF82F720000 Size: 1085440
textinputframework.dll Base Address: 0x7FF816770000 Size: 1015808
CoreUIComponents.dll Base Address: 0x7FF8283E0000 Size: 2039296
WINSTA.dll Base Address: 0x7FF82D7C0000 Size: 229376
nvldumdx.dll Base Address: 0x7FF824F20000 Size: 599040
nvgpucomp64.dll Base Address: 0x7FF81FD90000 Size: 29256704
NvMessageBus.dll Base Address: 0x7FF824900000 Size: 2750976
nvwgf2umx.dll Base Address: 0x7FF818120000 Size: 20630016
HID.DLL Base Address: 0x7FF82D570000 Size: 24576
MMDevApi.dll Base Address: 0x7FF81C860000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFFCCC30000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FF81ED80000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FF82C820000 Size: 36864
Windows.UI.dll Base Address: 0x7FF812750000 Size: 966656
avrt.dll Base Address: 0x7FF829000000 Size: 8192
DiscordHook64.dll Base Address: 0x7FFFC52E0000 Size: 793600
D3DCompiler_47.dll Base Address: 0x7FF82A5F0000 Size: 3043328
napinsp.dll Base Address: 0x7FFFF4530000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFFF4510000 Size: 69632
DNSAPI.dll Base Address: 0x7FF82D8B0000 Size: 737280
winrnr.dll Base Address: 0x7FFFF44F0000 Size: 32768
wshbth.dll Base Address: 0x7FF812B80000 Size: 45056
nlansp_c.dll Base Address: 0x7FFFF44C0000 Size: 81920
fwpuclnt.dll Base Address: 0x7FF8282D0000 Size: 294912
rasadhlp.dll Base Address: 0x7FF81E7A0000 Size: 8192
socialclub.dll Base Address: 0x7FFFC9A60000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFFCDBC0000 Size: 901120
libcef.dll Base Address: 0x7FFF90C00000 Size: 151009280
COMDLG32.dll Base Address: 0x7FF8300D0000 Size: 778240
COMCTL32.dll Base Address: 0x7FF823460000 Size: 573440
OLEACC.dll Base Address: 0x7FF823520000 Size: 274432
UIAutomationCore.DLL Base Address: 0x7FFFF8500000 Size: 3063808
NETAPI32.dll Base Address: 0x7FF822C90000 Size: 49152
WINHTTP.dll Base Address: 0x7FF828CF0000 Size: 987136
DWrite.dll Base Address: 0x7FF82AB80000 Size: 1654784
WINSPOOL.DRV Base Address: 0x7FF823590000 Size: 405504
ncrypt.dll Base Address: 0x7FF82E6B0000 Size: 114688
USP10.dll Base Address: 0x7FF82BFD0000 Size: 4096
urlmon.dll Base Address: 0x7FF81FBA0000 Size: 1298432
dxva2.dll Base Address: 0x7FFFE5110000 Size: 102400
wevtapi.dll Base Address: 0x7FF828A50000 Size: 245760
credui.dll Base Address: 0x7FF82BFB0000 Size: 65536
CRYPTUI.dll Base Address: 0x7FF800AB0000 Size: 278528
dhcpcsvc.DLL Base Address: 0x7FF828BD0000 Size: 69632
ESENT.dll Base Address: 0x7FF80BBA0000 Size: 3145728
iertutil.dll Base Address: 0x7FF81F8E0000 Size: 557056
netutils.dll Base Address: 0x7FF82D830000 Size: 20480
srvcli.dll Base Address: 0x7FF822DC0000 Size: 57344
DSROLE.DLL Base Address: 0x7FF82DA70000 Size: 8192
WKSCLI.DLL Base Address: 0x7FF828A30000 Size: 49152
SAMCLI.DLL Base Address: 0x7FF8248E0000 Size: 61440
NTASN1.dll Base Address: 0x7FF82E670000 Size: 69632
FirewallAPI.dll Base Address: 0x7FF82D6E0000 Size: 385024
fwbase.dll Base Address: 0x7FF82D660000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FF815130000 Size: 245760
wdmaud.drv Base Address: 0x7FF8232B0000 Size: 200704
ksuser.dll Base Address: 0x7FF82AA20000 Size: 8192
msacm32.drv Base Address: 0x7FF82AA10000 Size: 20480
MSACM32.dll Base Address: 0x7FF823290000 Size: 77824
midimap.dll Base Address: 0x7FF82AA00000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FF807E40000 Size: 45056
dhcpcsvc6.DLL Base Address: 0x7FF828BF0000 Size: 28672
MSVCP140.dll Base Address: 0x7FF8036A0000 Size: 345600
VCRUNTIME140_1.dll Base Address: 0x7FF803690000 Size: 15360
VCRUNTIME140.dll Base Address: 0x7FF803750000 Size: 65024
schannel.DLL Base Address: 0x7FF82DC90000 Size: 536576
ncryptsslp.dll Base Address: 0x7FF822D50000 Size: 86016
YimMenu.dll Base Address: 0x7FFFC0440000 Size: 7953920
MSVCP140_2.dll Base Address: 0x7FFFD22D0000 Size: 197632
winbrand.dll Base Address: 0x7FF822D80000 Size: 180224
xinput1_4.dll Base Address: 0x7FF81E5B0000 Size: 32768
Dumping registers:
RAX: 0x7FFFC9D69501
RCX: 0x298BDD110E0
RDX: 0x298BDD11760
RBX: 0x298BDD11730
RSI: 0x298BDD11738
RDI: 0x298BDD11760
RSP: 0xA5BF1895B0
RBP: 0xA5BF1896F0
R8:  0x72
R9:  0x72
R10: 0x7FFFC9D6C111
R11: 0x298BDD11761
R12: 0x1
R13: 0x3E
R14: 0x1FD
R15: 0x1E2
Dumping stacktrace:
[0]	socialclub.dll+0x1EABC0 0x7FFFC9C4ABC0
[1]	socialclub.dll+0x203084 0x7FFFC9C63084
[2]	socialclub.dll+0x1A6D35 0x7FFFC9C06D35
[3]	socialclub.dll+0x1E2A08 0x7FFFC9C42A08
[4]	socialclub.dll+0x1C7DC6 0x7FFFC9C27DC6
[5]	socialclub.dll+0x1C7CFF 0x7FFFC9C27CFF
[6]	socialclub.dll+0x1CACBB 0x7FFFC9C2ACBB
[7]	socialclub.dll+0x159C1B 0x7FFFC9BB9C1B
[8]	GTA5.exe+0x148C233 0x7FF65CCFC233
[9]	GTA5.exe+0x1493741 0x7FF65CD03741
[10]	GTA5.exe+0x10C6A26 0x7FF65C936A26
[11]	GTA5.exe+0x10C7522 0x7FF65C937522
[12]	GTA5.exe+0x162FA85 0x7FF65CE9FA85
[13]	GTA5.exe+0x162F2B7 0x7FF65CE9F2B7
[14]	GTA5.exe+0x27B6E 0x7FF65B897B6E
[15]	GTA5.exe+0x21283 0x7FF65B891283
[16]	GTA5.exe+0x162EEC0 0x7FF65CE9EEC0
[17]	GTA5.exe+0x1494 0x7FF65B871494
[18]	GTA5.exe+0x130538F 0x7FF65CB7538F
[19]	GTA5.exe+0x1821344 0x7FF65D091344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by maybegreat48**
This should cause the cache to regenerate. Untested

Fixes #2830

### CODE REVIEW

**Comment by gir489returns** [comment]
Why don't we just read the version number from the PE header and use that to see if it's time to dump the offsets again?

**Comment by maybegreat48** [comment]
> Why don't we just read the version number from the PE header and use that to see if it's time to dump the offsets again?

We already use the code size as a version identifier, but it seemingly did not work in this case

**Comment by gir489returns** [comment]
> > Why don't we just read the version number from the PE header and use that to see if it's time to dump the offsets again?
> 
> We already use the code size as a version identifier, but it seemingly did not work in this case

That doesn't make sense since SizeOfCode did change.

image

Our code is clearly not working properly.

**Comment by maybegreat48** [comment]
It has always worked since we see pattern breakages whenever the SC DLL updates. So this is a very special case or is caused by something else

**Comment by gir489returns** [comment]
> It has always worked since we see pattern breakages whenever the SC DLL updates. So this is a very special case or is caused by something else

Just claiming it's worked before and hasn't now and will only be a onetime thing is not an argument. It should be properly addressed so this doesn't happen again. I think switching out SizeOfCode for TimeDateStamp is a better solution.

**Comment by Yimura** [comment]
Superseded by #2832

**Pull request closed without merging**
