### PR TITLE
Fix script host kick

### PR DESCRIPTION
**Pull request by Mr-X-GTA**

### CODE REVIEW

**Comment by snowleopardd** [comment]
closes again https://github.com/YimMenu/YimMenu/issues/3315

**Comment by Rxann** [comment]
> closes again https://github.com/YimMenu/YimMenu/issues/3315

It's already closed

**Comment by snowleopardd** [comment]
> > closes again #3315
> 
> It's already closed

**again**

**Comment by gir489returns** [comment]
The guy who updated the globals did it by hand, when we have an automatic globals finder via MBG's signatures. I found one of the ones he updates was completely wrong and caused the garage feature to not work and cost me over half an hour in debug time to figure it out and fix it. In the future, we will not be accepting PRs from him and will do the updating ourselves, or at least from people we trust on the project.

**Review by gir489returns — APPROVED** [review]

**Review by Yimura — APPROVED** [review]

**Pull request merged**
