### PR TITLE
REDO: Add Protection GUI Element for Give Collectible 

### PR DESCRIPTION
**Pull request by rkwapisz**
Previously closed PRs were a result of me deleting the branches after I'd merged them into my own fork, but I didn't realize that would also close the PR in the base. Whoops.

### CODE REVIEW

**Review by gir489returns — COMMENTED** [review]
Is there any particular reason you reordered these?

**Comment by rkwapisz** [comment]
> Is there any particular reason you reordered these?

Aesthetics. The features are currently laid out in columns with six elements per group.

Adding this new toggle would have either required a single column of seven, or a new column of one. I decided that instead of making the menu wider, that it would be better visually to reorganize the checkboxes into groups of seven.

I am happy to defer to other preferences, though.

**Comment by gir489returns** [comment]
While the YImMenu project is a hodgepodge of several people's work all slammed together with no regard for UX at all, we generally what to adhere to WYSIWYG design philosophy when we can, because that's generally what ImGui is based upon, or at least tries to.

That being said, if you wish to pitch a new design, it's generally a nice idea to post a screenshot of your new design, so that we can internally weigh the options of accepting the new design, or asking to revert.

**Comment by rkwapisz** [comment]
Here is a screenshot of the proposed new Protection layout with the new Give Collectible checkbox.

image

**Review by gir489returns — APPROVED** [review]

**Comment by gir489returns** [comment]
The new design logically makes sense, I can see why you made those changes.

**Pull request merged**
