### PR TITLE
Fixed RAP signature.

### PR DESCRIPTION
**Pull request by gir489returns**
Closes https://github.com/YimMenu/YimMenu/issues/2546

### CODE REVIEW

**Comment by Rxann** [comment]
your branch title may be the corniest shit i've fucking seen all week

**Comment by gir489returns** [comment]
> your branch title may be the corniest shit i've fucking seen all week

Tell me what you think about this one?: https://github.com/YimMenu/YimMenu/pull/2511

**Comment by Rxann** [comment]
> > your branch title may be the corniest shit i've fucking seen all week
> 
> 
> 
> Tell me what you think about this one?: https://github.com/YimMenu/YimMenu/pull/2511

that shit is horrid aswell.you have to be age 30+ w this dumb shit

**Comment by gir489returns** [comment]
> > > your branch title may be the corniest shit i've fucking seen all week
> > 
> > 
> > Tell me what you think about this one?: #2511
> 
> that shit is horrid aswell.you have to be age 30+ w this dumb shit

That's funny coming from the guy who made this horrid POS PR https://github.com/YimMenu/YimMenu/pull/1782

**Comment by Rxann** [comment]
> > > > your branch title may be the corniest shit i've fucking seen all week
> 
> > > 
> 
> > > 
> 
> > > Tell me what you think about this one?: #2511
> 
> > 
> 
> > that shit is horrid aswell.you have to be age 30+ w this dumb shit
> 
> 
> 
> That's funny coming from the guy who made this horrid POS PR https://github.com/YimMenu/YimMenu/pull/1782

it's only horrid bc ur dumbass thinks everything needs to be a fucking lua script when there is no developed way to share to get lua scripts easily. also don't u have a job to be doing instead of coding all day? or are you just a degenerate relying on social security?

**Comment by gir489returns** [comment]
> > > > > your branch title may be the corniest shit i've fucking seen all week
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Tell me what you think about this one?: #2511
> > 
> > 
> > > 
> > 
> > 
> > > that shit is horrid aswell.you have to be age 30+ w this dumb shit
> > 
> > 
> > That's funny coming from the guy who made this horrid POS PR #1782
> 
> it's only horrid bc ur dumbass thinks everything needs to be a fucking lua script when there is no developed way to share to get lua scripts easily. also don't u have a job to be doing instead of coding all day? or are you just a degenerate relying on social security?

> image

**Comment by Rxann** [comment]
> > > > > > your branch title may be the corniest shit i've fucking seen all week
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Tell me what you think about this one?: #2511
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > that shit is horrid aswell.you have to be age 30+ w this dumb shit
> 
> > > 
> 
> > > 
> 
> > > That's funny coming from the guy who made this horrid POS PR #1782
> 
> > 
> 
> > it's only horrid bc ur dumbass thinks everything needs to be a fucking lua script when there is no developed way to share to get lua scripts easily. also don't u have a job to be doing instead of coding all day? or are you just a degenerate relying on social security?
> 
> 
> 
> > image
> 
> 

no response that's what i thought

**Comment by gir489returns** [comment]
> > > > > > > your branch title may be the corniest shit i've fucking seen all week
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > Tell me what you think about this one?: #2511
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > that shit is horrid aswell.you have to be age 30+ w this dumb shit
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > That's funny coming from the guy who made this horrid POS PR #1782
> > 
> > 
> > > 
> > 
> > 
> > > it's only horrid bc ur dumbass thinks everything needs to be a fucking lua script when there is no developed way to share to get lua scripts easily. also don't u have a job to be doing instead of coding all day? or are you just a degenerate relying on social security?
> > 
> > 
> > > image
> 
> no response that's what i thought

The response was that you're huffing copium, but your 2 IQ brain can't comprehend it, so you take that as a win. Lmao, the absolute COPE.

**Comment by Yimura** [comment]
Bruh

**Pull request merged**
