### PR TITLE
feat(Toxic): Added some minor stuff

### PR DESCRIPTION
**Pull request by BugisoftRSG**
idk what it can all crash from testing 2T1

### CODE REVIEW

**Review by Yimura — COMMENTED** [review]
Are we sure we want to go this way, I'm all for exposing terrible stuff but making it accessible in such a way seems very toxic.

**Comment by tupoy-ya** [comment]
Well if you are doing a custom build then you can implement it yourself anyway as it is public.

**Comment by BugisoftRSG** [comment]
> Well if you are doing a custom build then you can implement it yourself anyway as it is public.

Its because of some rules

**Comment by Yimura** [comment]
I want to be clear though I was not aware of this coming to YimMenu, @BugisoftRSG decided to make a PR with a crash in it.
Neither is there a protection for this crash available publicly.

**Comment by ghost** [comment]
I sent this crash to @maybegreat48 today and a protection for it should be public soon.

my 2 cents:

Let's not forget however that rockstar can see this github just like anyone else. If serious toxic stuff is added and maintained in the menu such as crashes the likely outcome is YimMenu getting constantly targeted with detections until it is rendered unusable.

It's good to keep a (sort-of) encyclopedia of all the known crashes, it's bad to add them to the public build, even if guarded behind the doors of a simple #ifdef. Some people genuinely enjoy YimMenu and the protection it gives them, let's not ruin that.

I think we should make a discussion channel where we can post all known crashes, so we can test them and post patches of sorts, right now all the research in crashes is just conducted by a few individuals and bits of information are all over the place. A public discussion for this would help.

**Comment by Yimura** [comment]
Yes I'm all for making them public in a discussion, I've don't want to post the protection for it here yet to prevent mass skidding. (more to prevent the crash + the protection from being public)

**Comment by MarkEcza** [comment]
> I sent this crash to @maybegreat48 today and a protection for it should be public soon.
> 
> 
> 
> my 2 cents:
> 
> 
> 
> Let's not forget however that rockstar can see this github just like anyone else. If serious toxic stuff is added and maintained in the menu such as crashes the likely outcome is YimMenu getting constantly targeted with detections until it is rendered unusable.
> 
> 
> 
> It's good to keep a (sort-of) encyclopedia of all the known crashes, it's bad to add them to the public build, even if guarded behind the doors of a simple #ifdef. Some people genuinely enjoy YimMenu and the protection it gives them, let's not ruin that.
> 
> 
> 
> I think we should make a discussion channel where we can post all known crashes, so we can test them and post patches of sorts, right now all the research in crashes is just conducted by a few individuals and bits of information are all over the place. A public discussion for this would help.

Lets not ruin the fun yet. Shall we? As of the case of protections ;)

**Comment by maybegreat48** [comment]
```c++
if (msgType == rage::eNetMessage::MsgBlacklist && frame->m_connection_identifier != gta_util::get_network()->m_game_session.m_connection_identifier)
		{
			if (player)
			{
				g_notification_service->push_error("Protections", std::format("Blocked invalid blacklist crash from {}", player->get_name()));
			}
			else
			{
				g_notification_service->push_error("Protections", "Blocked invalid blacklist remote crash");
			}
			return true;
		}
```
This is literally the invalid transition crash except it's a blacklist msg instead

**Comment by ghost** [comment]
10/10 brother keep america great 👍 i will be putting this into my stand source i got from sainan (had to do a lil favor)
jokes aside i seriously doubt crashes, kicks or anything besides recovery will get yimmenu targeted. it's obviously the only thing they've cared about for years, if it's for morality; you can't change an game's environment when cheat's are so widespread for this game. not everyone will play nice.

**Comment by ghost** [comment]
> Are we sure we want to go this way, I'm all for exposing terrible stuff but making it accessible in such a way seems very toxic.

I know you hate when I respond to you, but stop being so indecisive about the direction of this software. A few months ago, you didn't even want remote kill. Go big or go home. What is Rockstar going to do? Get mad at YOU because they made a dogshit game?

**Comment by Yimura** [comment]
> I know you hate when I respond to you, but stop being so indecisive about the direction of this software. A few months ago, you didn't even want remote kill. Go big or go home. What is Rockstar going to do? Get mad at YOU because they made a dogshit game?

In regards to me not liking you is because of the way you behave yourself and the way you answer.
Anyways crashes have always been a no even back when there were some mild toxic things in YimMenu.

**Comment by ghost** [comment]
> > Are we sure we want to go this way, I'm all for exposing terrible stuff but making it accessible in such a way seems very toxic.
> 
> 
> 
> I know you hate when I respond to you, but stop being so indecisive about the direction of this software. A few months ago, you didn't even want remote kill. Go big or go home. What is Rockstar going to do? Get mad at YOU because they made a dogshit game?

Rockstar has every right to stop any cheat. It's obviously against their terms of service. When a cheat becomes powerful (recovery, crashes) you may start to become a prime target.

**Pull request closed without merging**
