### PR TITLE
Add Admin Appendage

### PR DESCRIPTION
**Pull request by Rxann**

### CODE REVIEW

**Comment by gir489returns** [comment]
Is Admin can be spoofed, saying they're a Rockstar admin is most likely a lie and highly unlikely. That flag is borderline useless.

**Comment by rkwapisz** [comment]
If we don't already infract users with R* admin tags as modders then I think that would be more useful.

**Comment by Rxann** [comment]
> If we don't already infract users with R* admin tags as modders then I think that would be more useful.

What if they are R* admins though.

**Comment by gir489returns** [comment]
> > If we don't already infract users with R* admin tags as modders then I think that would be more useful.
> 
> What if they are R* admins though.

What if I'm a Rockstar admin? Not an argument.

**Comment by rkwapisz** [comment]
> > If we don't already infract users with R* admin tags as modders then I think that would be more useful.
> 
> What if they are R* admins though.

Good question. If we can't tell real admins apart from fake ones then what do we do with the information?

**Comment by Rxann** [comment]
> > > If we don't already infract users with R* admin tags as modders then I think that would be more useful.
> > 
> > 
> > What if they are R* admins though.
> 
> Good question. If we can't tell real admins apart from fake ones then what do we do with the information?

I will be closing this in favor of implementing a check in looped_modder_detection once #3094 is mereged to see if the player with the r* clan logo has the rid in the admin list that I will create. I will close this PR in about 12 hours to see if anyone has any opinions on this.

**Comment by rkwapisz** [comment]
> the rid in the admin list that I will create

Eagerly waiting to see how effective this is.

**Comment by Rxann** [comment]
> > the rid in the admin list that I will create
> 
> Eagerly waiting to see how effective this is.

Yes, I am struggling to figure out a way to get the clan data of a player.

**Pull request closed without merging**
