### PR TITLE
feat(Outfit Editor): Added [+] & [-] buttons for easier navigation

### PR DESCRIPTION
**Pull request by Democles85**
Added the [+] and [-] button for easier navigation based on a request. Sure, adding the step value and changing the formatting to display the current ID is easier, but I wanted to keep the input field as well. Hope it's good :)

Screenshot

### CODE REVIEW

**Comment by xiaoxiao921** [comment]
you could make function for code reuse instead of copy pasting the same things 4 times but otherwise looks fine

ALSO:

IsItemClicked is not needed as you can just write 

if (imgui:button)
{
  // clicked!
}

**Comment by Democles85** [comment]
> you could make function for code reuse instead of copy pasting the same things 4 times but otherwise looks fine
> 
> ALSO:
> 
> IsItemClicked is not needed as you can just write
> 
> if (imgui:button) { // clicked! }

For the `if(ImGui::Button("+") {}` I tried doing it, and it wasn't working for some reason, the values were not updating. That's why I did the IsItemClicked(), and ofc I shall work on creating a function for the buttons.

**Comment by tupoy-ya** [comment]
I don't understand `ImGui::InputInt` already has all the functionality for this it's just disabled with the last parameter being set to zero so either set it to 1 or remove it all together and ImGui will add the buttons for you.
```cpp
ImGui::SetNextItemWidth(100);
if (ImGui::InputInt(std::format("{} [0,{}]", item.label, item.drawable_id_max).c_str(), &item.drawable_id))
```

You will need to adjust the `ImGui::SetNextItemWidth` for it tool have more space.

image

### Add ImGui demo to the debug menu.
It's the second time today that someone is reinventing existing functionality.

### Edit
Ok now i realized that you cannot edit the value like this.
It works in the demo, so i thought it would work here as well.

**Comment by tupoy-ya** [comment]
Checked the code and found the reason why we can't edit some of the fields.
The problem is that some `ImGui::InputInt`s have the same name.
We can fix this by adding `##{column_number}` after the text so ImGui can distinguish them.
Example: 
```cpp
ImGui::BeginGroup();
for (auto& item : components.items)
{
	ImGui::SetNextItemWidth(110);
	if (ImGui::InputInt(std::format("{} [0,{}]##1", item.label, item.drawable_id_max).c_str(), &item.drawable_id))
	{
		g_fiber_pool->queue_job([item] {
			PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, 0, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
		});
	}
}
ImGui::EndGroup();

ImGui::SameLine();

ImGui::BeginGroup();
for (auto& item : components.items)
{
	ImGui::SetNextItemWidth(110);
	if (ImGui::InputInt(std::format("{} {} [0,{}]##2", item.label, "TEX", item.texture_id_max).c_str(), &item.texture_id))
	{
		g_fiber_pool->queue_job([item] {
			PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, item.texture_id, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
		});
	}
}
ImGui::EndGroup();
```
image

**Comment by Democles85** [comment]
> Checked the code and found the reason why we can't edit some of the fields. The problem is that some `ImGui::InputInt`s have the same name. We can fix this by adding `##{column_number}` after the text so ImGui can distinguish them. Example:
> 
> ```c++
> ImGui::BeginGroup();
> for (auto& item : components.items)
> {
> 	ImGui::SetNextItemWidth(110);
> 	if (ImGui::InputInt(std::format("{} [0,{}]##1", item.label, item.drawable_id_max).c_str(), &item.drawable_id))
> 	{
> 		g_fiber_pool->queue_job([item] {
> 			PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, 0, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
> 		});
> 	}
> }
> ImGui::EndGroup();
> 
> ImGui::SameLine();
> 
> ImGui::BeginGroup();
> for (auto& item : components.items)
> {
> 	ImGui::SetNextItemWidth(110);
> 	if (ImGui::InputInt(std::format("{} {} [0,{}]##2", item.label, "TEX", item.texture_id_max).c_str(), &item.texture_id))
> 	{
> 		g_fiber_pool->queue_job([item] {
> 			PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, item.texture_id, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
> 		});
> 	}
> }
> ImGui::EndGroup();
> ```
> 
> image

I tried this before and the input fields and the buttons were overlapping. IDK tbh...

## EDIT
I'll try again, I guess. :d

**Comment by Democles85** [comment]
> Checked the code and found the reason why we can't edit some of the fields. The problem is that some `ImGui::InputInt`s have the same name. We can fix this by adding `##{column_number}` after the text so ImGui can distinguish them. Example:
> 
> ```c++
> ImGui::BeginGroup();
> for (auto& item : components.items)
> {
> 	ImGui::SetNextItemWidth(110);
> 	if (ImGui::InputInt(std::format("{} [0,{}]##1", item.label, item.drawable_id_max).c_str(), &item.drawable_id))
> 	{
> 		g_fiber_pool->queue_job([item] {
> 			PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, 0, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
> 		});
> 	}
> }
> ImGui::EndGroup();
> 
> ImGui::SameLine();
> 
> ImGui::BeginGroup();
> for (auto& item : components.items)
> {
> 	ImGui::SetNextItemWidth(110);
> 	if (ImGui::InputInt(std::format("{} {} [0,{}]##2", item.label, "TEX", item.texture_id_max).c_str(), &item.texture_id))
> 	{
> 		g_fiber_pool->queue_job([item] {
> 			PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, item.texture_id, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
> 		});
> 	}
> }
> ImGui::EndGroup();
> ```
> 
> image

So I have the same code as you:
```c++
ImGui::BeginGroup();
		for (auto& item : components.items)
		{
			ImGui::SetNextItemWidth(110);
			if (ImGui::InputInt(std::format("{} [0,{}]##1", item.label, item.drawable_id_max).c_str(), &item.drawable_id))
			{
				g_fiber_pool->queue_job([item] {
					PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, 0, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
				});
			}
		}
		ImGui::EndGroup();

		ImGui::SameLine();

		ImGui::BeginGroup();
		for (auto& item : components.items)
		{
			ImGui::SetNextItemWidth(110);
			if (ImGui::InputInt(std::format("{} {} [0,{}]##2", item.label, "OUTFIT_TEX"_T, item.texture_id_max).c_str(), &item.texture_id))
			{
				g_fiber_pool->queue_job([item] {
					PED::SET_PED_COMPONENT_VARIATION(self::ped, item.id, item.drawable_id, item.texture_id, PED::GET_PED_PALETTE_VARIATION(self::ped, item.id));
				});
			}
		}
		ImGui::EndGroup();
```

Screenshot_3

## EDIT
Could be my pea sized brain that is tired, or my lack of knowledge in C++ and YimMenu, but I am trying to learn. :D

**Pull request closed without merging**
