### PR TITLE
feat(Hotkeys) Added Hotkey support

### PR DESCRIPTION
**Pull request by MoneyDropLobby**

### CODE REVIEW

**Comment by mentolixite** [comment]
#223

**Comment by MoneyDropLobby** [comment]
> #223

Idk but I think my implementation is better? I just don't know why CI gets an error and ok my local PC it can compile...

**Comment by Yimura** [comment]
We have warnings set as errors, so any warning you ignored will become an error and fail the build.

**Comment by MoneyDropLobby** [comment]
I don't know how to fix this...

**Comment by Yimura** [comment]
I'll take a look at it later

**Comment by xM4ddy** [comment]
PR closed reasoning can be found here. https://www.unknowncheats.me/forum/grand-theft-auto-v/476972-yimmenu-1-59-a-9.html#post3402800

**Pull request closed without merging**
