### PR TITLE
Update to 1.67

### LINKED ISSUE #1406: [Bug]: Upgrade to 1.67
### Describe the bug

Must be updated online to 1.67 and build to 2944

### Steps To Reproduce

...

### Expected Behavior

.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by maybegreat48**
Fixes #1406

### CODE REVIEW

**Comment by Tayipc38** [comment]
Bro how

**Comment by Sys0xdbg** [comment]
Maybegreat is just great

**Comment by navmodder** [comment]
Maybegreat is just great

**Comment by Daitaku17** [comment]
Great job, now its just a matter of time.

**Comment by BigboiKilljoy** [comment]
Nice job hacker man

**Comment by rrAsus** [comment]
God's Work

**Comment by KnollenRick** [comment]
Download the artifacts for this pull request:

* [binary.zip](https://nightly.link/YimMenu/YimMenu/actions/artifacts/750509430.zip)

**Comment by Yimura** [comment]
> Niice! The Mute Siren Option!! 😄
> 
> But GTA is crashing after a few minutes using the mod menu.
> 
> Need a log file?

No please refrain from communicating only the absolute necessary, we're aware that the mod menu isn't usable currently and that's why it hasn't been merged.
Also keep in mind that we don't know if Rockstar added any anti-cheat checks against YimMenu in this update so any usage of YimMenu is at your own risk.

**Comment by KnollenRick** [comment]
> No please refrain from communicating only the absolute necessary, we're aware that the mod menu isn't usable currently and that's why it hasn't been merged.
> Also keep in mind that we don't know if Rockstar added any anti-cheat checks against YimMenu in this update so any usage of YimMenu is at your own risk.

Okay.

**Comment by BUZZARDGTA** [comment]
> "Also keep in mind that we don't know if Rockstar added any anti-cheat checks against YimMenu in this update so any usage of YimMenu is at your own risk."

Well my account got banned like a couple hours after I tried to inject [YimMenu](https://github.com/YimMenu/YimMenu/actions/runs/5230388579) around 4 times yesterday.
I forgot there was 1.67 out and that was the reason I shouldn't inject.
Anyways I didn't tried any others cheats and I played normal, but then got banned (1 month + char deletion).
I don't actually know if this is the reason I got banned or not.

**Comment by CypherMorgan** [comment]
> > "Also keep in mind that we don't know if Rockstar added any anti-cheat checks against YimMenu in this update so any usage of YimMenu is at your own risk."
> 
> Well my account got banned like a couple hours after I tried to inject [YimMenu](https://github.com/YimMenu/YimMenu/actions/runs/5230388579) around 4 times yesterday. I forgot there was 1.67 out and that was the reason I shouldn't inject. Anyways I didn't tried any others cheats and I played normal, but then got banned (1 month + char deletion). I don't actually know if this is the reason I got banned or not.

If you tried injecting in Online then maybe it triggered anti-cheat cuz it's outdated.. Not sure tho.

**Comment by ghost** [comment]
@maybegreat48 Why did you remove the NTQVM caller? I've checked in IDA and the function appears to have stayed the same.

**Comment by Yimura** [comment]
> Well my account got banned like a couple hours after I tried to inject [YimMenu](https://github.com/YimMenu/YimMenu/actions/runs/5230388579) around 4 times yesterday. I forgot there was 1.67 out and that was the reason I shouldn't inject. Anyways I didn't tried any others cheats and I played normal, but then got banned (1 month + char deletion). I don't actually know if this is the reason I got banned or not.

@Illegal-Services, could you make a discussion explaining what exactly you used in YimMenu before the ban?
Like stat modifications or anything else that might come to mind?

**Comment by LexyDrow44WasTaken** [comment]
> > "Also keep in mind that we don't know if Rockstar added any anti-cheat checks against YimMenu in this update so any usage of YimMenu is at your own risk."
> 
> Well my account got banned like a couple hours after I tried to inject [YimMenu](https://github.com/YimMenu/YimMenu/actions/runs/5230388579) around 4 times yesterday. I forgot there was 1.67 out and that was the reason I shouldn't inject. Anyways I didn't tried any others cheats and I played normal, but then got banned (1 month + char deletion). I don't actually know if this is the reason I got banned or not.

i didn't, it just crashed my game for me

**Comment by maybegreat48** [comment]
I get force-crashed with the NTQVM hook enabled. The new queue dependency hook should prevent most anticheat functions, including the one that reports you, from being called. I'm currently reversing stuff to see if they've added anything new

**Comment by BUZZARDGTA** [comment]
> @Illegal-Services, could you make a discussion explaining what exactly you used in YimMenu before the ban?
> Like stat modifications or anything else that might come to mind?

@Yimura I where not using YimMenu's stat editor, to make money I where essentially doing heists (cayo and diamond, as well as selling businesses). I where playing a lot (~15H/d) so probably making around 20M everydays, easily...
Since I got banned a week ago (I believe either due to heist editor, or an asshole modder reporting me to R*) this was a very new account, and I've use a recovery from wasabi-unlocker-stat-editor.dll. I didn't got banned since I done that for idk me 4-7 days, and yeah then yesterday I do think I've injected online, maybe even twice. Then maybe twice again in story mode. I where so dumb I completely forgot that there was a new update of the game today and it didn't even download it as well... Anyways, since Rockstar don't give the reason of the bann it's complicated to know the reason...

Edit: Yeah when I injected yesterday in 1.67 it did crash my game every single time i tried.

**Comment by inthecatsdreams** [comment]
Do you need testers before merging? If so I don't mind, I'm off work for a while and I have a few spare accounts so let me know, would be happy to help.

**Comment by maybegreat48** [comment]
Sure, thanks. Try everything and report anything that doesn't work or crashes your game

**Comment by D-Borkan** [comment]
some feautres remove from same paid menus in 1.67
this may help for some reason

- stand
    • Removed breakup, ban, & confusion kicks
    • Removed host kick karma
    • Removed breakup kick reactions
    • Removed lessen breakup kicks as host
    • Removed player(s) > teleport to cayo perico

- 2take1
   • Removed village people 360 kick
   • Removed drop kick protex

**Comment by Primexz** [comment]
update of [metadata.json](https://github.com/YimMenu/YimMenu/blob/master/metadata.json) is missing in this pr. ;)

**Comment by takoyakiwhite** [comment]
Missing for disable phone globals update to 20483 :)

**Review by Yimura — APPROVED** [review]
Code looks good, some features will obviously not work and we cannot verify if R* has added anything that may cause a detection of YimMenu in this update.

**Pull request merged**
