### PR TITLE
potential fix for some infinite loop train(?) crash

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Need someone to sanity check this
func is located at
`45 32 C0 84 C9 79 03`

the infinite (do while) loop was found with the following callstack:

```
0, GTA5.exe+0xf1f2d6
1, GTA5.exe+0xfafa0a
2, GTA5.exe+0xf901d7
3, GTA5.exe+0x94026c
4, GTA5.exe+0x164c04d
5, GTA5.exe+0x6c4cfd
6, GTA5.exe+0x6d49a0
7, GTA5.exe+0x93309f
8, GTA5.exe+0x94ffad
9, GTA5.exe+0x1606401
10, GTA5.exe+0x1605c37
11, GTA5.exe+0x2765c
12, GTA5.exe+0x20d4b
13, GTA5.exe+0x1605840
14, GTA5.exe+0x1494
15, GTA5.exe+0x12e0267
16, GTA5.exe+0x17f7ea4
17, kernel32.dll!BaseThreadInitThunk+0x1d
18, ntdll.dll!RtlUserThreadStart+0x28
```

### CODE REVIEW

**Review by Yimura — DISMISSED** [review]
Code looks good haven't looked at the function yet.

**Comment by maybegreat48** [comment]
Is `a2` attacker controlled? Could it ever be negative inf or a really low or high number? `NaN`?

**Comment by xiaoxiao921** [comment]
Sadly I have no idea as I only thought of retrieving the callstack without checking the registers with a debugger, I guess it doesnt hurt also sanity checking the param

Edit: I guess for giving more context it was in a online session while playing with a friend (who had some other menus) and I ended up with an infinite loop while they simply got a notification of a "train crash"

**Comment by TSYiMa** [comment]
Hook `serialize_train_game_state_data_node(CTrainGameStateDataNode* node, rage::CSyncDataBase* data)`  and check `node->m_track_id`

**Comment by xiaoxiao921** [comment]
Closing due to this not being needed anymore due to `can_apply_data` changes that happened recently and also that these hooks are not really a clean way to solve those crashes

**Pull request closed without merging**
