### PR TITLE
Various fixes

### LINKED ISSUE #1864: [Bug]: VERY MINOR - Turn signals doesn't turn off.
### Describe the bug

Using J and L to signal Left and Right work and switch to one another, but you cannot stop the blinking signal.
It also happens with the "fully automated turn signal" option on.

The only way to stop the signal is to trigger the hazard signals, then turn that one off.

### Steps To Reproduce

1. Signal left or right.
2. Tap again to turn the signal off
3. It doesn't turn off.
4. To turn it off, toggle hazards on, then off.

### Expected Behavior

Turn off the signal when tapping the key again.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1925: Colours are not shown right.
### Describe the bug

:Minor: There is a problem with picking a colour in Yimmenu .. in the section Headlight there is 'backlight' instead of "blacklight" .. and in the neon section there is no option to choose "blacklight" at all.. please solve this ... thanks in advance.. 👍

### Steps To Reproduce

Get in a car.
Use LScustom. 
Headlight and Neon section. 
Colours. 

### Expected Behavior

Can you please adjust this.. 😀
Get the spelling right and add Blacklight option to neon. 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1928: [Bug]: Damage Override Bug
### Describe the bug

Even if the damageoverride setting is turned off, the menu still uses the value entered by the user.

### Steps To Reproduce

go to weapons

Turn on the damageoverride setting and enter a high value (it can be a value that destroys pedestrians with one shot)

shoot at pedestrians or vehicles

turn off damageoverride after some use

shoot at pedestrians or vehicles again

### Expected Behavior

Game defaults should work when damageoverride is turned off

### Logs and/or screenshots

https://youtu.be/S8-YNmjuMfY

### Store

Epic Games

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by T14D3**
Closes #1928
Closes #1925
Closes #1864

### CODE REVIEW

**Comment by GTMoraes** [comment]
Cool, I used it on my fork and it fixed the J and L for turn signals. Thanks.

The "Fully Automatic Signals" function is still broken, though. Behaves the same: It activates when turning the signal, but doesn't deactivate.

**Comment by T14D3** [comment]
> The "Fully Automatic Signals" function is still broken, though. Behaves the same: It activates when turning the signal, but doesn't deactivate.

Grrrreat, okay, I'll fiddle around with it a bit more

**Comment by GTMoraes** [comment]
> > The "Fully Automatic Signals" function is still broken, though. Behaves the same: It activates when turning the signal, but doesn't deactivate.
> 
> Grrrreat, okay, I'll fiddle around with it a bit more

Thanks! But like, I'm probably the only one that gives a damn about that, so if you want to skip that altogether, nobody will notice 😂

The other bugs are definitely more relevant.

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
Is this finished?

**Comment by T14D3** [comment]
> Is this finished?

Finished as in everything works and is ready to merge, yes, the turning off of the signal lights is probably gonna take some time and another PR because gta being weird, so yes, finished

**Pull request merged**
