### PR TITLE
Initial battleye bypass

### LINKED ISSUE #3690: [Bug]: BattlEye anti-cheat detection added to GTAOL
### Describe the bug

**BattlEye** anti-cheat detection added to GTAOL,Yimmenu's injections are highly likely to be detected.  
It could be extremely **unsafe** right now.

### Steps To Reproduce

When opening GTA5, BattlEye updates and pops up a MessageBox

### Expected Behavior

Hopefully changes can be made for this update

### Logs

<none>

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by maybegreat48**
Enjoy this while it lasts

Closes #3690 (for now)

Instructions:
* Disable BattlEye through the launcher or use the -nobattleye command-line flag
* Delete your settings file (%APPDATA%\YimMenu\settings.json)
* Inject normally

Credits: @Mr-X-GTA for testing

### CODE REVIEW

**Comment by gir489returns** [comment]
If the SCAPI gives you a BattleEye challenge and you give it no response they can easily figure out who’s not running BE. You have to emit heartbeats regularly on PUBG, I can’t imagine GTA doesn’t have GTA do this.

**Comment by Yimura** [comment]
@maybegreat48 can bump the version number in pointers.cpp?


https://github.com/YimMenu/YimMenu/blob/db36395fe009bb82bf8e7ce34afffdedc84e0f79/src/pointers.cpp#L6

**Review by Yimura — DISMISSED** [review]

**Comment by vuk-beta** [comment]
Is it online enabled aswell?

**Comment by Yimura** [comment]
> Is it online enabled aswell?

Read the provided instructions, limiting conversation in this PR to prevent off-topic talking.

**Review by Yimura — DISMISSED** [review]

**Comment by Yimura** [comment]
Merging after build completes.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
