### PR TITLE
feat(cmake): update ImGui to latest release

### PR DESCRIPTION
**Pull request by Yimura**
Had to fix some stuff and remove a Lua binding that doesn't exist anymore in the latest version of ImGui.

### CODE REVIEW

**Comment by gir489returns** [comment]
Is there a reason we're fast forwarding our version? Did they add/implement/fix something we need?

**Comment by Yimura** [comment]
Tried to fix #2586 but couldn't find a good, non-hacky way of fixing it without handicapping the current behaviour.

Decided since I did the work to fix the issues the new version introduced, I'll open a PR anyway.

**Comment by gir489returns** [comment]
> Tried to fix #2586 but couldn't find a good, non-hacky way of fixing it without handicapping the current behaviour.
> 
> Decided since I did the work to fix the issues the new version introduced, I'll open a PR anyway.

As long as it doesn't break anything, I'm OK with this, but I think we should regression test this before pushing it, they could've changed the way a lot of these behave, I had this happen before with BBv2 when we would constantly keep playing catch up with ImGui. Eventually we just decided to say fuck it and stay on an old version because it was too much work constantly updating and fixing ImGui.

**Comment by Yimura** [comment]
> As long as it doesn't break anything, I'm OK with this, but I think we should regression test this before pushing it, they could've changed the way a lot of these behave, I had this happen before with BBv2 when we would constantly keep playing catch up with ImGui. Eventually we just decided to say fuck it and stay on an old version because it was too much work constantly updating and fixing ImGui.

Yup, I completely agree however previously we didn't stick to actual version numbers and instead were just using the latest commit from their active dev branch it wasn't too good either. At least with this we'll start by using their versioned releases.

**Review by gir489returns — COMMENTED** [review]
Tested last night, no issues detected.

**Pull request merged**
