### PR TITLE
Exception handler toggle

### LINKED ISSUE #1205: [Bug]: looped dumps log log files
### Describe the bug

maybe a way for the menu to clean up the sometimes very large cout.out logs that happen from repeated dumps that dont crash the game i have found some as large as a gig in size most of the time 100 500 megs in size

### Steps To Reproduce

play game people try to crash you but you dont crash and you get repeat after repeat of the same dump info over and over  result in huge log files

### Expected Behavior

idk some sorta way to purge from the menu i do just goto the folder and delete them my self 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by Rxann**
Allow the exception handler to be turned off and on(i think). I have no good way to test this feature, that I know of. closes #1205

### CODE REVIEW

**Comment by Yimura** [comment]
We’re not disabling logs of exceptions. I’d rather have a different solution be found to minimise logging of exceptions, like generating a unique hash for each stack dump and if one has already been logged we don’t log it.

**Comment by Rxann** [comment]
Okay, I have to say it may be a little before I figure out how to implement this.

**Comment by Yimura** [comment]
> Okay, I have to say it may be a little before I figure out how to implement this.

Yeah don't worry I'll probably do it eventually.

**Comment by Rxann** [comment]
> > Okay, I have to say it may be a little before I figure out how to implement this.
> 
> 
> 
> Yeah don't worry I'll probably do it eventually.

Okay, you want me to close this?

**Comment by Yimura** [comment]
> > > Okay, I have to say it may be a little before I figure out how to implement this.
> > 
> > 
> > Yeah don't worry I'll probably do it eventually.
> 
> Okay, you want me to close this?

Yeah sure, there will be no benefit to adding this.

**Comment by Rxann** [comment]
> > > > Okay, I have to say it may be a little before I figure out how to implement this.
> 
> > > 
> 
> > > 
> 
> > > Yeah don't worry I'll probably do it eventually.
> 
> > 
> 
> > Okay, you want me to close this?
> 
> 
> 
> Yeah sure, there will be no benefit to adding this.

Alright thanks for the help & if i find out a solution i will try to work on it

**Pull request closed without merging**
