### PR TITLE
Redesigned the preview system entirely.

### LINKED ISSUE #2675: [Bug]: Vehicle Preview glitches out and actually spawns the vehicles
### Describe the bug

Only / at least at one certain spot on the map the preview glitches out. Instead of seeing the cars nothing shows up. The cars are spawned apparently underneath the map. Only after like 10-20sec suddenly usually dozens of vehicles start showing up. Apparently being teleported to the surface again after they fell into the void beneath the map. The vehicles are spawned as persistent, they will remain there forever. They also are networked.
Closely related to #2077.

### Steps To Reproduce

1. Create a new or join a existing session. (New one seems to be easier to reproduce.)
2. Teleport to the LS Customs south of the airfield at Sandy Shores.
3. Be on the street, face towards LSC. (The rough area should be good enough.)
4. You have to spawn at least a car once. Maybe do this several times.
5. Keep moving the mouse above multiple entries in the vehicle list to trigger a new/different preview.
6. You should now notice that no longer previews appear. Wait up to half a minute or try again after walking some meters and restart at 4.
7. Enjoy the piling up of docens of cars.

### Expected Behavior

No spawned cars. No networking of these cars.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by gir489returns**
Closes #2675.

### CODE REVIEW

**Review by Yimura — DISMISSED** [review]
Looks good, waiting for feedback as I didn't have issues with it in the past.

**Comment by Yimura** [comment]
Tested it and seems to work fine for me.

**Comment by gir489returns** [comment]
> Tested it and seems to work fine for me.

If you ramp up and down on the vehicles list, eventually you've overflow the vehicle pool and #2675 will occur.

**Comment by Yimura** [comment]
image

Yup still had it happen just now, welp.

**Comment by gir489returns** [comment]
image

**Comment by Yimura** [comment]
I guess we'll just have to force some type of timeout before allowing a switch to a different vehicle to prevent this from happening?

**Comment by gir489returns** [comment]
> I guess we'll just have to force some type of timeout before allowing a switch to a different vehicle to prevent this from happening?

I just tried that, but it doesn't matter. It has something to do with how we're spawning the cars, I guess.

**Comment by gir489returns** [comment]
Alright, I think I fixed it... @Yimura please retest if you can.

**Comment by gir489returns** [comment]
This is still broken. For some reason, CREATE_VEHICLE can fail and return 0, but will eventually spawn the car later.

**Comment by GreySideMM** [comment]
That's odd. Does the vehicle pool count increase after that call? That could be a workaround, not the prettiest one tho.

**Comment by gir489returns** [comment]
> That's odd. Does the vehicle pool count increase after that call? That could be a workaround, not the prettiest one tho.

Yes. Seems to have to do with spawning a vehicle, deleting it, then trying to spawn it again. Even if you do 1 or 2, the bug still occurs.

**Comment by gir489returns** [comment]
@GreySideMM I think I have fixed the issue. Please test this when applicable.

**Comment by gir489returns** [comment]
8B 0D ? ? ? ? 39 0D ? ? ? ? 0F 9C C0

This function is a check the game does to see if there's too many mission cars before spawning it. @Yimura Should we call this function and do nothing in the preview to prevent spam, or just hook it and make it return true? It's only called by CREATE_VEHICLE and its only purpose is to make it return 0. It should fail fast after that and do nothing, but it seems it doesn't and still spawns the car later on.

**Comment by Yimura** [comment]
Ahaha, make it make sense Rockstar. Function says no but still spawn a vehicle? Like brutha.

Maybe make it return 0 if the vehicle pool is full?

**Comment by gir489returns** [comment]
> Ahaha, make it make sense Rockstar. Function says no but still spawn a vehicle? Like brutha.
> 
> Maybe make it return 0 if the vehicle pool is full?

My thoughts exactly. Exchange the mission check for vehicle pool check. This will also fix other times when we want to spawn vehicles, but it doesn't even though there's room in the pool.

**Comment by gir489returns** [comment]
@GreySideMM What is the status of your testing of the new change?

**Comment by GreySideMM** [comment]
Sry, currently had not enough time. One good and one bad news: I tested it now for ~10mins with the provided build and was not able to reproduce the bug. While it sometimes did not appear immediately this should be long enough of testing. (I will keep testing it when merged with my build tho.)
However there is now a new but probably small bug: When I spawned a car "inside" that one car is the only one that will be displayed as preview - independent what car I hover. It will always be the last "spawn inside" car. This won't happen when you just spawn the car without spawning inside of it.

One other small bug, unrelated tho: Often a newly spawned car will be directly deleted by the preview system. That has been the case before, too. (Doesn't happen when spawning inside, ofc.)

That has been a lot more work then expected. Thank you already for that!

**Comment by gir489returns** [comment]
@GreySideMM I cannot understand what you are asking, are you using a translator?

**Comment by gir489returns** [comment]
@GreySideMM https://youtu.be/SHI6_OInMyI I can't reproduce whatever it is you're claiming doesn't work. You mentioned before you're using your own code base, test only with the provided builds from the builder bot.

**Comment by GreySideMM** [comment]
No, I'm not. There was no question. But sorry for my sometimes rough English. There was no question. I'll try again..
This bug seems to be fixed now. However there is now a new bug: The preview will only show one and the same car once you spawned one using the option "spawn inside". It will then no longer show the car it is supposed to show.

**Comment by GreySideMM** [comment]
I did use the build from above:

> [14:16:11.6942462][INFO/main.cpp:159] Git Info
> 	Branch:	
> 	Hash:	2b2da1cbf2b60a1cf396fff723ff35ba6a68142d
> 	Date:	Fri Mar 29 19:12:53 2024

It worked correct in the beginning. But after I joined a new session it stopped. The very first car I spawned now was using "spawn inside". 
[Screencast 2024-03-30 15:57:28_export4-2.webm](https://github.com/YimMenu/YimMenu/assets/155721485/67acf3ce-b210-4d4c-a608-34a7e2be99d3)

**Comment by gir489returns** [comment]
> I did use the build from above:
> 
> > [14:16:11.6942462][INFO/main.cpp:159] Git Info
> > Branch:
> > Hash:	[2b2da1c](https://github.com/YimMenu/YimMenu/commit/2b2da1cbf2b60a1cf396fff723ff35ba6a68142d)
> > Date:	Fri Mar 29 19:12:53 2024
> 
> It worked correct in the beginning. But after I joined a new session it stopped. The very first car I spawned now was using "spawn inside". [Screencast 2024-03-30 15:57:28_export4-2.webm](https://github.com/YimMenu/YimMenu/assets/155721485/67acf3ce-b210-4d4c-a608-34a7e2be99d3)

This actually looks like a completely unrelated issue. Because you're trying to spawn Army Trailer which is listed 3 times, ImGui is getting confused as there's multiple entries with the same name. @Yimura Is there code to check for this?

**Comment by gir489returns** [comment]
OK I've been able to reproduce the bug @GreySideMM. Very weird one, I think it has to do with switching between views, but I'll fix it.

**Comment by gir489returns** [comment]
@GreySideMM I think I have fixed it. Please retest once the builder bot finishes.

**Comment by GreySideMM** [comment]
Yes, it works now. Thanks again.

**Comment by gir489returns** [comment]
@Yimura This is now ready for review and merging.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
