### PR TITLE
Disable path traversal for Project File/Folder and added Session Switch command

### LINKED ISSUE #1888: [Improvement]: Add session switcher command to lua
### Which feature

I think it should be a command with a numeric argument like 1 is JOIN_PUBLIC, 2 is NEW_PUBLIC and so on.

### Reason

Such a thing will be much more convenient than using globals, although I did not succeed with them :(

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Yimura**
Probably still need to regenerate the Lua docs for commands.

Closes #1888

### CODE REVIEW

**Comment by gir489returns** [comment]
Why is the CLOSED_FRIENDS scenario labeled NEWFRIENDS?

**Comment by ghost** [comment]
Shouldn't NEWPUB create a solo public session? When I run the `command.call("joinsession", {"NEWPUB"})` command then I get into an open session with other people. Or did I do something wrong?

**Comment by Yimura** [comment]
> Shouldn't NEWPUB create a solo public session? When I run the `command.call("joinsession", {"NEWPUB"})` command then I get into an open session with other people. Or did I do something wrong?

I'll take a look on why it's behaving oddly this evening, I might have missed checking certain edge cases.

**Comment by Yimura** [comment]
@kbabrmover1995 due to limitations in the current command API you need to pass the ID of the join type not the string identifier.

The following code works as intended:
```lua
test_gui = gui.get_tab("GUI_TAB_SETTINGS"):add_tab("Debug Lua")

NEW_PUB = 1

test_gui:add_button("Test Join New Pub", function()
    command.call("joinsession", { NEW_PUB })
end)
```

If you need to know which ID's exist for other session types, these are it:
```cpp
enum class eSessionType
{
	JOIN_PUBLIC, // 0
	NEW_PUBLIC, // 1
	CLOSED_CREW, // 2
	CREW, // 3
	CLOSED_FRIENDS = 6,
	FIND_FRIEND    = 9,
	SOLO, // 10
	INVITE_ONLY, // 11
	JOIN_CREW, // 12
	SC_TV, // 13
	LEAVE_ONLINE = -1
};
```

**Pull request merged**
