### PR TITLE
Update for b3323

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
This makes YimMenu usable in SP.
- Disable BattlEye in the Rockstar Games Launcher.
- If the game crashes on injection, delete `%appdata%/YimMenu/settings.json`.

### CODE REVIEW

**Comment by Yimura** [comment]
We should probably look into disabling online usage of YimMenu in GTA V Online, even though we know as developers that it's stupid to go online right now without a proper bypass we can't be sure that our user base has the proper knowledge and insights to realize this.

**Comment by Mr-X-GTA** [comment]
You cannot go online if BattlEye is disabled and if it's enabled you cannot inject.

**Comment by Yimura** [comment]
> You cannot go online if BattlEye is disabled and if it's enabled you cannot inject.

Yes, that makes complete sense. I was a bit blind sighted by the fixing YimMenu for this update and missed the disabling BE part.

**Review by Yimura — APPROVED** [review]
LGTM, untested as I'm currently still at work.

**Comment by gir489returns** [comment]
> You cannot go online if BattlEye is disabled and if it's enabled you cannot inject.

Could it be as simple as just spoofing that we are running BattleEye, but disabling it?

**Review by gir489returns — APPROVED** [review]

**Pull request merged**
