### PR TITLE
Fix presence data pointer

### PR DESCRIPTION
**Pull request by sch-lda**
Not sure if it's accurate, but it works for me.

### CODE REVIEW

**Comment by Yimura** [comment]
Related #2726

**Comment by xiaoxiao921** [comment]
Checked with old dll too, matches just fine

**Comment by gir489returns** [comment]
This does not seem correct. I came up with 48 8D 05 ? ? ? ? 48 8B F9 48 89 01 48 83 C1 08 E8 ? ? ? ? 33 C0 

Only the D9 became F9.

See notes:

image

**Comment by sch-lda** [comment]
I see. Will close this. Plz make a new PR

**Comment by xiaoxiao921** [comment]
this pr worsk though, idk what @gir489returns is talking about

**Review by xiaoxiao921 — APPROVED** [review]

**Comment by xiaoxiao921** [comment]
I fucked up, sorry

**Pull request closed without merging**
