### PR TITLE
feat: Add menu onboarding to YimMenu

### LINKED ISSUE #2486: [Bug]: Multiple BAD METRIC warnings
### Describe the bug

I see multiple warnings for BAD METRICs in the log, e.g;
`[WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: EARN; DATA: "amt":7000,"char":{"slot":0,"cash":0,"bank":35610385,"evc":35617467,"pvc":0,"pxr":0.00000,"nonce":638373429111341077},"c":[-3118.82715,797.97003,17.98220],"pt":2692509279,"vct":0,"vcp":0,"mid":0,"action":"BOUNTY","cat":"JOBS","ctx":{"A":"UNKNOWN","B":"398`

For this version:
```

[03:00:11.3580590][INFO/main.cpp:105] Git Info
	Branch:	master
	Hash:	062c95b3745ff622b60f4a7bb0c564639b6f2d90-dirty
	Date:	Thu Nov 30 20:47:39 2023
```

### Steps To Reproduce

Not clear what causes the bug.  Seems to appear randomly (?)

### Expected Behavior

Don't expect to see bad metric warnings.

### Logs and/or screenshots

```
[03:00:11.3578353][INFO/main.cpp:104] Yim's Menu Initializing
[03:00:11.3580590][INFO/main.cpp:105] Git Info
	Branch:	master
	Hash:	062c95b3745ff622b60f4a7bb0c564639b6f2d90-dirty
	Date:	Thu Nov 30 20:47:39 2023
[03:00:11.3582123][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[03:00:11.3583685][INFO/main.cpp:108] Thread pool initialized.
[03:00:11.3622460][INFO/main.cpp:111] Settings Loaded.
[03:00:11.3622594][DEBUG/thread_pool.cpp:96] Thread 23568 executing settings.cpp:12
[03:00:11.3633587][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[03:00:11.3633696][INFO/pointers.cpp:1808] Loading pointers instance from cache
[03:00:11.3633706][INFO/pointers.cpp:1817] Pointers cache: Loading 215 fields from the cache
[03:00:11.3633798][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[03:00:11.3636845][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[03:00:11.3636893][INFO/pointers.cpp:1808] Loading pointers instance from cache
[03:00:11.3636905][INFO/pointers.cpp:1817] Pointers cache: Loading 5 fields from the cache
[03:00:11.3637098][INFO/main.cpp:114] Pointers initialized.
[03:00:11.3637208][INFO/main.cpp:121] Disabled anticheat gameskeleton.
[03:00:11.3638923][INFO/main.cpp:124] Byte Patch Manager initialized.
[03:00:11.3651093][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7D8E20000 Size: 66857984
ntdll.dll Base Address: 0x7FFBE5FD0000 Size: 1153536
aswhook.dll Base Address: 0x7FFBB34B0000 Size: 47104
KERNEL32.DLL Base Address: 0x7FFBE5840000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFBE39D0000 Size: 1256448
USER32.dll Base Address: 0x7FFBE4650000 Size: 584704
win32u.dll Base Address: 0x7FFBE39A0000 Size: 42496
GDI32.dll Base Address: 0x7FFBE5790000 Size: 61952
gdi32full.dll Base Address: 0x7FFBE3DD0000 Size: 686592
msvcp_win.dll Base Address: 0x7FFBE3900000 Size: 344064
ucrtbase.dll Base Address: 0x7FFBE3CD0000 Size: 735744
PSAPI.DLL Base Address: 0x7FFBE5C10000 Size: 2048
WS2_32.dll Base Address: 0x7FFBE5680000 Size: 275456
RPCRT4.dll Base Address: 0x7FFBE4030000 Size: 923136
CRYPT32.dll Base Address: 0x7FFBE36B0000 Size: 1094656
WINTRUST.dll Base Address: 0x7FFBE3890000 Size: 292864
msvcrt.dll Base Address: 0x7FFBE5B70000 Size: 477184
IMM32.dll Base Address: 0x7FFBE5C20000 Size: 122368
bcrypt.dll Base Address: 0x7FFBE3860000 Size: 102912
SHLWAPI.dll Base Address: 0x7FFBE57E0000 Size: 182784
VERSION.dll Base Address: 0x7FFBDB310000 Size: 10752
ADVAPI32.dll Base Address: 0x7FFBE59A0000 Size: 428544
DSOUND.dll Base Address: 0x7FFB84570000 Size: 380928
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFB06AB0000 Size: 96256
sechost.dll Base Address: 0x7FFBE5900000 Size: 412672
bink2w64.dll Base Address: 0x7FFBA9070000 Size: 307712
combase.dll Base Address: 0x7FFBE4160000 Size: 2328064
ole32.dll Base Address: 0x7FFBE4520000 Size: 833024
SHELL32.dll Base Address: 0x7FFBE4EC0000 Size: 5804032
WINMM.dll Base Address: 0x7FFBD9D90000 Size: 81408
WININET.dll Base Address: 0x7FFBCB8D0000 Size: 2019840
OLEAUT32.dll Base Address: 0x7FFBE48A0000 Size: 608768
MF.dll Base Address: 0x7FFBB51B0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFBB3770000 Size: 1409024
msdmo.dll Base Address: 0x7FFB49530000 Size: 13312
PROPSYS.dll Base Address: 0x7FFBDEDB0000 Size: 631296
MFReadWrite.dll Base Address: 0x7FFB50360000 Size: 918016
cfgmgr32.dll Base Address: 0x7FFBE3810000 Size: 219136
shcore.dll Base Address: 0x7FFBE5E60000 Size: 476672
WTSAPI32.dll Base Address: 0x7FFBDF040000 Size: 37888
D3DCOMPILER_43.dll Base Address: 0x7FFB4CE80000 Size: 2423296
d3d9.dll Base Address: 0x7FFB87760000 Size: 1371648
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFBD4B30000 Size: 48128
DINPUT8.dll Base Address: 0x7FFBB52F0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
IPHLPAPI.DLL Base Address: 0x7FFBE2AB0000 Size: 166400
SETUPAPI.dll Base Address: 0x7FFBE4A50000 Size: 887808
powrprof.dll Base Address: 0x7FFBE2C20000 Size: 70656
winmmbase.dll Base Address: 0x7FFBBDAE0000 Size: 95232
d3dx9_43.dll Base Address: 0x7FFB5E6B0000 Size: 2280960
kernel.appcore.dll Base Address: 0x7FFBE1550000 Size: 16384
dwmapi.dll Base Address: 0x7FFBE1260000 Size: 98816
windows.storage.dll Base Address: 0x7FFBE1750000 Size: 5841920
OPENGL32.dll Base Address: 0x7FFB623F0000 Size: 909312
MFCORE.DLL Base Address: 0x7FFBB4C90000 Size: 3960320
Wldp.dll Base Address: 0x7FFBE3010000 Size: 93696
GLU32.dll Base Address: 0x7FFBD4A30000 Size: 122880
ksuser.dll Base Address: 0x7FFBB4C30000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFBE2F80000 Size: 10752
UMPDC.dll Base Address: 0x7FFBE2A90000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFBE3EF0000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFBB3670000 Size: 105472
MSASN1.dll Base Address: 0x7FFBE3280000 Size: 34816
gameoverlayrenderer64.dll Base Address: 0x7FFB86490000 Size: 996864
inputhost.dll Base Address: 0x7FFBCA300000 Size: 976384
wintypes.dll Base Address: 0x7FFBDF5A0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFBE0C60000 Size: 606720
CoreUIComponents.dll Base Address: 0x7FFBE0580000 Size: 1795072
ntmarta.dll Base Address: 0x7FFBE27F0000 Size: 140288
sdk_legacy_led_x64.dll Base Address: 0x7FFB065A0000 Size: 3417088
MSVCP140.dll Base Address: 0x7FFBB5CF0000 Size: 345600
VCRUNTIME140.dll Base Address: 0x7FFBB5CD0000 Size: 65024
VCRUNTIME140_1.dll Base Address: 0x7FFBB58D0000 Size: 15360
ZLIB1.dll Base Address: 0x7FFBBFA50000 Size: 54784
CRYPTSP.dll Base Address: 0x7FFBE3050000 Size: 46080
rsaenh.dll Base Address: 0x7FFBE26D0000 Size: 142336
mswsock.dll Base Address: 0x7FFBE2DF0000 Size: 331776
dbghelp.dll Base Address: 0x7FFBD9E00000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFBD9DC0000 Size: 136704
d3d12.dll Base Address: 0x7FFBA1A50000 Size: 92160
uxtheme.dll Base Address: 0x7FFBE1030000 Size: 382976
AudioDevProps2.dll Base Address: 0x7FFBA8CF0000 Size: 624640
imagehlp.dll Base Address: 0x7FFBE57C0000 Size: 45056
NahimicOSD.dll Base Address: 0x7FFBA10A0000 Size: 433152
ProductInfo.dll Base Address: 0x7FFBA1990000 Size: 55808
AudioDevProps2.dll Base Address: 0x7FFBAE7D0000 Size: 624640
gpapi.dll Base Address: 0x7FFBE1F00000 Size: 69120
clbcatq.dll Base Address: 0x7FFBE47F0000 Size: 437760
dxdiagn.dll Base Address: 0x7FFB979A0000 Size: 395264
d3d11.dll Base Address: 0x7FFBDFB60000 Size: 1853440
dxgi.dll Base Address: 0x7FFBE1F30000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFBE3440000 Size: 132608
WMICLNT.dll Base Address: 0x7FFBDE8D0000 Size: 31744
cryptnet.dll Base Address: 0x7FFBDB2D0000 Size: 135168
wbemprox.dll Base Address: 0x7FFBDBCA0000 Size: 27648
wbemcomn.dll Base Address: 0x7FFBDCFE0000 Size: 328704
profapi.dll Base Address: 0x18355BF0000 Size: 88064
WINNSI.DLL Base Address: 0x7FFBDDF30000 Size: 11776
NSI.dll Base Address: 0x7FFBE5780000 Size: 7680
wbemsvc.dll Base Address: 0x7FFBDA9C0000 Size: 7168
steam_api64.dll Base Address: 0x6F3E0000 Size: 110592
steamclient64.dll Base Address: 0x7FFB108F0000 Size: 16286208
tier0_s64.dll Base Address: 0x7FFB84610000 Size: 259584
vstdlib_s64.dll Base Address: 0x7FFB91F20000 Size: 285184
Secur32.dll Base Address: 0x7FFBC5B00000 Size: 11264
SSPICLI.DLL Base Address: 0x7FFBE3590000 Size: 123904
fastprox.dll Base Address: 0x7FFBDAA80000 Size: 708608
amsi.dll Base Address: 0x7FFBD41B0000 Size: 62464
USERENV.dll Base Address: 0x7FFBE3560000 Size: 108032
aswAMSI.dll Base Address: 0x7FFBD40C0000 Size: 540160
nvapi64.dll Base Address: 0x7FFBD2810000 Size: 6282752
drvstore.dll Base Address: 0x7FFBDB180000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFBB6230000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFBD4D10000 Size: 7680
dhcpcsvc.DLL Base Address: 0x7FFBDD3B0000 Size: 61440
MSCTF.dll Base Address: 0x7FFBE5A50000 Size: 864256
textinputframework.dll Base Address: 0x7FFBCA200000 Size: 726016
WINSTA.dll Base Address: 0x7FFBE2360000 Size: 190976
nvldumdx.dll Base Address: 0x7FFBDAFA0000 Size: 591360
nvwgf2umx.dll Base Address: 0x7FFBCC840000 Size: 36384256
MessageBus.dll Base Address: 0x7FFBD6E20000 Size: 5349888
dxcore.dll Base Address: 0x7FFBDE8F0000 Size: 147968
HID.DLL Base Address: 0x7FFBE1EF0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFBD9530000 Size: 387072
AudioSes.dll Base Address: 0x7FFBCAD50000 Size: 1037312
ProductInfo.dll Base Address: 0x7FFBAF050000 Size: 56320
XAudio2_7.dll Base Address: 0x7FFBCC110000 Size: 485376
resourcepolicyclient.dll Base Address: 0x7FFBE1160000 Size: 31744
Windows.UI.dll Base Address: 0x7FFBCA760000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFBDDCE0000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFBDDA90000 Size: 1468416
avrt.dll Base Address: 0x7FFBDE780000 Size: 5632
napinsp.dll Base Address: 0x7FFBD3070000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFBD41E0000 Size: 66048
wshbth.dll Base Address: 0x7FFBD4290000 Size: 43008
NLAapi.dll Base Address: 0x7FFBDF080000 Size: 68608
DNSAPI.dll Base Address: 0x7FFBE2AF0000 Size: 595456
winrnr.dll Base Address: 0x7FFBD42B0000 Size: 32768
fwpuclnt.dll Base Address: 0x7FFBDC740000 Size: 283648
rasadhlp.dll Base Address: 0x7FFBDA7A0000 Size: 7168
DPAPI.dll Base Address: 0x7FFBE34A0000 Size: 5632
socialclub.dll Base Address: 0x7FFB0FCF0000 Size: 5133824
chrome_elf.dll Base Address: 0x7FFB855C0000 Size: 676864
libcef.dll Base Address: 0x7FFB07C50000 Size: 109744128
COMDLG32.dll Base Address: 0x7FFBE4970000 Size: 684032
UIAutomationCore.DLL Base Address: 0x7FFBBE790000 Size: 2040832
OLEACC.dll Base Address: 0x7FFBD86B0000 Size: 260608
NETAPI32.dll Base Address: 0x7FFBD48F0000 Size: 47616
COMCTL32.dll Base Address: 0x7FFBD7560000 Size: 560128
WINSPOOL.DRV Base Address: 0x7FFBD8720000 Size: 389632
DWrite.dll Base Address: 0x7FFBC7E50000 Size: 1601024
USP10.dll Base Address: 0x7FFBDF4E0000 Size: 512
dxva2.dll Base Address: 0x7FFBDF500000 Size: 96256
credui.dll Base Address: 0x7FFB94C40000 Size: 55808
urlmon.dll Base Address: 0x7FFBD68C0000 Size: 1283072
WINHTTP.dll Base Address: 0x7FFBDCB90000 Size: 845312
ncrypt.dll Base Address: 0x7FFBE3160000 Size: 98304
CRYPTUI.dll Base Address: 0x7FFBDF530000 Size: 246272
wevtapi.dll Base Address: 0x7FFBDE7E0000 Size: 296960
ESENT.dll Base Address: 0x7FFBCB500000 Size: 2585088
srvcli.dll Base Address: 0x7FFBDCCC0000 Size: 54272
netutils.dll Base Address: 0x7FFBE2BC0000 Size: 19456
iertutil.dll Base Address: 0x7FFBD65B0000 Size: 550400
WKSCLI.DLL Base Address: 0x7FFBE2830000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFBDCCF0000 Size: 61440
NTASN1.dll Base Address: 0x7FFBE3120000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFBE2260000 Size: 329728
fwbase.dll Base Address: 0x7FFBE2220000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFBB5E50000 Size: 205824
wdmaud.drv Base Address: 0x7FFBD4CC0000 Size: 193024
msacm32.drv Base Address: 0x7FFBD63F0000 Size: 17920
MSACM32.dll Base Address: 0x7FFBD6350000 Size: 74240
midimap.dll Base Address: 0x7FFBD4D80000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFBC0A20000 Size: 42496
dhcpcsvc6.DLL Base Address: 0x7FFBDD1A0000 Size: 23552
YimMenu.dll Base Address: 0x7FFB04F60000 Size: 6497280
D3DCOMPILER_47.dll Base Address: 0x7FFBDF700000 Size: 3396608
Dumping registers:
RAX: 0x49
RCX: 0x183D0D65120
RDX: 0x11
RBX: 0x1831BF7F130
RSI: 0x183E27F407F
RDI: 0x183E28066B1
RSP: 0x5E456FF1F0
RBP: 0x5E456FF289
R8:  0x7FF7DBCC3070
R9:  0x183E2800000
R10: 0x2
R11: 0x1831BF7D920
R12: 0x8
R13: 0x183E2807DE0
R14: 0x1831BF7F108
R15: 0x1831BF73B58
Dumping stacktrace:
[0]	GTA5.exe+0x160DFCB 0x7FF7DA42DFCB
[1]	GTA5.exe+0x160E9CB 0x7FF7DA42E9CB
[2]	GTA5.exe+0xA52D9C 0x7FF7D9872D9C
[3]	GTA5.exe+0x160F0AD 0x7FF7DA42F0AD
[4]	GTA5.exe+0xA47610 0x7FF7D9867610
[5]	GTA5.exe+0xA4AED8 0x7FF7D986AED8
[6]	GTA5.exe+0x161DEF9 0x7FF7DA43DEF9
[7]	GTA5.exe+0x161DEF9 0x7FF7DA43DEF9
[8]	GTA5.exe+0x161D72B 0x7FF7DA43D72B
[9]	GTA5.exe+0x27820 0x7FF7D8E47820
[10]	GTA5.exe+0x20F07 0x7FF7D8E40F07
[11]	GTA5.exe+0x161D334 0x7FF7DA43D334
[12]	GTA5.exe+0x1494 0x7FF7D8E21494
[13]	GTA5.exe+0x12F50BB 0x7FF7DA1150BB
[14]	GTA5.exe+0x180FFB0 0x7FF7DA62FFB0
[15]	KERNEL32.DLL BaseThreadInitThunk
[16]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[03:00:11.7999578][INFO/main.cpp:127] Renderer initialized.
[03:00:11.9824473][INFO/main.cpp:131] Fiber pool initialized.
[03:00:11.9833677][INFO/main.cpp:134] HTTP Client initialized.
[03:00:12.3541156][INFO/main.cpp:137] Translation Service initialized.
[03:00:12.3680217][INFO/main.cpp:140] Hooking initialized.
[03:00:12.3732709][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[03:00:12.3732799][INFO/gta_data_service.cpp:172] Loading 1029 peds from cache.
[03:00:12.3736308][INFO/gta_data_service.cpp:190] Loading 810 vehicles from cache.
[03:00:12.3738830][INFO/gta_data_service.cpp:207] Loading 117 weapons from cache.
[03:00:12.3738849][INFO/gta_data_service.cpp:208] Loading 378 weapon components from cache.
[03:00:12.3738982][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[03:00:12.3797032][INFO/main.cpp:161] Registered service instances...
[03:00:12.3798489][INFO/main.cpp:182] Scripts registered.
[03:00:12.4493829][INFO/main.cpp:185] Hooking enabled.
[03:00:12.4516293][INFO/main.cpp:188] Dynamic native hooker initialized.
[03:00:12.4520260][INFO/main.cpp:191] Lua manager initialized.
[03:00:12.5297759][INFO/backend.cpp:53] Starting script: Self
[03:00:12.5299201][INFO/backend.cpp:78] Starting script: Weapons
[03:00:12.5299374][INFO/backend.cpp:101] Starting script: Vehicles
[03:00:12.5299482][INFO/backend.cpp:117] Starting script: Miscellaneous
[03:00:12.5299824][INFO/backend.cpp:138] Starting script: Remote
[03:00:12.5300027][INFO/backend.cpp:153] Starting script: Ls customs
[03:00:12.5300050][INFO/backend.cpp:165] Starting script: Rainbow paint
[03:00:12.5300071][INFO/backend.cpp:177] Starting script: Disable Control Action
[03:00:12.5300102][INFO/backend.cpp:190] Starting script: World
[03:00:12.5480439][INFO/tunables_service.cpp:36] Loading tunables from cache
[03:00:22.6105726][INFO/queue_dependency.cpp:63] Blocking AC Verifier 669f48
[03:00:22.6106011][INFO/queue_dependency.cpp:63] Blocking AC Verifier 669f70
[03:00:34.6149170][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: UVC; DATA: "vc":false
[03:00:38.6794379][INFO/queue_dependency.cpp:63] Blocking AC Verifier 95bd58
[03:00:38.6794716][INFO/queue_dependency.cpp:63] Blocking AC Verifier a5fe68
[03:02:48.6058498][INFO/queue_dependency.cpp:63] Blocking AC Verifier 3143f8
[03:02:48.6109011][INFO/queue_dependency.cpp:63] Blocking AC Verifier 4557c0
[03:02:48.6110342][INFO/queue_dependency.cpp:63] Blocking AC Verifier 454a04
[03:02:48.6110428][INFO/queue_dependency.cpp:63] Blocking AC Verifier 5c5650
[03:02:48.6134891][INFO/queue_dependency.cpp:63] Blocking AC Verifier 669f98
[03:02:48.6135061][INFO/queue_dependency.cpp:63] Blocking AC Verifier 669f20
[03:02:48.6161702][INFO/queue_dependency.cpp:63] Blocking AC Verifier 330c1c
[03:02:48.6161905][INFO/queue_dependency.cpp:63] Blocking AC Verifier 330bf4
[03:02:48.6162097][INFO/queue_dependency.cpp:63] Blocking AC Verifier 3fbf30
[03:05:56.7027132][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: AWARD_XP; DATA: "amt":10226488,"type":3136273443,"cat":654913086,"pt":2691963272,"slot":0
[03:12:45.9863810][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: AWARD_XP; DATA: "amt":10226488,"type":3136273443,"cat":654913086,"pt":2692369232,"slot":0
[03:14:02.2019942][WARN/reaction.cpp:60] Received Remote Ragdoll from JAKELIKESWILLY69 (240266414)
[03:14:02.2477498][WARN/reaction.cpp:60] Received Remote Ragdoll from JAKELIKESWILLY69 (240266414)
[03:14:02.2990922][WARN/reaction.cpp:60] Received Remote Ragdoll from JAKELIKESWILLY69 (240266414)
[03:15:14.5520006][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: EARN; DATA: "amt":7000,"char":{"slot":0,"cash":0,"bank":35610385,"evc":35617467,"pvc":0,"pxr":0.00000,"nonce":638373429111341077},"c":[-3118.82715,797.97003,17.98220],"pt":2692509279,"vct":0,"vcp":0,"mid":0,"action":"BOUNTY","cat":"JOBS","ctx":{"A":"UNKNOWN","B":"398
[03:15:14.5520320][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: EARN; DATA: "amt":7000,"char":{"slot":0,"cash":0,"bank":35610385,"evc":35617467,"pvc":0,"pxr":0.00000,"nonce":638373429111341077},"c":[-3118.82715,797.97003,17.98220],"pt":2692509279,"vct":0,"vcp":0,"mid":0,"action":"BOUNTY","cat":"JOBS","ctx":{"A":"UNKNOWN","B":"398
[03:15:23.0359682][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: AWARD_XP; DATA: "amt":640,"type":2658791846,"cat":3135401010,"pt":2692509279,"slot":0
[03:15:38.9520944][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: AWARD_XP; DATA: "amt":10227128,"type":3136273443,"cat":654913086,"pt":2692540498,"slot":0
[03:17:01.1463281][WARN/reaction.cpp:60] Received Modder Detection from lllllllllllll29 (234726037)
[03:20:51.4563391][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: EARN; DATA: "amt":15,"char":{"slot":0,"cash":15,"bank":35609885,"evc":35616982,"pvc":0,"pxr":0.00000,"nonce":638373432482950271},"c":[905.80951,45.80763,80.89835],"pt":2692844444,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{},"tobank":false
[03:20:51.4563693][WARN/prepare_metric_for_sending.cpp:92] BAD METRIC: EARN; DATA: "amt":15,"char":{"slot":0,"cash":15,"bank":35609885,"evc":35616982,"pvc":0,"pxr":0.00000,"nonce":638373432482950271},"c":[905.80951,45.80763,80.89835],"pt":2692844444,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{},"tobank":false
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

Also happens on [08:08:58.5399720][INFO/main.cpp:105] Git Info
        Branch: master
        Hash:   b80865f34c5649f0aaec55afe6e2e4261f480410-dirty
        Date:   Tue Dec 5 21:35:05 2023

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Yimura**
This PR adds an onboarding popup to YimMenu, this way new users can instantly choose which language they'd (rather) use, modify the key to open the menu as well as opt-in to hiding the console window.

image

Closes #2486

### CODE REVIEW

**Comment by Killer4563782** [comment]
> I will bet real dollar dollar bills that this is gonna cause just as much headache, as people expect the YimMenu console to popup after injecting, and now nothing is going to happen after injecting, so after this is merged a bombardment of tickets will ensue of: "WHERE'S THE CONSOLE?!"

That will definitely exist, but one could say that the console is simply kept activated by default, allowing users the option to disable it. For instance, one could incorporate a kind of loading screen, similar to the dumping that was already present, where one can then enable or disable the console by default.

**Comment by Yimura** [comment]
Perhaps I should convert this PR into a general improvement PR to make YimMenu more user friendly.

Some things I've got in mind:
- Add onboarding 
   - select language
   - menu opening key
   - if the developer console should be open on inject

**Comment by thehorizon84** [comment]
> Perhaps I should convert this PR into a general improvement PR to make YimMenu more user friendly.
> 
> Some things I've got in mind:
> 
> * Add onboarding
>   
>   * select language
>   * menu opening key
>   * if the developer console should be open on inject

I like that idea, like a launcher. Would definitelly eliminate the confusion.

**Comment by Rxann** [comment]
> I will bet real dollar dollar bills that this is gonna cause just as much headache, as people expect the YimMenu console to popup after injecting, and now nothing is going to happen after injecting, so after this is merged a bombardment of tickets will ensue of: "WHERE'S THE CONSOLE?!"

Yes dipshit, that's why he fucking said to use the toast api to send a notification.

**Comment by Killer4563782** [comment]
> Perhaps I should convert this PR into a general improvement PR to make YimMenu more user friendly.
> 
> Some things I've got in mind:
> 
> * Add onboarding
>   
>   * select language
>   * menu opening key
>   * if the developer console should be open on inject

How about having something like a loading screen where initially, you have the menu open button, menu language, the console, and perhaps automatic saving? Afterward, you could have a kind of tutorial where you're 'introduced' to the menu, showing you everything like checkboxes, tabs, buttons, and so on.

**Comment by Rxann** [comment]
I think the "introduction" could consist of native gta menus that ask you yes or no questions. idk if that's what you guys are thinking or not but just an idea

**Comment by Killer4563782** [comment]
> I think the "introduction" could consist of native gta menus that ask you yes or no questions. idk if that's what you guys are thinking or not but just an idea

I wouldn't use a native interface but rather the existing ImGui interface, as it familiarizes the user with the interface.

**Comment by Rxann** [comment]
> > I think the "introduction" could consist of native gta menus that ask you yes or no questions. idk if that's what you guys are thinking or not but just an idea
> 
> 
> 
> I wouldn't use a native interface but rather the existing ImGui interface, as it familiarizes the user with the interface.

Yes, actually that is true. But, the interface isn't exactly that complicated.

**Comment by thehorizon84** [comment]
What I would do if I we're "in charge": Upon injecting, grey the entire screen to create a focus effect and add a main small window in the middle with atleast 3 checkboxes, language, show console, auto-save settings, then at the bottom just a simple "choose menu open key" then 2 buttons "Load YimMenu" and "Cancel and Unload".

If I picture this correctly in my mind it will look very aesthetic, yet simplistic and user friendly. I could set this up quickly in an external ImGui application to provide an idea of how it may look if you guys think this will be fitting.

**Comment by Killer4563782** [comment]
> What I would do if I we're "in charge": Upon injecting, grey the entire screen to create a focus effect and add a main small window in the middle with atleast 3 checkboxes, language, show console, auto-save settings, then at the bottom just a simple "choose menu open key" then 2 buttons "Load YimMenu" and "Cancel and Unload".
> 
> If I picture this correctly in my mind it will look very aesthetic, yet simplistic and user friendly. I could set this up quickly in an external ImGui application to provide an idea of how it may look if you guys think this will be fitting.

That sounds like a good idea. Perhaps one could add a selection where the user can choose their level of menu knowledge, and then certain menu features would not be displayed based on this selection

**Comment by Yimura** [comment]
> That sounds like a good idea. Perhaps one could add a selection where the user can choose their level of menu knowledge, and then certain menu features would not be displayed based on this selection

That's going to take a bunch of extra work to implement for little to no beneficial changes to the user experience.

**Comment by Rxann** [comment]
> > That sounds like a good idea. Perhaps one could add a selection where the user can choose their level of menu knowledge, and then certain menu features would not be displayed based on this selection
> 
> 
> 
> That's going to take a bunch of extra work to implement for little to no beneficial changes to the user experience.
> 
> 

I agree

**Comment by ghost** [comment]
How about, Minimizing the console right after injection say after some part of the injecting. I am not familiar with this codebase as i have found it only today from one of Yim's post on UC but from what i can tell it would be before this part (Where we listen for an unload):

```
g_running = true;

while (g_running)
    std::this_thread::sleep_for(500ms);
```

in **main.cpp**

You could add a call to minimise the console (This should give a brief period of time for users to see it and helpful for those who DO want it as they can just re focus it and they have it.)

Maybe something like this:

```
g_running = true;

ShowWindow(GetConsoleWindow(),SW_MINIMIZE);

while (g_running)
    std::this_thread::sleep_for(500ms);
```

Happy coding.

**Comment by Yimura** [comment]
Ready to be tested.

**Review by gir489returns — DISMISSED** [review]

**Pull request merged**
