### PR TITLE
feat(Self & Spoofing)

### PR DESCRIPTION
**Pull request by karifeld**
optimization and ease of access

### CODE REVIEW

**Comment by Yimura** [comment]
Looks good I will check it out when I get back to my home pc.

**Review by ThatKakiGuy — APPROVED** [review]

**Comment by Yimura** [comment]
Ye seems good, thanks for contributing!

**Comment by szarpii** [comment]
Ey yo, 18 is my number, my fave, if someone wondering why 18, lol

**Comment by 7HA7MA77** [comment]
yooo my number! o/

**Pull request merged**
