### PR TITLE
fix(ESP): Elements getting cut off on screen edges

### PR DESCRIPTION
**Pull request by ghost**
The ESP elements render improperly on the edges of the screen (Specifically the top and the left). It seems to be simple confusion between _ImGui::GetWindowDrawList();_ and _ImGui::GetBackgroundDrawList();_. Very easy fix.

### CODE REVIEW

**Comment by Yimura** [comment]
Thanks for the fix Caden 😉 

If that was the fix then thank you, we weren't aware of a way to resolve this issue.
Will check it out when I have the time and then merge it.

**Comment by Loko415** [comment]
caden unban? 👀

**Comment by Yimura** [comment]
> caden unban? 👀

No he's free to contribute on Github, but remains banned on Discord for his behaviour.

**Comment by cl52902** [comment]
> > caden unban? 👀
> 
> 
> 
> No he's free to contribute on Github, but remains banned on Discord for his behaviour.

😺❤️

**Comment by ghost** [comment]
I am just realizing now that I forgot to remove the `ImGui::End();` statement on line 97. Other than that the code works perfectly.

**Comment by Yimura** [comment]
Do you want me to fix it or will you push a fix?

**Comment by Yimura** [comment]
@cl1xa @cl52902 I can't push to your remote so you'll have to push the fix yourself.

Aside from that the fix works as intended and I will merge it into master once you've done that.

**Comment by ghost** [comment]
Pushed the fix to my branch just now.

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
Thanks for your contribution!

**Pull request merged**
