### PR TITLE
fix(hotkey) check for is chatbox is active

### LINKED ISSUE #1948: [Bug]: Hotkeys while in textfields
### Describe the bug

When i'm currently in a textfield (socialclub message, sending text message via phone, other popups where you need to enter text), keybinds are still working. This is very FRUSTRATING and LIFE CHANGEING when something is bound to key like a-z.

### Steps To Reproduce

Bind e.g. noclip to n.
Send someone a message (like don't send just click send so gui opens)
Type n in gui
NoClip should enable

### Expected Behavior

NoClip should not enable :D

### Logs and/or screenshots

Nah

### Store

Epic Games

### Additional context

I think that the text gui should be easy. With socialclub idk

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by alyxme**
Add check to disable hotkeys if chat typing is active
Closes #1948

### CODE REVIEW

**Review by Yimura — CHANGES_REQUESTED** [review]
I’m pretty sure this code doesn’t work, I didn’t test it though.

Did you test it?

**Comment by alyxme** [comment]
> I’m pretty sure this code doesn’t work, I didn’t test it though.
> 
> Did you test it?

yes tested right now. works fine!

**Comment by xiaoxiao921** [comment]
Can you test again?

**Comment by alyxme** [comment]
Id not pull that without all tests pass.

**Comment by xiaoxiao921** [comment]
A similar check would make more sense than whatever non working code you just wrote https://github.com/YimMenu/YimMenu/blob/e87931bf605cf967ac5b9d490bfa0dcb3c1bb168/src/backend/looped/weapons/weapon_hotkeys.cpp#L27

**Comment by alyxme** [comment]
> A similar check would make more sense than whatever non working code you just wrote
> 
> https://github.com/YimMenu/YimMenu/blob/e87931bf605cf967ac5b9d490bfa0dcb3c1bb168/src/backend/looped/weapons/weapon_hotkeys.cpp#L27

Yes you may right. Thanks for the review! I was not so into to make this. The behavior of the issue is work because of that code you mentioned!

**Pull request closed without merging**
