### PR TITLE
Redesign Script Patches for Lua

### PR DESCRIPTION
**Pull request by ShinyWasabi**

### CODE REVIEW

**Review by gir489returns — DISMISSED** [review]

**Review by xiaoxiao921 — DISMISSED** [review]

**Review by gir489returns — APPROVED** [review]

**Review by xiaoxiao921 — APPROVED** [review]

**Review by tupoy-ya — APPROVED** [review]
This should be marked as a breaking change.

**Comment by xiaoxiao921** [comment]
From a github search it seems the only user of this was ShinyWasabi so I imagine it's fine even though it is breaking yeah

**Comment by gir489returns** [comment]
> This should be marked as a breaking change.

I'm sure he is aware.

**Review by Yimura — APPROVED** [review]
Missing translation entry?

**Comment by gir489returns** [comment]
> Missing translation entry?

I already merged it.

**Pull request merged**
