### PR TITLE
Update tab_settings.cpp

### PR DESCRIPTION
**Pull request by The-Denno**
feat(settings): added checkboxes to enable and disable protections in tab_settings.cpp

### CODE REVIEW

**Comment by Yimura** [comment]
Please use
```cpp
ImGui::TreeNode("Protections");
// and
ImGui::TreePop();
```

**Comment by Yimura** [comment]
It's fine I'll do it myself.

**Comment by The-Denno** [comment]
good point - already did it.

**Comment by Yimura** [comment]
Thanks seems good!

**Pull request merged**
