### PR TITLE
Actually fix integrity checks

### LINKED ISSUE #2228: [Bug]: Crash while joining session
### Describe the bug

The game crashed at 'Freemode Swoop Down' when i was trying to join my friend's session (It was an invite only session with 2 players) happened twice with me.

Edit: The game crashed automatically after 20-25 minutes (I was with 2 more players in the session hosted by me and no changes in log)

### Steps To Reproduce

1. Inject Menu
2. Try join a lobby hosted by someone else (Try with a friend maybe)
3. Game will be crashed at Freemode Swoop Down

### Expected Behavior

Shouldn't be crashing

### Logs and/or screenshots

[20:07:36.2246870][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[20:07:36.2248451][INFO/main.cpp:68] Thread pool initialized.
[20:07:36.2281535][INFO/main.cpp:71] Settings Loaded.
[20:07:36.2283868][DEBUG/thread_pool.cpp:95] Thread 5156 executing settings.cpp:12
[20:07:36.2285756][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[20:07:36.2285896][INFO/pointers.cpp:1751] Loading pointers instance from cache
[20:07:36.2285918][INFO/pointers.cpp:1760] Pointers cache: Loading 208 fields from the cache
[20:07:36.2286157][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[20:07:36.2287277][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[20:07:36.2287326][INFO/pointers.cpp:1751] Loading pointers instance from cache
[20:07:36.2287350][INFO/pointers.cpp:1760] Pointers cache: Loading 5 fields from the cache
[20:07:36.2290356][INFO/main.cpp:74] Pointers initialized.
[20:07:36.2292410][INFO/main.cpp:77] Byte Patch Manager initialized.
[20:07:36.9070403][INFO/main.cpp:80] Renderer initialized.
[20:07:37.1732933][INFO/main.cpp:84] Fiber pool initialized.
[20:07:38.3891899][INFO/main.cpp:87] Translation Service initialized.
[20:07:38.4571077][INFO/main.cpp:90] Hooking initialized.
[20:07:38.4638953][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[20:07:38.4639137][INFO/gta_data_service.cpp:172] Loading 1029 peds from cache.
[20:07:38.4644093][INFO/gta_data_service.cpp:190] Loading 810 vehicles from cache.
[20:07:38.4648599][INFO/gta_data_service.cpp:207] Loading 117 weapons from cache.
[20:07:38.4648749][INFO/gta_data_service.cpp:208] Loading 378 weapon components from cache.
[20:07:38.4649046][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[20:07:38.4740854][INFO/main.cpp:110] Registered service instances...
[20:07:38.4742672][INFO/main.cpp:131] Scripts registered.
[20:07:38.5125160][INFO/main.cpp:134] Hooking enabled.
[20:07:38.5160587][INFO/main.cpp:137] Dynamic native hooker initialized.
[20:07:38.5163478][INFO/main.cpp:140] Lua manager initialized.
[20:07:38.6698576][INFO/backend.cpp:51] Starting script: Self
[20:07:38.6699043][INFO/backend.cpp:77] Starting script: Weapons
[20:07:38.6699163][INFO/backend.cpp:100] Starting script: Vehicles
[20:07:38.6699485][INFO/backend.cpp:117] Starting script: Miscellaneous
[20:07:38.6699913][INFO/backend.cpp:141] Starting script: Remote
[20:07:38.6700070][INFO/backend.cpp:157] Starting script: Ls customs
[20:07:38.6700090][INFO/backend.cpp:169] Starting script: Rainbow paint
[20:07:38.6700238][INFO/backend.cpp:181] Starting script: Disable Control Action
[20:07:38.6700282][INFO/backend.cpp:194] Starting script: World
[20:07:38.6791251][INFO/tunables_service.cpp:36] Loading tunables from cache
[20:10:21.9461165][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[20:10:40.1413407][INFO/assign_physical_index.cpp:80] Player joined  allocating slot #0 with Rockstar ID: 
[20:20:56.4718090][INFO/assign_physical_index.cpp:80] Player joined  allocating slot #2 with Rockstar ID: 
[20:20:56.4718592][INFO/assign_physical_index.cpp:80] Player joined  allocating slot #0 with Rockstar ID: 
[20:20:59.3959387][INFO/assign_physical_index.cpp:80] Player joined  allocating slot #1 with Rockstar ID: 

### Store

Rockstar

### Additional context

Refreshing the player database will crash the game as well (My bad if it's off topic)

Note: The Game works fine in the session hosted by the user.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2231: [Bug]: Saving the game causes crash
### Describe the bug

Triggering a save causes crash of the game without any mention in logs.

### Steps To Reproduce

1. Trigger a manual or automatic save of the game (change outfit, buy something or smth, just trigger the orange circle)
2. Crash.

### Expected Behavior

Don't crash

### Logs and/or screenshots

```
[08:04:20.1482540][INFO/main.cpp:65] Yim's Menu Initializing
[08:04:20.1482939][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	05575a63570aaa6e7d5f7e94320eababd8641543
	Date:	Sat Oct 7 17:19:46 2023
[08:04:20.1483928][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[08:04:20.2145665][INFO/main.cpp:69] Thread pool initialized.
[08:04:20.2168574][INFO/main.cpp:72] Settings Loaded.
[08:04:20.2168624][DEBUG/thread_pool.cpp:95] Thread 15448 executing settings.cpp:12
[08:04:20.2170406][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[08:04:20.2170540][INFO/pointers.cpp:1751] Loading pointers instance from cache
[08:04:20.2170551][INFO/pointers.cpp:1760] Pointers cache: Loading 208 fields from the cache
[08:04:20.2170623][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[08:04:20.2171224][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[08:04:20.2171253][INFO/pointers.cpp:1751] Loading pointers instance from cache
[08:04:20.2171268][INFO/pointers.cpp:1760] Pointers cache: Loading 5 fields from the cache
[08:04:20.2171411][INFO/main.cpp:75] Pointers initialized.
[08:04:20.2172993][INFO/main.cpp:78] Byte Patch Manager initialized.
[08:04:20.7318737][INFO/main.cpp:81] Renderer initialized.
[08:04:20.9441498][INFO/main.cpp:85] Fiber pool initialized.
[08:04:21.2189705][INFO/main.cpp:88] Translation Service initialized.
[08:04:21.2348631][INFO/main.cpp:91] Hooking initialized.
[08:04:21.2369592][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[08:04:21.2369724][INFO/gta_data_service.cpp:172] Loading 1029 peds from cache.
[08:04:21.2372344][INFO/gta_data_service.cpp:190] Loading 810 vehicles from cache.
[08:04:21.2375083][INFO/gta_data_service.cpp:207] Loading 117 weapons from cache.
[08:04:21.2375146][INFO/gta_data_service.cpp:208] Loading 378 weapon components from cache.
[08:04:21.2375300][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[08:04:21.2390844][DEBUG/thread_pool.cpp:95] Thread 17024 executing player_database_service.cpp:285
[08:04:21.2391328][INFO/main.cpp:111] Registered service instances...
[08:04:21.2392063][INFO/main.cpp:132] Scripts registered.
[08:04:21.2759513][INFO/main.cpp:135] Hooking enabled.
[08:04:21.2784504][INFO/main.cpp:138] Dynamic native hooker initialized.
[08:04:21.2857003][INFO/lua_module.cpp:226] Loaded Alestarov_Menu_V2.1b_1.67.lua
[08:04:21.2941781][WARN/log.cpp:27] pessi.lua: Use At Your Own Risk This Hasn't Been Tested With YimMenu, But It's Safe With Some Menus..
[08:04:21.2942578][INFO/lua_module.cpp:226] Loaded pessi.lua
[08:04:21.3007689][INFO/lua_module.cpp:226] Loaded Ultimate-Menu.lua
[08:04:21.3008169][INFO/main.cpp:141] Lua manager initialized.
[08:04:21.3066571][INFO/backend.cpp:51] Starting script: Self
[08:04:21.3066683][INFO/backend.cpp:76] Starting script: Weapons
[08:04:21.3066845][INFO/backend.cpp:99] Starting script: Vehicles
[08:04:21.3066924][INFO/backend.cpp:115] Starting script: Miscellaneous
[08:04:21.3067006][INFO/backend.cpp:136] Starting script: Remote
[08:04:21.3067031][INFO/backend.cpp:151] Starting script: Ls customs
[08:04:21.3067067][INFO/backend.cpp:163] Starting script: Rainbow paint
[08:04:21.3067079][INFO/backend.cpp:175] Starting script: Disable Control Action
[08:04:21.3067097][INFO/backend.cpp:188] Starting script: World
[08:04:21.3164171][INFO/tunables_service.cpp:36] Loading tunables from cache
[08:04:26.2393198][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[08:04:47.2052801][INFO/assign_physical_index.cpp:80] Player joined Player allocating slot #0 with Rockstar ID: 1
```

### Store

Epic Games

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by maybegreat48**
Fixes #2231
Fixes #2228

### CODE REVIEW

**Comment by pierrelasse** [comment]
lgtm & works (for me)

**Comment by Tayipc38** [comment]
> lgtm & works (for me)

Just takes a little more before it crashes for me.

**Comment by pierrelasse** [comment]
> Just takes a little more before it crashes for me.

F.
Yeah it just takes longer for you to crash.

**Comment by maybegreat48** [comment]
Yeah the vtable is integrity checked too

**Comment by abuazizv** [comment]
QD hook also crashes the game not sure if you guys aware of this or not.

**Comment by Tayipc38** [comment]
> QD hook also crashes the game not sure if you guys aware of this or not.

This entire PR exists because of that, so I'd say we do know.

**Comment by mangocider** [comment]
still seems to prolong a crash. went from 10-20mins to a little over an hour. witnessed this in both story and in a solo session.

**Comment by maybegreat48** [comment]
> still seems to prolong a crash. went from 10-20mins to a little over an hour. witnessed this in both story and in a solo session.

Logs?

**Comment by tiCkuhAr** [comment]
Self seems to still be crashing.

```
[17:25:28.4263026][INFO/main.cpp:65] Yim's Menu Initializing
[17:25:28.4263224][INFO/main.cpp:66] Git Info
        Branch: master
        Hash:   05575a63570aaa6e7d5f7e94320eababd8641543
        Date:   Sat Oct 7 09:19:46 2023
[17:25:28.4263349][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[17:25:28.4265445][INFO/main.cpp:69] Thread pool initialized.
[17:25:28.4292134][INFO/main.cpp:72] Settings Loaded.
[17:25:28.4292334][DEBUG/thread_pool.cpp:95] Thread 11744 executing settings.cpp:12
[17:25:28.4297827][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[17:25:28.4297910][INFO/pointers.cpp:1751] Loading pointers instance from cache
[17:25:28.4297930][INFO/pointers.cpp:1760] Pointers cache: Loading 208 fields from the cache
[17:25:28.4298075][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[17:25:28.4299699][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[17:25:28.4299740][INFO/pointers.cpp:1751] Loading pointers instance from cache
[17:25:28.4299760][INFO/pointers.cpp:1760] Pointers cache: Loading 5 fields from the cache
[17:25:28.4300070][INFO/main.cpp:75] Pointers initialized.
[17:25:28.4301466][INFO/main.cpp:78] Byte Patch Manager initialized.
[17:25:28.9773069][INFO/main.cpp:81] Renderer initialized.
[17:25:29.2368915][INFO/main.cpp:85] Fiber pool initialized.
[17:25:29.4401846][INFO/main.cpp:88] Translation Service initialized.
[17:25:29.4682913][INFO/main.cpp:91] Hooking initialized.
[17:25:29.4729175][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[17:25:29.4729265][INFO/gta_data_service.cpp:172] Loading 1029 peds from cache.
[17:25:29.4733542][INFO/gta_data_service.cpp:190] Loading 810 vehicles from cache.
[17:25:29.4736723][INFO/gta_data_service.cpp:207] Loading 117 weapons from cache.
[17:25:29.4736813][INFO/gta_data_service.cpp:208] Loading 378 weapon components from cache.
[17:25:29.4737006][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[17:25:29.4742610][DEBUG/thread_pool.cpp:95] Thread 20592 executing player_database_service.cpp:285
[17:25:29.4744484][INFO/main.cpp:111] Registered service instances...
[17:25:29.4745816][INFO/main.cpp:132] Scripts registered.
[17:25:29.5277300][INFO/main.cpp:135] Hooking enabled.
[17:25:29.5277655][INFO/main.cpp:138] Dynamic native hooker initialized.
[17:25:29.5280784][INFO/main.cpp:141] Lua manager initialized.
[17:25:32.3853131][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7DF280000 Size: 66857984
ntdll.dll Base Address: 0x7FFF05250000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFF04FA0000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFF02E60000 Size: 1255936
apphelp.dll Base Address: 0x7FFF00160000 Size: 323584
USER32.dll Base Address: 0x7FFF04C50000 Size: 584704
win32u.dll Base Address: 0x7FFF03160000 Size: 42496
GDI32.dll Base Address: 0x7FFF04310000 Size: 61952
gdi32full.dll Base Address: 0x7FFF03190000 Size: 686080
msvcp_win.dll Base Address: 0x7FFF02B10000 Size: 344064
ucrtbase.dll Base Address: 0x7FFF02BB0000 Size: 735744
PSAPI.DLL Base Address: 0x7FFF04E20000 Size: 2048
WS2_32.dll Base Address: 0x7FFF04F30000 Size: 275456
RPCRT4.dll Base Address: 0x7FFF04650000 Size: 923136
CRYPT32.dll Base Address: 0x7FFF02D00000 Size: 1100288
WINTRUST.dll Base Address: 0x7FFF02930000 Size: 292864
msvcrt.dll Base Address: 0x7FFF04480000 Size: 477184
IMM32.dll Base Address: 0x7FFF04DF0000 Size: 122368
bcrypt.dll Base Address: 0x7FFF02AE0000 Size: 102912
SHLWAPI.dll Base Address: 0x7FFF04E30000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFF03610000 Size: 423424
sechost.dll Base Address: 0x7FFF05170000 Size: 412672
SHELL32.dll Base Address: 0x7FFF03990000 Size: 5804544
ole32.dll Base Address: 0x7FFF04340000 Size: 832000
combase.dll Base Address: 0x7FFF032B0000 Size: 2327040
OLEAUT32.dll Base Address: 0x7FFF037E0000 Size: 608768
VERSION.dll Base Address: 0x7FFEFCBB0000 Size: 10752
DSOUND.dll Base Address: 0x7FFE9E0E0000 Size: 380928
WININET.dll Base Address: 0x7FFEEA9B0000 Size: 2019840
WINMM.dll Base Address: 0x7FFEFA770000 Size: 81408
MF.dll Base Address: 0x7FFEC1080000 Size: 340992
msdmo.dll Base Address: 0x7FFEE0650000 Size: 13312
MFPlat.DLL Base Address: 0x7FFEB8130000 Size: 1409536
cfgmgr32.dll Base Address: 0x7FFF02CB0000 Size: 219136
shcore.dll Base Address: 0x7FFF050C0000 Size: 476672
MFReadWrite.dll Base Address: 0x7FFECF780000 Size: 918016
PROPSYS.dll Base Address: 0x7FFEFE460000 Size: 631296
WTSAPI32.dll Base Address: 0x7FFEFE5C0000 Size: 37888
d3d9.dll Base Address: 0x7FFECD8A0000 Size: 1371648
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFE98CE0000 Size: 96256
DINPUT8.dll Base Address: 0x7FFED0E90000 Size: 169472
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFEED6E0000 Size: 48128
IPHLPAPI.DLL Base Address: 0x7FFF01D70000 Size: 166400
D3DCOMPILER_43.dll Base Address: 0x7FFEB8A20000 Size: 2423296
powrprof.dll Base Address: 0x7FFF01EE0000 Size: 70656
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFF04780000 Size: 887808
winmmbase.dll Base Address: 0x7FFEBA820000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFF00700000 Size: 16384
windows.storage.dll Base Address: 0x7FFF009E0000 Size: 5841408
dwmapi.dll Base Address: 0x7FFF006D0000 Size: 99328
OPENGL32.dll Base Address: 0x7FFEC0160000 Size: 909312
Wldp.dll Base Address: 0x7FFF02370000 Size: 94720
GLU32.dll Base Address: 0x7FFEC00F0000 Size: 122880
bink2w64.dll Base Address: 0x7FFECF6F0000 Size: 307712
d3dx9_43.dll Base Address: 0x7FFE8C170000 Size: 2280960
MFCORE.DLL Base Address: 0x7FFE8BCE0000 Size: 3959296
ksuser.dll Base Address: 0x7FFED8CE0000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFF022E0000 Size: 10752
UMPDC.dll Base Address: 0x7FFF01D50000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFF02A50000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFEBCEB0000 Size: 105472
MSASN1.dll Base Address: 0x7FFF02500000 Size: 34816
inputhost.dll Base Address: 0x7FFEE95F0000 Size: 976384
CoreMessaging.dll Base Address: 0x7FFEFFDF0000 Size: 606720
wintypes.dll Base Address: 0x7FFEFE5E0000 Size: 487424
CoreUIComponents.dll Base Address: 0x7FFEFFA90000 Size: 1804800
ntmarta.dll Base Address: 0x7FFF01A90000 Size: 140288
dbghelp.dll Base Address: 0x7FFEF7FF0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFEEA730000 Size: 136704
d3d12.dll Base Address: 0x7FFED3D90000 Size: 92160
CRYPTSP.dll Base Address: 0x7FFF022C0000 Size: 46080
rsaenh.dll Base Address: 0x7FFF01970000 Size: 142336
uxtheme.dll Base Address: 0x7FFF00310000 Size: 382976
clbcatq.dll Base Address: 0x7FFF045A0000 Size: 437760
imagehlp.dll Base Address: 0x7FFF040E0000 Size: 45056
dxdiagn.dll Base Address: 0x7FFECEAA0000 Size: 395264
d3d11.dll Base Address: 0x7FFEFECF0000 Size: 1853440
DEVOBJ.dll Base Address: 0x7FFF026C0000 Size: 132608
dxgi.dll Base Address: 0x7FFF011C0000 Size: 614912
WMICLNT.dll Base Address: 0x7FFEFDF70000 Size: 31744
wbemprox.dll Base Address: 0x7FFEFC530000 Size: 27648
wbemcomn.dll Base Address: 0x7FFEF4CF0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFEFA0E0000 Size: 7168
fastprox.dll Base Address: 0x7FFEFA140000 Size: 708608
amsi.dll Base Address: 0x7FFEF9FC0000 Size: 62464
gpapi.dll Base Address: 0x7FFF01190000 Size: 69120
cryptnet.dll Base Address: 0x7FFEFCB70000 Size: 135168
profapi.dll Base Address: 0x7FFF02860000 Size: 88064
WINNSI.DLL Base Address: 0x7FFEFCB50000 Size: 11776
NSI.dll Base Address: 0x7FFF04F20000 Size: 7680
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFE4FD50000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFF04100000 Size: 240128
Normaliz.dll Base Address: 0x7FFF04470000 Size: 512
WINHTTP.dll Base Address: 0x7FFEFB470000 Size: 845312
Secur32.dll Base Address: 0x7FFEF5330000 Size: 11264
MSVCP140.dll Base Address: 0x7FFEED430000 Size: 345600
VCRUNTIME140.dll Base Address: 0x7FFEED410000 Size: 65024
SSPICLI.DLL Base Address: 0x7FFF02810000 Size: 123904
VCRUNTIME140_1.dll Base Address: 0x7FFEED3A0000 Size: 15360
dhcpcsvc6.DLL Base Address: 0x7FFEFC7D0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFEFC8E0000 Size: 61440
mswsock.dll Base Address: 0x7FFF020D0000 Size: 331776
napinsp.dll Base Address: 0x7FFEE3180000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFEE3160000 Size: 66048
wshbth.dll Base Address: 0x7FFEE3120000 Size: 43008
NLAapi.dll Base Address: 0x7FFEFE2B0000 Size: 68608
DNSAPI.dll Base Address: 0x7FFF01DC0000 Size: 595456
winrnr.dll Base Address: 0x7FFEE3100000 Size: 32768
mdnsNSP.dll Base Address: 0x66190000 Size: 91136
nvapi64.dll Base Address: 0x7FFEFA7E0000 Size: 6283776
drvstore.dll Base Address: 0x7FFEFC900000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFEC0120000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFEC1DB0000 Size: 7680
nvspcap64.dll Base Address: 0x7FFEBA010000 Size: 2055680
MSCTF.dll Base Address: 0x7FFF036C0000 Size: 864256
textinputframework.dll Base Address: 0x7FFEE8B90000 Size: 726016
WINSTA.dll Base Address: 0x7FFF01600000 Size: 190976
nvldumdx.dll Base Address: 0x7FFEFC690000 Size: 591360
rasadhlp.dll Base Address: 0x7FFEFA7D0000 Size: 7168
nvwgf2umx.dll Base Address: 0x7FFEEE4D0000 Size: 36396032
MessageBus.dll Base Address: 0x7FFEF7230000 Size: 5349888
dxcore.dll Base Address: 0x7FFEFC7F0000 Size: 147968
fwpuclnt.dll Base Address: 0x7FFEFA440000 Size: 288768
HID.DLL Base Address: 0x7FFF01180000 Size: 20480
MMDevApi.dll Base Address: 0x7FFEF4D80000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFECEA10000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFEC5000000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFF003D0000 Size: 31744
Windows.UI.dll Base Address: 0x7FFEC4300000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFEFDA90000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFEFD880000 Size: 1468416
avrt.dll Base Address: 0x7FFEFDF60000 Size: 5632
symsrv.dll Base Address: 0x7FFECE9B0000 Size: 83968
USERENV.dll Base Address: 0x7FFF027E0000 Size: 108032
socialclub.dll Base Address: 0x7FFEA0A10000 Size: 4990464
chrome_elf.dll Base Address: 0x7FFECFA30000 Size: 676864
libcef.dll Base Address: 0x7FFE23B70000 Size: 109744128
COMDLG32.dll Base Address: 0x7FFF038B0000 Size: 684032
UIAutomationCore.DLL Base Address: 0x7FFEBB530000 Size: 2040832
OLEACC.dll Base Address: 0x7FFEF7A20000 Size: 260608
NETAPI32.dll Base Address: 0x7FFEF6AB0000 Size: 47616
DWrite.dll Base Address: 0x7FFECB410000 Size: 1601024
WINSPOOL.DRV Base Address: 0x7FFEF7A90000 Size: 364544
COMCTL32.dll Base Address: 0x7FFEF7970000 Size: 560128
USP10.dll Base Address: 0x7FFEE0740000 Size: 512
dxva2.dll Base Address: 0x7FFED6D60000 Size: 96256
credui.dll Base Address: 0x7FFEFE2D0000 Size: 61952
urlmon.dll Base Address: 0x7FFEEA440000 Size: 1282560
CRYPTUI.dll Base Address: 0x7FFEEA900000 Size: 246272
wevtapi.dll Base Address: 0x7FFEFD110000 Size: 296960
ESENT.dll Base Address: 0x7FFEF53D0000 Size: 2585088
ncrypt.dll Base Address: 0x7FFF023E0000 Size: 102400
netutils.dll Base Address: 0x7FFF01DB0000 Size: 19456
srvcli.dll Base Address: 0x7FFEF4960000 Size: 58368
iertutil.dll Base Address: 0x7FFEEA180000 Size: 550400
WKSCLI.DLL Base Address: 0x7FFF01AD0000 Size: 51200
SAMCLI.DLL Base Address: 0x7FFEFAF80000 Size: 61440
NTASN1.dll Base Address: 0x7FFF023A0000 Size: 81408
xinput1_4.dll Base Address: 0x7FFED3F20000 Size: 30208
schannel.DLL Base Address: 0x7FFF01880000 Size: 480768
mskeyprotect.dll Base Address: 0x7FFEF50A0000 Size: 48640
ncryptsslp.dll Base Address: 0x7FFEF5300000 Size: 78848
FirewallAPI.dll Base Address: 0x7FFF01520000 Size: 364544
fwbase.dll Base Address: 0x7FFF014B0000 Size: 159744
FWPolicyIOMgr.dll Base Address: 0x7FFEED500000 Size: 216064
wdmaud.drv Base Address: 0x7FFEB86E0000 Size: 193024
msacm32.drv Base Address: 0x7FFED4250000 Size: 17920
MSACM32.dll Base Address: 0x7FFED2400000 Size: 74240
midimap.dll Base Address: 0x7FFED3D40000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFEE34D0000 Size: 42496
YimMenu.dll Base Address: 0x7FFE4F4A0000 Size: 6266880
D3DCOMPILER_47.dll Base Address: 0x7FFEFE890000 Size: 3396608
Dumping registers:
RAX: 0x757A0
RCX: 0x0
RDX: 0x0
RBX: 0x0
RSI: 0x1DD79CAFBB0
RDI: 0x1DD1F426B20
RSP: 0x6CA13FF6B0
RBP: 0x6CA13FF7B0
R8:  0x0
R9:  0x0
R10: 0x1DD15F66030
R11: 0x6CA13FF6A0
R12: 0x1B0
R13: 0x0
R14: 0x0
R15: 0x1
Dumping stacktrace:
[0]     YimMenu.dll+0x434FC8 0x7FFE4F8D4FC8
[1]     YimMenu.dll+0x3E6851 0x7FFE4F886851
[2]     YimMenu.dll+0x3E91A8 0x7FFE4F8891A8
[3]     YimMenu.dll+0x47753A 0x7FFE4F91753A
[4]     YimMenu.dll+0x348F2F 0x7FFE4F7E8F2F
[5]     YimMenu.dll+0xD8A54 0x7FFE4F578A54
[6]     GTA5.exe+0x138672A 0x7FF7E060672A
[7]     GTA5.exe+0x7E8229 0x7FF7DFA68229
[8]     GTA5.exe+0x2D8A3A 0x7FF7DF558A3A
[9]     GTA5.exe+0x1645130 0x7FF7E08C5130
[10]    GTA5.exe+0x164E00A 0x7FF7E08CE00A
[11]    GTA5.exe+0x12FE732 0x7FF7E057E732
[12]    KERNEL32.DLL BaseThreadInitThunk
[13]    ntdll.dll RtlUserThreadStart
--------End of exception--------


```

**Comment by maybegreat48** [comment]
> Self seems to still be crashing.
> 
> ...

This crash is unrelated to the anticheat or Arxan. I've accidentally linked this PR to the bug report, I've removed it now. PS: that crash has something to do with the hotkey service

**Comment by tiCkuhAr** [comment]
> > Self seems to still be crashing.
> > ...
> 
> This crash is unrelated to the anticheat or Arxan

Then why did you say it would fix it?

**Comment by mangocider** [comment]
> > still seems to prolong a crash. went from 10-20mins to a little over an hour. witnessed this in both story and in a solo session.
> 
> Logs?

ill send next crash, so far it's been logless.

**Review by pierrelasse — COMMENTED** [review]
No virus & works better than before? : D

**Comment by lonelybud** [comment]
i will probably open an issue for passive mod disabled check. In view_self file at line no 43 seems to break sometimes when loading into a session.

**Comment by mangocider** [comment]
> > > still seems to prolong a crash. went from 10-20mins to a little over an hour. witnessed this in both story and in a solo session.
> > 
> > 
> > Logs?
> 
> ill send next crash, so far it's been logless.

could've been a fluke, in a public lobby now and have yet to crash over an hour in. seems like a solid enough patch for the moment.

**Comment by CypherMorgan** [comment]
Works fine for me too, played for like 1.5 hour (there were two modder friends using 2t1 (spawning cml maps and stuffs) with me as well yet no crash), seems pretty fine for now.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
