### PR TITLE
refactor!: Added filters for Visual Studio.

### LINKED ISSUE #561: Bug: Visual Studo
### Describe the bug

After generating project files and opening the solution in visual studio, all the files are not in their respective folders

### Steps To Reproduce

Clone menu, generate project files, open solution 

### Expected Behavior

All files should be normal

### Screenshots and/or Logs

FF1C40EB-A049-4DED-9AC3-1ACEBE3103F8

### Store

Epic Games

### Additional context

Its forcing me to say i used it unmodified but i used tupoya's fork and just updated it to latest version of yimmenu

### Build

- [X] I used YimMenu unmodified

### PR DESCRIPTION
**Pull request by SpaghettDev**
Fixes #561

### CODE REVIEW

**Comment by tupoy-ya** [comment]
Shouldn't 
https://github.com/YimMenu/YimMenu/blob/138c65e8b0e3fbf358d2f10aa1acc834d18deda4/CMakeLists.txt#L35
already do this?

**Comment by SpaghettDev** [comment]
> Shouldn't
> 
> https://github.com/YimMenu/YimMenu/blob/138c65e8b0e3fbf358d2f10aa1acc834d18deda4/CMakeLists.txt#L35
> 
> already do this?

Not sure, when I tried building it with the original CMakeLists.txt, all the files were in one solution (YimMenu) (not being separated into different filters).

**Comment by SpaghettDev** [comment]
I'm not sure, because I'm just a beginner when it comes to CMake, but i think what you're referencing just adds all the files to the YimMenu solution, not making filters for each folder.

**Comment by tupoy-ya** [comment]
It does add filters (or it did when i last tested it).
This is what this line is for.

**Comment by SpaghettDev** [comment]
> It does add filters (or it did when i last tested it). This is what this line is for.

Well it no longer does so...

**Comment by xiaoxiao921** [comment]
In c++ i find the show all files checkbox being enabled much more bearable than the filters

**Comment by SpaghettDev** [comment]
> In c++ i find the show all files checkbox being enabled much more bearable than the filters

You prefer having all the files in one single place? Because that is what happens if I enable Show All Files...

**Comment by tupoy-ya** [comment]
Ok after some testing i fixed the problem by
```diff
-source_group(TREE "${SRC_DIR}" PREFIX "YimMenu" FILES "${SRC_MAIN}" ) 
+source_group(TREE ${SRC_DIR} PREFIX "src" FILES ${SRC_MAIN} )
```

**Review by tupoy-ya — APPROVED** [review]

**Comment by xiaoxiao921** [comment]
> > In c++ i find the show all files checkbox being enabled much more bearable than the filters
> 
> You prefer having all the files in one single place? Because that is what happens if I enable Show All Files...

The README is incorrect if you are using Visual Studio, the correct steps are:
git clone the repo
open visual studio, open a local folder, select the folder that just got added by the git command

**Comment by tupoy-ya** [comment]
> > > In c++ i find the show all files checkbox being enabled much more bearable than the filters
> > 
> > 
> > You prefer having all the files in one single place? Because that is what happens if I enable Show All Files...
> 
> The README is incorrect if you are using Visual Studio, the correct steps are: git clone the repo open visual studio, open a local folder, select the folder that just got added by the git command

That's if you installed a CMake extension.

The steps in README are universal and will only fail if you have MinGW installed on your windows system.

**Comment by xiaoxiao921** [comment]
> > > > In c++ i find the show all files checkbox being enabled much more bearable than the filters
> > > 
> > > 
> > > You prefer having all the files in one single place? Because that is what happens if I enable Show All Files...
> > 
> > 
> > The README is incorrect if you are using Visual Studio, the correct steps are: git clone the repo open visual studio, open a local folder, select the folder that just got added by the git command
> 
> That's if you installed a CMake extension.
> 
> The steps in README are universal and will only fail if you have MinGW installed on your windows system.

"Universal"

`&&` is used in the README and its not even valid in PS, i'm making a PR with a subsection only for Windows and one only for linux based OS

**Comment by tupoy-ya** [comment]
> `&&` is used in the README and its not even valid in PS.

I thought that if bash has `&&` and DOS(batch(cmd)) has `&&` then PowerShell should too. (I use bash on my windows VM so i didn't test)

**Pull request merged**
