### PR TITLE
Added crash objects to list

### PR DESCRIPTION
**Pull request by Vali0004**
Given to me by 41Baloo
```lua
local invalid_crash_objects <const> = {
    "proc_drygrasses01",
    "proc_drygrasses01b",
    "proc_brittlebush_01",
    "proc_forest_ivy_01",
    "proc_grassdandelion01",
    "proc_grasses01b",
    "proc_grassfronds01",
    "proc_grassplantmix_01",
    "proc_indian_pbrush_01",
    "proc_leafybush_01",
    "proc_lizardtail_01",
    "proc_lupins_01",
    "proc_meadowmix_01",
    "proc_meadowpoppy_01",
    "proc_desert_sage_01",
    "prop_saplin_001_b",
    --[["prop_fernba", -- known
    "h4_prop_bush_buddleia_low_01", -- known
    "h4_prop_bush_ear_aa", -- known
    "h4_prop_bush_ear_ab" -- known ]]
}
```

### CODE REVIEW

**Review by Yimura — DISMISSED** [review]
Has any testing been done to confirm if this creates false positives?

**Comment by holysnipz** [comment]
just nitpicking here, but remove the duplicated `"proc_dryplantsgrass_02"_J` as well? there are 2 of them 😅

**Comment by gir489returns** [comment]
Knowing the author's history, this was probably copypasted from the same source as #2857 which I had to revert, see #2921.

**Comment by Vali0004** [comment]
> Knowing the author's history, this was probably copypasted from the same source as #2857 which I had to revert, see #2921.

Just given to me by Baloo (stand staff), and it crashed yim. I didn't do much testing, but I know for a fact none of these assets in the game cause conflicts with missions or regular gameplay, and just trigger a crash. I do believe there might be duplicates because of how the object list was structured. I'll look it over again.
EDIT: Object list is fine, and none of #2857's objects are in that list.

**Comment by Vali0004** [comment]
> just nitpicking here, but remove the duplicated `"proc_dryplantsgrass_02"_J` as well? there are 2 of them 😅

That was not from my commit, but I will change it regardless.
I accidentally pushed a empty commit due to my lackluster knowledge of how the VSC Git plugin works.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
