### PR TITLE
Fix fake ban message

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Rxann** [comment]
Nice

**Review by Rxann — COMMENTED** [review]
Very subtle change. Looks good.

**Review by gir489returns — APPROVED** [review]

**Comment by gir489returns** [comment]
```cpp
union Args {
	struct
	{
		int64_t event;
		int64_t id;
		int64_t playerId;
	};
	char message[15]; // if (HUD::GET_LENGTH_OF_LITERAL_STRING_IN_BYTES(sParam1) > 15) return;
};

const size_t arg_count = 9;
Args args = {(int64_t)eRemoteEvent::SendTextLabelSMS, self::id, 1 << player->id()};
std::string str        = "HUD_ROSBANPERM";
std::copy(str.begin(), str.end(), args.message);

g_pointers->m_gta.m_trigger_script_event(1, (int64_t*)&args, arg_count, 1 << player->id(), (int)eRemoteEvent::SendTextLabelSMS);
```

We can also do it this way.

**Comment by gir489returns** [comment]
image

This feautre doesn't work the way it used to. I guess they patched it? Before, it used to open a dialog window saying you were banned. Now it just does this,... Not exactly gonna make them panic or anything. I think this feature should be removed.

**Comment by rkwapisz** [comment]
> image
> 
> This feautre doesn't work the way it used to. I guess they patched it? Before, it used to open a dialog window saying you were banned. Now it just does this,... Not exactly gonna make them panic or anything. I think this feature should be removed.

Agreed. Get rid of it. I wouldn't even blink at an in-game text like that.

**Comment by ghost** [comment]
We could create a checkbox and add a loop to it that would display a warning message `HUD::SET_WARNING_MESSAGE_WITH_HEADER_AND_SUBSTRING_FLAGS("WARN", "JL_INVITE_ND", 2, "", true, -1, -1, "You have been permanently banned from entering Grand Theft Auto Online Mode.", " Return to Grand Theft Auto V.", true, 0);` but I don't know how to do it, maybe someone else will create another PR.

**Comment by maybegreat48** [comment]
> it used to open a dialog window saying you were banned

It never did that to my knowledge

**Comment by gir489returns** [comment]
> > it used to open a dialog window saying you were banned
> 
> It never did that to my knowledge

The one I had did a while ago did. Must've gotten patched.

**Pull request merged**
