### PR TITLE
Extend spawn tab functionality

### PR DESCRIPTION
**Pull request by ThatKakiGuy**
Not ready yet, I'm still getting some compiler errors...

### CODE REVIEW

**Comment by ThatKakiGuy** [comment]
error

**Comment by ThatKakiGuy** [comment]
The second and third compiler error are my fault, idk how the first one happened

**Comment by Yimura** [comment]
Try regenerating the project solution by executing GenerateProject.bat

**Comment by Yimura** [comment]
Try to work on a clean fork of YimMenu if you can't get it to work.

**Comment by ThatKakiGuy** [comment]
Ok, regenerating the solution fixed the first one, the other two are still there, but thats my code.

**Comment by ThatKakiGuy** [comment]
Accessing `g.spawn.vehicle_id` seems to be causing the error messages..

**Comment by Yimura** [comment]
> Accessing `g.spawn.vehicle_id` seems to be causing the error messages..

Look into how you need to copy data into a char array, you can't just use `=`. Same with comparing them, you need to use strcmp and strcpy functions for those.

**Comment by ThatKakiGuy** [comment]
Oh... 🤦‍♂️ 
Still the same error messages, though.

**Comment by Yimura** [comment]
I will check it out at a later date, just taking some time away from the computer.

**Comment by ThatKakiGuy** [comment]
Ok, thanks

**Comment by ThatKakiGuy** [comment]
The layout is also kinda broken... Idk, I never worked with ImGui before 🤷‍♂️

**Comment by ThatKakiGuy** [comment]
Ok, my code is a mess, I didn't think and committed to master, instead of making an extra branch, which makes me unable to make any other PRs without these changes here. Will close this one for now, delete my fork, make a new one, fix everything and eventually open another one.

**Pull request closed without merging**
