### PR TITLE
Moved GTA data into the binary.

### PR DESCRIPTION
**Pull request by aa15032261**
Created an action to automatically update the data, which runs at 1pm UTC daily (1 hour prior to the nightly build).

### CODE REVIEW

**Comment by GeopJr** [comment]
Thanks for creating this PR!

I can't say much on the GTA side of things, but on the action side:

I believe it's impossible for it to commit directly to the repo due to the repo protections. Nobody can directly push to the repo. Everything has to be done through PRs and even then, they need to be approved by at least one org memeber before being allowed to be merged.

The PR is pretty big and quite opinionated so it might take the members responsible for reviewing it quite a while 😅

**Comment by aa15032261** [comment]
> Thanks for creating this PR!
> 
> I can't say much on the GTA side of things, but on the action side:
> 
> I believe it's impossible for it to commit directly to the repo due to the repo protections. Nobody can directly push to the repo. Everything has to be done through PRs and even then, they need to be approved by at least one org memeber before being allowed to be merged.
> 
> The PR is pretty big and quite opinionated so it might take the members responsible for reviewing it quite a while 😅

Totally forgot about the protection. I've modified the action to update the files in action branch, then create pull requests to the default branch. The branch will be deleted automatically after merging.

The only problem is we need to setup the branch protection for the action branch, allowing one user to force update and delete that branch. The action will then use the PAT (ACTION_KEY in the yml) of that user to do stuff.

**Comment by aa15032261** [comment]
Finalised.

**Comment by Yimura** [comment]
This PR will be closed when #457 is merged into master.

I explain in #446 why I no longer want to rely on DurtyFree's data.

**Comment by Yimura** [comment]
Closing as #457 has been merged into master.

**Pull request closed without merging**
