### PR TITLE
feat(Vehicle): Added keep engine running functionality when you leave…

### PR DESCRIPTION
**Pull request by Democles85**
Adding the requested functionality of keeping the engine running for the current vehicle.

### CODE REVIEW

**Review by Yimura — CHANGES_REQUESTED** [review]
Could you make this into a looped command? We're trying to step away from adding to looped scripts.

**Comment by Democles85** [comment]
> 

Could I not, you mean?

**Comment by Democles85** [comment]
> Could you make this into a looped command? We're trying to step away from adding to looped scripts.

Looped command... Can you please give me like an example of which function is a looped command? I only have a little experience when it comes to game modding and very little to YimMenu. :)

**Comment by Yimura** [comment]
Take a look at the disable_siren looped command for example:
https://github.com/YimMenu/YimMenu/blob/6aa713c831b65a044bbc4561356dfc57674bea9b/src/backend/looped/vehicle/disable_siren.cpp#L1-L29

There's an `on_tick()` function which is basically where you put your code that you would otherwise loop.
Then there's also `on_disable()` which gets ran when the feature gets disabled so you can do the proper cleanup if needed.
If you need to do some one time setup in a looped command you can also use `on_enable()` for that.

**Comment by Democles85** [comment]
> Take a look at the disable_siren looped command for example:
> 
> https://github.com/YimMenu/YimMenu/blob/6aa713c831b65a044bbc4561356dfc57674bea9b/src/backend/looped/vehicle/disable_siren.cpp#L1-L29
> 
> There's an `on_tick()` function which is basically where you put your code that you would otherwise loop. Then there's also `on_disable()` which gets ran when the feature gets disabled so you can do the proper cleanup if needed. If you need to do some one time setup in a looped command you can also use `on_enable()` for that.

Okay thank you! 🤗

**Comment by Yimura** [comment]
No need to close the PR, you can keep pushing changes here.

Edit:
Any changes you made won't be visible either as we squash everything before it's merged into master.

**Comment by Democles85** [comment]
It closed since I merged mine with yours here, for the CI... oops

**Pull request closed without merging**
