### PR TITLE
feat: stat editor

### PR DESCRIPTION
**Pull request by Aure7138**

### CODE REVIEW

**Comment by yasmasdas** [comment]
Maybe a danger warning would be nice? some stats are honeypot stats or heavilly monitored

**Comment by Aure7138** [comment]
> Maybe a danger warning would be nice? some stats are honeypot stats or heavilly monitored

Yes, it's dangerous to cap it more than it should, my knowledge about stat is only from https://www.unknowncheats.me/forum/grand-theft-auto-v/461672-gtahax-1-64-external-thread-3-a.html, I don't know how to implement your idea, maybe I should add "Be aware of stat limits..."

**Comment by Aure7138** [comment]
> > 
> 
> Yes, it's dangerous to cap it more than it should, my knowledge about stat is only from https://www.unknowncheats.me/forum/grand-theft-auto-v/461672-gtahax-1-64-external-thread-3-a.html, I don't know how to implement your idea, maybe I should add "Be aware of stat limits..."

**Comment by yasmasdas** [comment]
There are multiple stats which are known to get people banned but I just mean like maybe a label above it saying that you should be aware that there is a risk with some setting stats and that it should be used with caution that should be enough. Something along those lines

**Review by Yimura — APPROVED** [review]

**Pull request merged**
