### PR TITLE
Kick host during join

### PR DESCRIPTION
**Pull request by ghost**
I don't know why you removed this useful feature. I suggest bringing it back.

anim

### CODE REVIEW

**Review by Yimura — DISMISSED** [review]

**Comment by snowleopardd** [comment]
Does this check if the host is a detected modder and is spoofing their token?
otherwise this will lead to us getting into a lot of databases + kicked + blocked, these simple checks should be a must tbh

**Comment by ghost** [comment]
> Does this check if the host is a detected modder and is spoofing their token? otherwise this will lead to us getting into a lot of databases + kicked + blocked, these simple checks should be a must tbh

why do we need to check the host to see if he is a modder or what? don't kick the host? if he is a modder, then we won't last more than a minute in the session, and it will have to be changed anyway.

**Comment by snowleopardd** [comment]
> > Does this check if the host is a detected modder and is spoofing their token? otherwise this will lead to us getting into a lot of databases + kicked + blocked, these simple checks should be a must tbh
> 
> why do we need to check the host to see if he is a modder or what? don't kick the host? if he is a modder, then we won't last more than a minute in the session, and it will have to be changed anyway.

Thats it, there's no need and is 100% useless to try to kick a host token spoofer if we will end up getting kicked and permanently blocked by these guys, we got the tools and built-in detections to prevent that, why not?

**Comment by ghost** [comment]
> Thats it, there's no need and is 100% useless to try to kick a host token spoofer if we will end up getting kicked and permanently blocked by these guys, we got the tools and built-in detections to prevent that, why not?

I still don't understand what you want

**Comment by snowleopardd** [comment]
> > Thats it, there's no need and is 100% useless to try to kick a host token spoofer if we will end up getting kicked and permanently blocked by these guys, we got the tools and built-in detections to prevent that, why not?
> 
> I still don't understand what you want

I'm just suggesting adding a check to prevent automatically kicking host token spoofers who are already host, the less we are in their databases, the better, no?, also what if the spoofer is a good guy but we trigger their reactions and get permanently blocked from their sessions?, there's nothing we can lose from adding this logic and it helps a lot...

**Comment by ghost** [comment]
> I'm just suggesting adding a check to prevent automatically kicking host token spoofers who are already host, the less we are in their databases, the better, no?, also what if the spoofer is a good guy but we trigger their reactions and get permanently blocked from their sessions?, there's nothing we can lose from adding this logic and it helps a lot...

Dude, we'll end up in their database anyway because we'll spoof the token too. If we were able to find out that the host is a cheater, we'll add him to the database and won't connect to his session anymore. Even if we don't know this host but he blocked our connection during matchmaking, matchmaking will connect us to the next session in the queue without a banner.

**Comment by snowleopardd** [comment]
> > I'm just suggesting adding a check to prevent automatically kicking host token spoofers who are already host, the less we are in their databases, the better, no?, also what if the spoofer is a good guy but we trigger their reactions and get permanently blocked from their sessions?, there's nothing we can lose from adding this logic and it helps a lot...
> 
> Dude, we'll end up in their database anyway because we'll spoof the token too. If we were able to find out that the host is a cheater, we'll add him to the database and won't connect to his session anymore. Even if we don't know this host but he blocked our connection during matchmaking, matchmaking will connect us to the next session in the queue without a banner.

I was explicitly referring to getting permanently blocked by them or getting kicked which is stupid because we can prevent that easily (if spoofer and host = don't try kick), i see that you don't care about getting kicked and blocked and just move on to a next session, but I'd prefer not, we have different views it's your PR, if you don't want to add it its okay 👍

**Comment by ghost** [comment]
> I was explicitly referring to getting permanently blocked by them or getting kicked which is stupid because we can prevent that easily (if spoofer and host = don't try kick), i see that you don't care about getting kicked and blocked and just move on to a next session, but I'd prefer not, we have different views it's your PR, if you don't want to add it its okay 👍

It's definitely better to be kicked immediately and join the next session than to play in a session with a host modder and be kicked for anything at any time (friendly modders is a good joke), especially since we can't determine whether the host is a modder or not, maybe he didn't even spoof the token and filled the solo session earlier with a multiplexer.

**Comment by Yimura** [comment]
Personally @mikedrugs and @CringeArab are making fairly good arguments. I think there's still room for improvement, perhaps we can offer additional options to users to either always try to kick the host regardless of what kind of protections and spoofing they may have applied or alternatively try not to kick the host if they're token spoofing (they likely are running a mod menu and in superior position making it unlikely we can kick them).

**Comment by CypherMorgan** [comment]
> Personally @mikedrugs and @CringeArab are making fairly good arguments. I think there's still room for improvement, perhaps we can offer additional options to users to either always try to kick the host regardless of what kind of protections and spoofing they may have applied or alternatively try not to kick the host if they're token spoofing (they likely are running a mod menu and in superior position making it unlikely we can kick them).

An option for a user to select if they want to kick the host if they're a modder can be added imo. This would satisfy the needs of both type of users, who always want to try to kick the host no matter if they're modder or not and the ones who just wanna kick non-modders.

Edit: It just got added the same minute I commented this, my bad.

**Review by snowleopardd — COMMENTED** [review]
Nicee, gj

**Review by gir489returns — APPROVED** [review]
image

Looks good to me.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
