### PR TITLE
Colors to main players + add friends to db

### PR DESCRIPTION
**Pull request by binded-zz**
colors ideas likely to  change but it works 
as of now test 

admin i have no idea its default 
friends  - green or blue friend icon for plays in data base
modder - orange
blocked - red notfriend icon

this adds friends in to the db non-rock* adds color to players lists and also friend icon

is_friends  is used because is_friend is already a function but that is for R* friends 
 trying to add more just a lil lost but this works

### CODE REVIEW

**Comment by xiaoxiao921** [comment]
Looks like you reverted #1313 for no reason

**Comment by binded-zz** [comment]
wow LOL i spent so much time doing mine i never rechecked to see if there was new ones 
i knew the stuff i did was small but looks like mine is a major nerf

i dont think its a nerf looking at what he changed this now still mostly adds and expends

**Comment by xiaoxiao921** [comment]
if you were actually using git instead of doing it through the web interface u would've been hit with a normal merge conflict and you could have fixed it easily with a merge editor like the one vscode ship with

**Comment by binded-zz** [comment]
but none the less i do beleave that i still relates 

when i get home from work i will update and then add try  to fix it to work with the new info 
and im still learning i was not expecting such small changes to take so much learning

**Comment by binded-zz** [comment]
i dont think i added all the stuff i changed i need to relook at this

**Comment by Rxann** [comment]
you should merge master into your branch to see the new code yimura created

**Pull request closed without merging**
