### PR TITLE
feat(Teleport): Teleport to objective

### PR DESCRIPTION
**Pull request by ThatKakiGuy**
It works now 🎉

### CODE REVIEW

**Comment by Yimura** [comment]
Nice will take a look later on my computer.

**Review by Yimura — CHANGES_REQUESTED** [review]
The button is still called waypoint.

Watch out with teleport to blip because it disregards the Z coordinate (height) and calculates its own based on ground coordinates.

Maybe make some kind of for loop with all the blip ID's instead of hardcoding them.

Also if one of the functions returns true exit the for loop this will prevent the others from executing and creating unnecessary calls.

**Comment by ThatKakiGuy** [comment]
oh, right, I just copied the code from the waypoint button.

**Comment by ThatKakiGuy** [comment]
fixed

**Review by Yimura — CHANGES_REQUESTED** [review]
Looks much better.

Only could you use a static variable or static const and an int array instead of a vector. You don't need a dynamic array.

```cpp
static const int blips[] = { 1, 57, ... };
```

Aside from that I've got no complaints.

**Comment by ThatKakiGuy** [comment]
Fixed :D

**Comment by Yimura** [comment]
Ok now just remove the include for vector and you're good.

**Comment by Yimura** [comment]
Perfect! I will merge it in master now.

**Pull request merged**
