### PR TITLE
Lua Scripting

### LINKED ISSUE #83: Add a Lua scripting API
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to load Lua files

**Provide Reasoning**
It would be cool to make some Scripts.

**Additional context**

### LINKED ISSUE #1129: [Bug]: set bounty not work
### Describe the bug

set bounty not work

### Steps To Reproduce

set bounty not work

### Expected Behavior

work

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1287: [Bug]: Override local time makes the world flicker
### Describe the bug

When enabling Local time override (under World -> Time and Weather -> Local Time -> Override local time) it makes the world (ground) flicker.

### Steps To Reproduce

1. Enable Local Time under World
2. Enable Override Time
3. Set the time to 12 hours or so for the best effect
4. For better effect get into a flying vehicle and fly around

### Expected Behavior

For the world to not flicker

### Screenshots and/or Logs

_No response_

### Store

Rockstar

### Additional context

It might have something to do with graphics settings if you don't get the same effect as I did.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1309: [Bug]: Bring Player
### Describe the bug

When you bring a player to your location (using bring player feature), the menu will keep bringing that person on the same spot multiple times after different time gaps.

### Steps To Reproduce

1. Go to any session with your friend or any player.
2. Bring that person to your place/location and once that person is there.
3. Now go to different place or stay there and wait for a while.
4. The player will be automatically Tp-ed to that spot again.

### Expected Behavior

The player doesn't get tp-ed multiple times.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by maybegreat48**
This is going to be a draft PR for quite some time, so feel free to suggest improvements to the API or the framework in general

Known issues:
* Script patches do not unload properly
* Build times are slower now due to the natives file

I've also added a tunable service, and a button that teleports all players to your position, even if they are on foot

Closes #83
Fixes #1309 
Fixes #1287 
Fixes #1129 (actually fixed now)

### CODE REVIEW

**Comment by xiaoxiao921** [comment]
Didn't read it all yet but I like the fact that we use sol and how it handles pointers for natives, which is something I didn't even get working and neither fiveM did for their Lua api lol.

Small nitpick but I imagine there is a small perf cost with how the natives are declared. I imagine it's a bit better if it was a single pass to C land instead of the current begin_call, push args etc but it seems pretty solid nonetheless

**Comment by maybegreat48** [comment]
> neither fiveM did for their Lua api lol

They intentionally chose not to due to security reasons

Will rewrite the invoker when I have time

**Comment by xiaoxiao921** [comment]
Posting this in there just in case you are interested, since this pr contains the can_apply_data node patch for trains with invalid track id

Apparently the crash still happens in a 2 player session (you and the crasher basically), atleast thats what the people here are saying https://github.com/YimMenu/YimMenu/issues/1355

Somehow there seems to be a code path where train are still getting created with invalid track id, in lumen the two functions that are problematic are `CTrain::_CrashFunc` and `CTrain::GetPosition`

`CTrain::_CrashFunc` is getting patched by https://github.com/YimMenu/YimMenu/pull/1288

`CTrain::GetPosition` is at `48 89 5C 24 08 57 48 83 EC 20 48 63 02`
and the fix is apparently

```cpp
if (trackId /*a4*/ >= 27 || trackId /*a4*/ < 0)
  return;

if (!a2 || !a3 || !a7)
  return;

return original(...);
```

**Comment by maybegreat48** [comment]
I'd like to filter invalid values rather than band-aid affected functions, but it remains an option if all else fails. I have asked the reporter for more info (since they could test with Stand)

**Comment by takoyakiwhite** [comment]
> Posting this in there just in case you are interested, since this pr contains the can_apply_data node patch for trains with invalid track id
> 
> Apparently the crash still happens in a 2 player session (you and the crasher basically), atleast thats what the people here are saying #1355
> 
> Somehow there seems to be a code path where train are still getting created with invalid track id, in lumen the two functions that are problematic are `CTrain::_CrashFunc` and `CTrain::GetPosition`
> 
> `CTrain::_CrashFunc` is getting patched by #1288
> 
> `CTrain::GetPosition` is at `48 89 5C 24 08 57 48 83 EC 20 48 63 02` and the fix is apparently
> 
> ```c++
> if (trackId /*a4*/ >= 27 || trackId /*a4*/ < 0)
>   return;
> 
> if (!a2 || !a3 || !a7)
>   return;
> 
> return original(...);
> ```

If you are host, still got crash.

**Review by Yimura — DISMISSED** [review]
Can be merged after the merge conflicts have been merged.

**Review by Yimura — APPROVED** [review]
Waiting for translations to propagate before merging

**Pull request merged**
