### PR TITLE
Add .pdb file to ci workflow

### PR DESCRIPTION
**Pull request by pierrelasse**
This allows the download of the .pdb file from pull requests.

### CODE REVIEW

**Comment by gir489returns** [comment]
Duplicate of #2818?

**Comment by xiaoxiao921** [comment]
Not duplicate, but I'd rather have the github bot comment being modified instead with two links, one with just the binary.zip and one with binary_and_pdb.zip. Is that possible with the github action?

**Comment by gir489returns** [comment]
Why not just upload one zip for the DLL and one zip for the PDB?

**Comment by pierrelasse** [comment]
Why zip the files individually? Not that they're a few GB.

**Comment by xiaoxiao921** [comment]
Because I don't want to download the pdb if I don't want it, simple as that.

**Comment by Yimura** [comment]
Yeah that's what I was expecting, the build isn't even creating a PDB to begin with.

**Comment by xiaoxiao921** [comment]
For finishing this PR, do the following change:
```
      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D OPTIMIZE=YES -S. -Bbuild -G Ninja

      - name: Build 64bit release DLL
        run: cmake --build ./build --config RelWithDebInfo --target YimMenu --
```
       
and

```
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dll
          path: |
              path_to_dll
``` 

```
      - name: Upload PDB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdb
          path: |
            path_to_pdb
```

**Comment by Yimura** [comment]
Indeed for CI we don't really need a Release build as it's really just meant for debugging.

Though I do agree with @xiaoxiao921's comment on separating the two as users/tests don't necessarily need the pdb file.

**Comment by xiaoxiao921** [comment]
The fact that the comment bot use Release instead of RelWithDebInfo is more of a bug than anything. the nighlty already use RelWithDebInfo so that the pdb is generated inside the artifact.

**Comment by pierrelasse** [comment]
Please feel free everyone to edit the workflow to put it into two separate zips or close this PR.

**Comment by gir489returns** [comment]
We're not going to do your work for you.

**Comment by xiaoxiao921** [comment]
Pretty sure what I gave can be copy pasted and it'll work

**Pull request closed without merging**
