### PR TITLE
fix "sync fuzzer" crash

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Very much like https://github.com/YimMenu/YimMenu/pull/610 :
- This is untested
- we need to fix g3log crashing the game

### CODE REVIEW

**Review by Yimura — APPROVED** [review]

**Comment by Aure7138** [comment]
I think the pr name should be to prevent the sync fuzzer from crashing from the menu, whether it can prevent the sync fuzzer is unknown

**Comment by pelecanidae** [comment]
Fighting "fuzzer crashes" is going to be an uphill battle. They're no different from any other crashes in that they all violate parser invariants, but fuzzers make finding the low-hanging fruits very easy. A good way to convince yourself of this is to hook `receive_net_message` and flip random bits -- things go wrong very quickly. 

I think there are a few paths forward here:
- Continue to take piecemeal measures against specific crash sites like we already do (easy but doesn't scale well)
- Re-implement the entire networking stack as a way to "vet" packets (large initial time investment + continuous changes needed with game updates)
- Sandbox the parsers as much as possible so that crashes don't bring down the entire process (not too hard with sync trees, I'm not sure how well that scales to the rest of the parsers however)

**Comment by xiaoxiao921** [comment]
the only viable path for us because we are not being paid unlike p2c devs is that we work a bit to publish a packet fuzzer, it'll be such a big clown fiesta that r* will be forced to finally fix their trash code

**Comment by maybegreat48** [comment]
Node security audit (read from bitbuf part):
CAutomobileCreationDataNode - Nothing special
CBikeGameStateDataNode - Just reads a bool
CBoatGameStateDataNode - Nothing special
CDoorCreationDataNode - Nothing special
CDoorMovementDataNode - Nothing special
CDoorScriptGameStateDataNode - ^
CDoorScriptInfoDataNode ^
CDynamicEntityGameStateDataNode - PATCHED
CEntityOrientationDataNode - Nothing special
CEntityScriptGameStateDataNode - ^
CEntityScriptInfoDataNode ^
CGlobalFlagsDataNode - ^
CHeliControlDataNode - ^
CHeliHealthDataNode - ^
CMigrationDataNode - ^
CObjectCreationDataNode - ^
CObjectGameStateDataNode - ARRAY READ OVERFLOW!!!
CObjectOrientationNode - Nothing special
CObjectScriptGameStateDataNode - ^
CObjectSectorPosNode - Does some shady size stuff but I doubt there is a overflow
CPedAIDataNode - Nothing special
CPedAppearanceDataNode - ^
CPedAttachDataNode - ^
CPedComponentReservationDataNode - Very unsafe array length retrieval but doubt it can overflow due to bitcount
CPedCreationDataNode - Nothing special
CPedGameStateDataNode - MULTIPLE OUT OF BOUNDS ARRAY READS!!!
CPedHealthDataNode - Nothing special
CPedInventoryDataNode - MULTIPLE OUT OF BOUNDS ARRAY READS!!!
CPedMovementDataNode - Nothing special
CPedMovementGroupDataNode - ^ (but needs more research)
CPedOrientationDataNode - ^
CPedScriptCreationDataNode - ^
CPedScriptGameStateDataNode - ^ (but does really complex stuff, needs more research)
CPedSectorPosMapNode - ^
CPedSectorPosNavMeshNode - ^
CPedTaskSequenceDataNode - ^ (array length access guarded)
CPedTaskSpecificDataNode - ARRAY READ OVERFLOW!!!
CPedTaskTreeDataNode - Nothing special
CPhysicalAngVelocityDataNode - ^
CPhysicalAttachDataNode - ^
CPhysicalGameStateDataNode - ^
CPhysicalHealthDataNode - ^
CPhysicalMigrationDataNode - ^
CPhysicalScriptGameStateDataNode - ^
CPhysicalScriptMigrationDataNode - ^
CPhysicalVelocityDataNode - ^
CPickupCreationDataNode - OUT OF BOUNDS ARRAY READ!!!
CPickupPlacementCreationDataNode - Nothing special
CPickupPlacementStateDataNode - ^
CPickupScriptGameStateNode - ^
CPickupSectorPosNode - ^
CPlaneControlDataNode - ^
CPlaneGameStateDataNode - ^
CPlayerAmbientModelStreamingNode - ^
CPlayerAppearanceDataNode - Does way too much things for me to audit this one, needs more research
CPlayerCameraDataNode - Nothing special
CPlayerCreationDataNode - ^
CPlayerExtendedGameStateNode - ^
CPlayerGamerDataNode - ^
CPlayerPedGroupDataNode - ^
CPlayerSectorPosNode - ^
CPlayerWantedAndLOSDataNode - ^
CSectorDataNode - ^
CSectorPositionDataNode - ^
CSubmarineControlDataNode - ^
CSubmarineGameStateDataNode - ^
CTrainGameStateDataNode - ^
CVehicleAngVelocityDataNode - ^
CVehicleAppearanceDataNode - ^
CVehicleComponentReservationDataNode - Very unsafe array length retrieval but doubt it can overflow due to bitcount
CVehicleControlDataNode - OUT OF BOUNDS ARRAY READ!!!
CVehicleCreationDataNode - Nothing special
CVehicleDamageStatusDataNode - ^
CVehicleGadgetDataNode - OUT OF BOUNDS ARRAY READ!!!
CVehicleGameStateDataNode - Nothing special
CVehicleHealthDataNode - MULTIPLE OUT OF BOUNDS ARRAY READS!!!
CVehicleProximityMigrationDataNode - UNDEFINED BEHAVIOR + OUT OF BOUNDS ARRAY READ!!!
CVehicleScriptGameStateDataNode - Nothing special
CVehicleSteeringDataNode - ^
CVehicleTaskDataNode - Very unsafe array read but doubt it can overflow due to bitcount
Turns out there are only 100 task serializers so decided to take a look at them
CClonedControlVehicleInfo - Very unsafe array read but doubt it can overflow due to bitcount
CClonedTaskMoVEScriptedInfo - MULTIPLE OUT OF BOUNDS ARRAY READS!!!
The rest are probably not vulnerable

Fixing the out of bounds write and the array reads is the proper fix for this crash. Note to Rockstar: All these crashes can also be used as RCEs by hackers

**Comment by ghost** [comment]
I think one of the only ways to solve the issue here would be to fight fire with fire. Let's figure out how to send some of these nodes and write a mini fuzzer ourselves, as we discover more and more crashes we can fix them. 

The crashes are out there, the game already is an unplayable mess.

I have a background in coverage guided testing, given how little these functions are protected we could build something really nice here.

@maybegreat48 how did you find the functions responsible for handling each node by the way?

**Comment by maybegreat48** [comment]
You can find them through classinformer by searching for ICommonDataOperations

**Comment by iwanttodo1t** [comment]
Why not merge this PR

**Comment by Yimura** [comment]
> Why not merge this PR

Because of how we currently log crashes in YimMenu it is not possible to merge this code into master as a fix.
We can catch the crash but the logger still ends up killing the game.

Eventually we'd best step over to our own implementation of an async logger and handle exceptions separately.

**Pull request closed without merging**
