### PR TITLE
Huge protection improvements and other stuff

### LINKED ISSUE #972: [Bug]: teleport to wrong place while the waypoint is on water
### Describe the bug

character will be moved to the bottom of the sea when trying to teleport into water, and I have to use noclip to go back to the surface

it will always teleport to the surface in the past (before 1.66)

### Steps To Reproduce

put the waypoint on the sea and use "teleport to waypoint"

### Expected Behavior

i think teleport to the surface of the water is more convenient( •̀ ω •́ )✧

### Screenshots and/or Logs

_No response_

### Store

Epic Games

### Additional context

_No response_

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1666: [Bug]: crash during block join
### Describe the bug

I get a crash when I connect to the same player. Is there some new way to crash, or is it a problem with the last commit?
P.S. I am connecting to a person who has a block join checkbox in my database. It turns out he kicks desynchronously and after that he tries to connect to me when I'm the host and in most cases I see a notification that the player is blocked from joining the session, but immediately my game crashes without a dump. Perhaps this could also be the reason

### Steps To Reproduce

1. Join a session
2. Get crash after +- 10 seconds

### Expected Behavior

I shouldn't crash

### Screenshots and/or Logs

[log.txt](https://github.com/YimMenu/YimMenu/files/12000562/log.txt)

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1754: [Request]: Feature to clear persistent spawned garbage by other players
### Problem

Some players have the ability to spawn persistent props or vehicles. These items persist between sessions, even into missions with other players that weren't present at the time the spawned garbage was added. 

### Solution

Ability to manually clear everything on a needed basis. 

### Reason

Only way I've been able to clear this persistent spawned garbage is with a restart of the game. 

### Additional context

_No response_

### LINKED ISSUE #1906: [Bug]: multiple actions bound to single hotkey doesn't work
### Describe the bug

i would like to have 'Fill Snacks', 'Repair PV' and 'Fill Ammo' bound to one key and if i do it, none of these actions work

### Steps To Reproduce

1. hotkeys -> set >=2 actions to one keybind
2. try to press the keybind

### Expected Behavior

run all of them

### Logs and/or screenshots

none

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1909: [Bug]: Please remove options to install HSW mods
### Describe the bug

Yimmenu grants user the ability to install HSW vehicle mods, both through LS Customs options and through the "max vehicle" button. This triggers an "invalid vehicle mod" crash for surrounding players. 

### Steps To Reproduce

1. Enter one of HSW vehicles (list available here: https://gta.fandom.com/wiki/Hao%27s_Special_Works )
2. a. Mod it with HSW mods 
2. b. Or press "max vehicle"
3. HSW mods are installed on vehicle, triggering "invalid vehicle mod" crash for nearby players

### Expected Behavior

Not crashing other players. 

### Logs and/or screenshots

yimmenu_spawning_hsw_vehicle_mods

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1920: [Bug]: OG Heists issues when "Spoof Player Model" is enabled
### Describe the bug

Fleeca job: It starts, but the last mission, where you must drive the Armored Kuruma to the bank, if I (yimmenu user) get into the car before the driver, the driver is unable to drive until I leave the car. After he moves the car a little bit, it goes through and mission can be finished.

Other heists:
So far, I couldn't get past the drawing board phase. I only joined already active heists, and never hosted one.
Either it's the initial drawing board where you're supposed to select one of the preps, or the final drawing board where cuts and roles are selected.

In either case, it's like everybody's AFK, nobody readys up, nobody changes roles, and the "Continue" timer on the bottom right corner is 0:00 since the beginning. Nobody answers the chat either.

I've tried disabling protections, reactions and whatnot. Restarting the game without YimMenu, the heists are possible to start 

### Steps To Reproduce

What I do:

1. Join a heist (On a Call)
2. Wait until lobby fills up
3. If Fleeca Job, it goes through. Just don't enter the Kuruma on the last mission before the driver.
4. If any other mission, whenever it gets on the drawing board, it's like everybody's AFK and not responding.

### Expected Behavior

Play the heists.

### Logs and/or screenshots

```
names edited to prevent identification

[00:28:00.2501169][INFO/main.cpp:65] Yim's Menu Initializing
[00:28:00.2501412][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	c2d91c11aa5ae86db596cbaa9d50754332e870d3
	Date:	Fri Aug 4 23:19:39 2023
[00:28:00.2501551][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[00:28:00.2508249][INFO/main.cpp:69] Thread pool initialized.
[00:28:00.2588553][INFO/settings.cpp:79] Updating settings.
[00:28:00.2613345][INFO/main.cpp:72] Settings Loaded.
[00:28:00.2613420][DEBUG/thread_pool.cpp:95] Thread 24504 executing settings.cpp:18
[00:28:00.2647767][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[00:28:00.2647975][INFO/pointers.cpp:1548] Loading pointers instance from cache
[00:28:00.2647990][INFO/pointers.cpp:1557] Pointers cache: Loading 181 fields from the cache
[00:28:00.2648084][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[00:28:00.2682610][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[00:28:00.2682712][INFO/pointers.cpp:1548] Loading pointers instance from cache
[00:28:00.2682731][INFO/pointers.cpp:1557] Pointers cache: Loading 5 fields from the cache
[00:28:00.2683034][INFO/main.cpp:75] Pointers initialized.
[00:28:00.2684127][INFO/main.cpp:78] Byte Patch Manager initialized.
[00:28:00.7679668][INFO/main.cpp:81] Renderer initialized.
[00:28:00.9810132][INFO/main.cpp:85] Fiber pool initialized.
[00:28:01.4866894][INFO/main.cpp:88] Translation Service initialized.
[00:28:01.5060900][INFO/main.cpp:91] Hooking initialized.
[00:28:01.5233490][DEBUG/gta_data_service.cpp:162] Loading data from cache.
[00:28:01.5233580][INFO/gta_data_service.cpp:174] Loading 1029 peds from cache.
[00:28:01.5236546][INFO/gta_data_service.cpp:192] Loading 815 vehicles from cache.
[00:28:01.5238805][INFO/gta_data_service.cpp:209] Loading 117 weapons from cache.
[00:28:01.5238851][INFO/gta_data_service.cpp:210] Loading 378 weapon components from cache.
[00:28:01.5238950][DEBUG/gta_data_service.cpp:168] Loaded all data from cache.
[00:28:01.6338651][INFO/tunables_service.cpp:21] Loading tunables from cache
[00:28:01.6339001][INFO/main.cpp:111] Registered service instances...
[00:28:01.6338948][DEBUG/thread_pool.cpp:95] Thread 22856 executing tunables_service.cpp:24
[00:28:01.6340089][INFO/main.cpp:132] Scripts registered.
[00:28:01.6905304][INFO/main.cpp:135] Hooking enabled.
[00:28:01.6921547][INFO/main.cpp:138] Dynamic native hooker initialized.
[00:28:01.7013360][INFO/lua_module.cpp:226] Loaded CasinoPacino.lua
[00:28:01.7013987][INFO/main.cpp:141] Lua manager initialized.
[00:28:01.7014197][DEBUG/thread_pool.cpp:95] Thread 28164 executing player_database_service.cpp:276
[00:28:01.7781003][INFO/backend.cpp:51] Starting script: Self
[00:28:01.7781106][INFO/backend.cpp:76] Starting script: Weapons
[00:28:01.7781236][INFO/backend.cpp:99] Starting script: Vehicles
[00:28:01.7781274][INFO/backend.cpp:115] Starting script: Miscellaneous
[00:28:01.7781337][INFO/backend.cpp:135] Starting script: Remote
[00:28:01.7781469][INFO/backend.cpp:150] Starting script: Ls customs
[00:28:01.7781488][INFO/backend.cpp:162] Starting script: Rainbow paint
[00:28:01.7781509][INFO/backend.cpp:174] Starting script: Disable Control Action
[00:28:01.7781531][INFO/backend.cpp:187] Starting script: World
[00:28:45.6324523][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:28:48.4420788][DEBUG/thread_pool.cpp:95] Thread 22856 executing view_settings.cpp:54
[00:29:04.3022046][DEBUG/thread_pool.cpp:95] Thread 22856 executing view_settings.cpp:54
[00:29:08.5294258][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:29:08.5309556][INFO/translation_service.cpp:158] Translations for 'zh_TW' does not exist, downloading from https://raw.githubusercontent.com/GTMoraes/Translations/master
[00:29:11.9000006][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:29:11.9016064][INFO/translation_service.cpp:158] Translations for 'zh_CN' does not exist, downloading from https://raw.githubusercontent.com/GTMoraes/Translations/master
[00:29:14.5079745][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:29:17.8066681][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:29:33.8253268][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:30:43.0581950][DEBUG/thread_pool.cpp:95] Thread 22856 executing view_settings.cpp:54
[00:30:45.5439098][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:30:47.1600231][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:30:58.5187634][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:30:59.7997505][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[00:34:16.4233749][WARN/animations.hpp:94] Animations file is not in directory. https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/animDictsCompact.json
[00:38:33.3090963][WARN/animations.hpp:94] Animations file is not in directory. https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/animDictsCompact.json
[00:41:12.8787511][WARN/animations.hpp:94] Animations file is not in directory. https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/animDictsCompact.json
[00:41:24.2105554][DEBUG/thread_pool.cpp:95] Thread 26476 executing animations.hpp:103
[00:42:03.3477915][WARN/reaction.cpp:25] Received Modder Detection from XXXXXXXXX (000000000000)
[00:42:29.9564606][WARN/animations.hpp:87] Anim list already contained data, overwriting...
[00:42:29.9913674][DEBUG/thread_pool.cpp:95] Thread 26476 executing animations.hpp:103
[00:52:51.6518062][WARN/reaction.cpp:25] Received Send To Interior from XXXXXXXXX (000000000000)
[01:04:21.6028611][DEBUG/thread_pool.cpp:95] Thread 22856 executing translation_service.cpp:95
[01:04:34.4318819][WARN/reaction.cpp:25] Received Send To Interior from XXXXXXXXX (000000000000)
[01:12:50.7689591][WARN/reaction.cpp:25] Received Send To Interior from XXXXXXXXX (000000000000)
[01:41:08.8961809][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[02:01:35.5429652][INFO/main.cpp:152] Scripts unregistered.
[02:01:35.5453398][INFO/main.cpp:155] Lua manager uninitialized.
[02:01:35.6055284][INFO/main.cpp:158] Hooking disabled.
[02:01:35.6057183][INFO/main.cpp:161] Dynamic native hooker uninitialized.
[02:01:35.6057779][DEBUG/thread_pool.cpp:108] Thread 22856 exiting...
[02:01:35.6057847][DEBUG/thread_pool.cpp:108] Thread 26476 exiting...
[02:01:35.6812119][DEBUG/thread_pool.cpp:108] Thread 24504 exiting...
[02:01:36.3448475][DEBUG/thread_pool.cpp:108] Thread 28164 exiting...
[02:01:36.3453526][INFO/main.cpp:169] Destroyed thread pool.
[02:01:36.3453630][INFO/main.cpp:172] Script Connection Service reset.
[02:01:36.3467730][INFO/main.cpp:174] Tunables Service reset.
[02:01:36.3467828][INFO/main.cpp:176] Hotkey Service reset.
[02:01:36.3467860][INFO/main.cpp:178] Matchmaking Service reset.
[02:01:36.3469361][INFO/main.cpp:180] Player Database Service reset.
[02:01:36.3469413][INFO/main.cpp:182] API Service reset.
[02:01:36.3563455][INFO/main.cpp:184] Script Patcher Service reset.
[02:01:36.3563720][INFO/main.cpp:186] Gui Service reset.
[02:01:36.3578028][INFO/main.cpp:188] GTA Data Service reset.
[02:01:36.3578257][INFO/main.cpp:190] Vehicle Service reset.
[02:01:36.3578283][INFO/main.cpp:192] Model Preview Service reset.
[02:01:36.3578300][INFO/main.cpp:194] Mobile Service reset.
[02:01:36.3578368][INFO/main.cpp:196] Player Service reset.
[02:01:36.3578478][INFO/main.cpp:198] Pickup Service reset.
[02:01:36.3578513][INFO/main.cpp:200] Custom Text Service reset.
[02:01:36.3578871][INFO/main.cpp:202] Context Service reset.
[02:01:36.3578905][INFO/main.cpp:204] Xml Vehicles Service reset.
[02:01:36.3578921][INFO/main.cpp:205] Services uninitialized.
[02:01:36.3579245][INFO/main.cpp:208] Hooking uninitialized.
[02:01:36.3579323][INFO/main.cpp:211] Fiber pool uninitialized.
[02:01:36.3682447][INFO/main.cpp:214] Renderer uninitialized.
[02:01:36.3683798][INFO/main.cpp:217] Byte Patch Manager uninitialized.
[02:01:36.3683860][INFO/main.cpp:220] Pointers uninitialized.
[02:01:36.3683893][INFO/main.cpp:223] Thread pool uninitialized.
[02:01:36.3683905][INFO/main.cpp:225] Farewell!

```
ztjYrTd

### Store

Steam

### Additional context

running on my own fork build, updated to the bleeding edge. It's the base build + some still-not-merged changes for unlimited vehicle summon.
Should behave just like the latest base build, for all intents and purposes.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1931: [Bug]: Unable to start missions due to Spoof Player Model being enabled.
### Describe the bug

I'm unable to start some missions on freemode, such as the stash house missions. 
Whenever I try to start the mission, it says something like "Unable to start this mission. Try again soon".

It works if I'm playing solo, but it seems if I join a populated session, it doesn't work.
It also works if I unload YimMenu.

### Steps To Reproduce

1. Go to a stash house mission
2. Try to start mission
3. Fail to start mission
4. Unload YimMenu
5. Successfully start mission

### Expected Behavior

Missions should start without needing to unload YimMenu.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1932: [Bug]: Things get weird after using End Session Kick on someone
### Describe the bug

After I use End Session Kick on someone, I have what seems to be an enormous latency when doing stuff like registering as boss, entering a personal vehicle or sitting on the Nightclub PC chair.

When I use the register as boss, I see my blip change colors, but I don't see the banner until, like, 30 minutes in. 
Also, when I try to enter my PV, my player character hangs mid animation and stays there, moving his eyes and mouth, until I cancel the action (if I use the Vehicle submenu option to jump inside the car, the car doesn't start up until I also click on the menu button to start the vehicle)
Trying to sit on a PC chair (like on the nightclub or office's chair), the player just stands in there. I can still move the character around, but can't open the interaction menu until I exit the nightclub or office (or use the elevator)

### Steps To Reproduce

1. End Session Kick someone
2. Try to register as CEO/MC
3. Try to sit on a computer chair

You should experience the bug. If not, wait a bit before doing step 2 or 3.

### Expected Behavior

Normal game like when I use the Desync kick option (which I use now, instead of End Session kick)

### Logs and/or screenshots

```
no logs atm. I didn't know how to report bugs here before. I just remembered this bug because I saw a PR about using all available kick options for reaction, and thought that'd be a bad idea due to this End Session kick bug.
```

### Store

Steam

### Additional context

I've just personally just switched to Desync kick. 
I have no idea what's the difference between them, all I know is that after 10-20 seconds, a lame player leaves.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #1934: [Bug]: Spoofed model does not reset, now saved in settings
### Describe the bug

One of the newer builds now loads a spoofed player model from settings on launch and on session switch. It is a nice touch however combined with being unable to roll back the spoof this function becomes a pain in the arse. Let me provide an example.

I made myself a monkey to fool around in session missions and bring some variety to cutscenes. That's all fine and cool. Next day I launch the game, the menu loads, my friend tells me I'm still a monkey. Spoofing as "self" through the menu glitches the character out, makes be a male with no head texture or bald (I play as female with hair) and wrong clothes. The model rolled back to normal whenever the menu was NOT running, and would corrupt on menu load. I could not roll back to my character at all, the only thing that did the trick for me is to remove the settings json which basically reset everything.

Older versions apparently did not store this as switching sessions always reset the model back to normal. At this moment what's needed is either being able to restore the normal model/reset this function somehow, or let the game do it on sessions switch.

### Steps To Reproduce

1. Spoof model (any will do)
2. Switch sessions/relaunch game
3. Try to restore default player model
4. Fail

### Expected Behavior

Either as in previous versions, do not store spoofed model in settings, or be able to correctly restore the player model

### Logs and/or screenshots

_No response_

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by maybegreat48**
* Added a fuzzer to detect crashes
* Added all kinds of new protections
* Added some vehicle trolling options (currently not blocked by any menu)
* Added some misc stuff

Fixes #1934 
Fixes #1932 
Fixes #1909 
Fixes #1906 
Fixes #1666 
Fixes #972 
Closes #1931 (added a warning, fixing the underlying issue isn't possible)
Closes #1920 (see above)
Closes #1754

### CODE REVIEW

**Comment by gir489returns** [comment]
@maybegreat48 Why do you have this marked as draft? Code looks solid to me.

**Comment by maybegreat48** [comment]
> @maybegreat48 Why do you have this marked as draft? Code looks solid to me.

I'm thinking of adding more stuff to this

**Comment by gir489returns** [comment]
Just a thought, in your VMT class, you're not backing up index -1, which is usually used for RTTI. I know GTA stripped it, but it could still store something there, and if it's missing, the anti-cheat could see that and detect that a class has been hooked.

**Comment by maybegreat48** [comment]
> Just a thought, in your VMT class, you're not backing up index -1, which is usually used for RTTI. I know GTA stripped it, but it could still store something there

The RTTI isn't zeroed out, it doesn't exist at all (`-1` generally has something else in it)

> and if it's missing, the anti-cheat could see that and detect that a class has been hooked.

They'll just make Arxan integrity check or self-heal the vtable (see `MetricBENCHMARK_Q`)

**Comment by GTMoraes** [comment]
Small suggestion: As you added the warning in the "spoof player model" on Ped spawn, it'd make sense if the same warning were also on the "Spoofing" tab, on the "Spoof Player Model" button.

**Comment by TheGreenBandit** [comment]
Great commit as always

**Comment by CypherMorgan** [comment]
Lil suggestion: Addition of ability to Stance vehicle(The interaction menu option) as it works only on Personal Vehicles.

**Comment by ghost** [comment]
With these fixes I can now teleport onto my kosatka but I think the teleportation is a bit broken for other locations

also when using this test version the player list and lester searches are also broken, the player list won't load and the lester properties get stuck.

Here is the video of my problems:

https://youtu.be/7wxrtR6Ykb0

**Comment by Killer4563782** [comment]
@maybegreat48 I have a question, why did you create a vtable_hook class for the sync_reader stuff? Can't you just use the vmt_hook class that already exists in the project ?

**Comment by SkiddyToast** [comment]
> @maybegreat48 I have a question, why did you create a vtable_hook class for the sync_reader stuff? Can't you just use the vmt_hook class that already exists in the project ?

VMT hooks replace the pointer to the virtual method table in a singular object, while a vtable hook modifies the actual VMT for all objects that use it.

**Comment by maybegreat48** [comment]
> when using this test version the player list and lester searches are also broken, the player list won't load and the lester properties get stuck.
> 
> Here is the video of my problems:
> 
> https://youtu.be/7wxrtR6Ykb0

Is this a thing after a settings reset?

**Comment by grvelmaster** [comment]
> 

I did a clean install because it was a file prepared for testing. settings were at default (except gui)

**Comment by ghost** [comment]
> > when using this test version the player list and lester searches are also broken, the player list won't load and the lester properties get stuck.
> > Here is the video of my problems:
> > https://youtu.be/7wxrtR6Ykb0
> 
> Is this a thing after a settings reset?

I did a clean install because it was a file prepared for testing. settings were at default (except gui)


Sorry for the misinformation, the error in loading the player list and the jamming of the lester calls was due to the dns settings I was using. My modem settings, which I accidentally reset, made the dns server default, and while testing the menu again, there was no problem with the player list and lester calls.

**Comment by Yimura** [comment]
Ok then this should be ready to merge.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
