### PR TITLE
fix(vehicle-god): fix armored vehicles losing armor when vehicle god get disabled. 

### LINKED ISSUE #1192: [Bug]: Armored vehicles lose armor with menu injected
### Describe the bug

When using yimmenu the ocelot virtue doesnt mimic the bricade 6x6 stats of the ammount of missles it can take before it is destroyed. Ive tried this with a new clone of yimmenu on a seperate computer and the same issue persists 

### Steps To Reproduce

To reproduce simply hook yimmenu into gta and go into online. When online call the machanic for your personal vehicle or spawn one using the menu provided. When using armor plating it should be able to take a explosion without being destroyed. Simply throw a sticky on your ocelot virtue and get into, when in you can detonate your stickies and you should die instantly. 

When done spawn thrle same ocelot virtue and unload yimmenu by pushing 'unload' on the yimmenus status gui. Throw a couple stickies on it and get inside and you are now able to detonate the stickies and survive to tell the tale.

### Expected Behavior

Car doesnt go boom

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [ ] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by xiaoxiao921**
UNTESTED

closes #1192

### CODE REVIEW

**Comment by ghost** [comment]
When I test the file here in the game, the armor does not disappear anymore. But when I drive a vehicle that I have spawned and get off, I cannot get into the vehicle again.

The game acts as if there is no vehicle and the vehicle does not explode even if godmode is turned off.

**Comment by xiaoxiao921** [comment]
@grvelmaster can you test again please? i've made some new changes

**Comment by gir489returns** [comment]
> @grvelmaster can you test again please? i've made some new changes

You might need to post a build for him.

**Comment by Yimura** [comment]
> You might need to post a build for him.

The binary.zip updates with every new successful CI run.

**Comment by ghost** [comment]
Ok, I tested it, now there is no problem with getting into the vehicle. I also tested the armor on the f-106 and it survived 3 homing blasts.

**Comment by EbneSinam** [comment]
I tested it for a personal vehicle and it works fine. I used the Virtue vehicle and tested both the Homing Launcher and the Railgun, the armor worked fine. But when I used the Spawn Vehicles menu in the New or Persistent section and Spawn Clone for Personal Vehicle to spawn the car, the car armor did not work.

**Comment by ghost** [comment]
> I tested it for a personal vehicle and it works fine. I used the Virtue vehicle and tested both the Homing Launcher and the Railgun, the armor worked fine. But when I used the Spawn Vehicles menu in the New or Persistent section and Spawn Clone for Personal Vehicle to spawn the car, the car armor did not work.

yes I tried it on my personal vehicle clone too, armor didn't work.

**Comment by Yimura** [comment]
This should be ready to merge as it has fixed the original issue, the issue with clones/persist vehicles not having the proper blast protections is an issue with the persist feature not with the god mode feature.

**Comment by ghost** [comment]
When will this merge? I can't wait to get this fix. Even if the full test is not over, it is better that the armor of the vehicles is not damaged in the current situation.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
