### PR TITLE
feat(protection): sound overload crash protection

### PR DESCRIPTION
**Pull request by Aure7138**

### CODE REVIEW

**Review by MarkEcza — COMMENTED** [review]
functionality wise it works perfectly fine.

**Comment by Aure7138** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/10049491/cout.log)
I think I forgot this, this is the crash log

**Comment by xiaoxiao921** [comment]
This is not getting merged in it's current state, don't remove the constructor of byte patch and simply add an overload which take an an array of byte instead

**Comment by Aure7138** [comment]
You are right, it was too late that day and I just thought of this method with no experience, will change it back immediately

**Pull request closed without merging**
