### PR TITLE
Update bounty_player.cpp

### PR DESCRIPTION
**Pull request by tyackman**
Forgot to remove original set bounty function.
Sorry for double pull request my brain too lorge..

### CODE REVIEW

**Comment by TheGreenBandit** [comment]
why not remove the whole file if you're deleting the whole of the code?

**Comment by tyackman** [comment]
Not too familiar with github, and accidentally named the pr something different. I could've removed it, but left to avoid having to run cmake again for it.

**Comment by TheGreenBandit** [comment]
> Not too familiar with github, and accidentally named the pr something different. I could've removed it, but left to avoid having to run cmake again for it.

removing it in a new pr would not do it for your original pr, close this pr and implement this in your other pr if its needed

**Comment by Yimura** [comment]
Please commit these changes onto your other PR, this PR is unnecessary.
On top of that I will merge #823 first, you'll have to merge master onto your changes and make sure it works as intended for #829.

**Pull request closed without merging**
