### PR TITLE
Give optimisation hints to compiler

### PR DESCRIPTION
**Pull request by Yimura**
I split up my work into multiple commits as I did NO TESTING whatsoever to see if they make a difference, they can be reverted at any point in time.

This should definitely not be forced on every branch that exists in YimMenu, hot code paths should be prioritized (game thread mainly and expensive operations).

### CODE REVIEW

**Comment by xiaoxiao921** [comment]
Bad feeling about this, could this be atleast profiled with atleast a stopwatch or something? feel like this could backfire

**Comment by Yimura** [comment]
> Bad feeling about this, could this be atleast profiled with atleast a stopwatch or something? feel like this could backfire

It can definitely backfire and that's why it shouldn't be overused or forced into YimMenu. However it is a very powerful tool and can be used to improve certain things that are really inefficient.

**Comment by xiaoxiao921** [comment]
I know it's very powerful, but I don't think doing this kind of stuff without profiling it is reasonable.

**Comment by Yimura** [comment]
Indeed, I discussed with @gir489returns yesterday and I was talking on how powerful it can be but it can also be overused and counter-productive.
image

> This should definitely not be forced on every branch that exists in YimMenu, hot code paths should be prioritized (game thread mainly and expensive operations).

I quit early as I was just being trigger happy on adding the likely/unlikely keywords and I've committed everything as single commits so they can be reverted easily (because I know this is quite controversial but we shouldn't stay away from it).

**Comment by gir489returns** [comment]
> Bad feeling about this, could this be atleast profiled with atleast a stopwatch or something? feel like this could backfire

Just like with inline, ultimately the decision is still up to the compiler, but if you look here: https://en.cppreference.com/w/cpp/language/attributes/likely you can see at the bottom they produced a test case scenario that was extremely close to std::cos. std::cos is probably extremely optimized, but because of the likely/unlikely statements, you can tell the compiler how to generate the branch prediction code in such a way that the happy path scenario is usually the predicted path.

**Comment by gir489returns** [comment]
So I have come up with the following guidelines to use the likely/unlikely scenarios.

1. They should only be applied to scenarios where the function runs an indeterminate number of times (hooks/frame/render time dependent, all ad-hock function calls be left to the compiler for determination)
2. Any if statements that rely on user-configuration never be given a likely/unlikely scenario as we can never be predeterministic as to what the client wants.
2b. The only exception to 2 is debug scenarios, debug configurations should never be run by the client and we should never expect them to, they are there only for developers who know what they're doing.
3. Do not optimize anything that requires specific control flow. (TBD)

**Comment by gir489returns** [comment]
This should conclude the majority of my optimization emplacements.

**Comment by Yimura** [comment]
We need to do some profiling because my system is showing negligible performance changes however that doesn't mean there is a difference for system that are less performant.

**Comment by gir489returns** [comment]
```
namespace big
{
	using namespace std::chrono;
	class benchmark
	{
	public:
		explicit benchmark(std::string name = "") : 
			m_start(high_resolution_clock::now()), m_name(name) {}

		void get_runtime()
		{
			auto now = high_resolution_clock::now();
			auto milliseconds_elapsed = duration_cast<milliseconds>(now - m_start);
			auto microseconds_elapsed = duration_cast<microseconds>(now - m_start);
			LOG(INFO) << m_name << " finished with a resulting time of: " << milliseconds_elapsed.count() << "ms " << microseconds_elapsed.count() % 1000 << "us";
		}

		void reset()
		{
			m_start = high_resolution_clock::now();
		}
	private:
		high_resolution_clock::time_point m_start;
		std::string m_name;
	};
}

```

We need some kind of benchmark class to determine if the optimizations from the compiler have an effect.

**Comment by gir489returns** [comment]
I just benchmarked this with queue_dependency.

With the optimizations:

`[16:21:34.5675681][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x318D08
[16:21:34.5675723][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 4us 600ns
[16:21:34.5720734][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x961FBC
[16:21:34.5720829][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 11us 100ns
[16:21:34.5720995][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0xA66114
[16:21:34.5721008][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 400ns
[16:21:34.5726901][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F09C
[16:21:34.5726958][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 6us 700ns
[16:21:34.5727074][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F0C4
[16:21:34.5727093][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 2us 0ns
[16:21:34.5727208][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F0EC
[16:21:34.5727218][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 100ns
[16:21:34.5727234][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F074
[16:21:34.5727245][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 100ns
[16:21:34.5753427][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x335660
[16:21:34.5753459][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 3us 500ns
[16:21:34.5753517][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x335638
[16:21:34.5753563][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 4us 700ns
[16:21:34.5753847][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x4015B8
[16:21:34.5753857][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 100ns
[16:21:34.5788160][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x45B164
[16:21:34.5788226][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 7us 600ns
[16:21:34.5788842][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x45A3A8
[16:21:34.5788856][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 500ns
[16:21:34.5788875][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x5CAA60
[16:21:34.5788882][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 900ns`

Without:

`[16:28:21.6586132][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x961FBC
[16:28:21.6586299][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 18us 700ns
[16:28:21.6586454][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0xA66114
[16:28:21.6586472][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 900ns
[16:29:14.6359202][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x45A3A8
[16:29:14.6359234][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 3us 400ns
[16:29:14.6359251][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x5CAA60
[16:29:14.6359259][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 800ns
[16:29:14.6371187][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x318D08
[16:29:14.6371224][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 4us 200ns
[16:29:14.6386673][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F09C
[16:29:14.6386738][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 7us 700ns
[16:29:14.6386797][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F0C4
[16:29:14.6386813][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 800ns
[16:29:14.6386924][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F0EC
[16:29:14.6386940][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 800ns
[16:29:14.6386971][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x66F074
[16:29:14.6386986][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 600ns
[16:29:14.6410049][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x335660
[16:29:14.6410080][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 3us 300ns
[16:29:14.6410139][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x335638
[16:29:14.6410156][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 800ns
[16:29:14.6410397][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x4015B8
[16:29:14.6410415][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 1us 900ns
[16:29:14.6441614][INFO/queue_dependency.cpp:65] Blocking AC Verifier 0x45B164
[16:29:14.6441681][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 7us 700ns`

Random calls with:

`[16:21:34.5791955][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5791966][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5791976][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 0ns
[16:21:34.5791986][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792010][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792028][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792038][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792047][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 0ns
[16:21:34.5792059][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792071][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792085][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 400ns
[16:21:34.5792097][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792107][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792134][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792153][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792167][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792181][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792191][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 0ns
[16:21:34.5792217][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792236][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792248][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792264][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792275][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792303][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:21:34.5792322][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns`

Random calls without:

`[16:29:14.6443151][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 600ns
[16:29:14.6443213][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 200ns
[16:29:14.6443393][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 200ns
[16:29:14.6443768][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 400ns
[16:29:14.6443840][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:29:14.6443864][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:29:14.6443882][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:29:14.6443895][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 0ns
[16:29:14.6443910][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:29:14.6443943][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:29:14.6443967][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 100ns
[16:29:14.6443979][INFO/benchmark.hpp:18] queue_dependency finished with a resulting time of: 0us 0ns`

I think it's safe to say that the branch prediction influence has an immense difference and should be considered ready for merging.

**Review by gir489returns — APPROVED** [review]

**Pull request merged**
