### PR TITLE
Added atRTTI to CEventNetwork

### PR DESCRIPTION
**Pull request by Vali0004**
How everyone missed this, I will never know.

### CODE REVIEW

**Comment by Vali0004** [comment]
This will address issue #1398

**Comment by Tayipc38** [comment]
I have taken the liberty to test this and sadly all logs still result in event 0.
image
image

Idk if im doing something wrong here.

**Comment by Vali0004** [comment]
> I have taken the liberty to test this and sadly all logs still result in event 0. image image
> 
> Idk if im doing something wrong here.

I don’t doubt that you are doing it right, just a bit weird that it works fine in my menu.

**Comment by Vali0004** [comment]
I’m unfortunately not home. I’ll have to do some more testing when home, but that won’t be for a few hours. Please dm me on discord so I can provide the working code in order to come up with a solution

**Comment by Tayipc38** [comment]
> > I have taken the liberty to test this and sadly all logs still result in event 0. image image
> > Idk if im doing something wrong here.
> 
> I don’t doubt that you are doing it right, just a bit weird that it works fine in my menu.

Index unk_0010 within the class is reporting suspiciously close data that is within the event limits. 153 through 244.

**Comment by Vali0004** [comment]
Removing the deconstructor fixed the issue. Dayib tested and privately told me it works.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
