### PR TITLE
Update for 1.66

### LINKED ISSUE #927: Game has been updated!
I have enabled interaction limits on the repo for now.

### PR DESCRIPTION
**Pull request by Yimura**
Closes #927

### CODE REVIEW

**Comment by Yimura** [comment]
YimMenu can load in offline from this point, don't even try loading online you'll crash 100%.

**Comment by Rimmuru** [comment]
updated your todo hashes

Spectate = -2029707091
MCTeleport = 891653640
TSECommand = -1428749433
TSECommandRotateCam = 448051697
NotificationMoneyBanked = 276906331
NotificationMoneyRemoved = 853249803
NotificationMoneyStolen = 82080686

**Comment by Primexz** [comment]
> updated your todo hashes
> 
> Spectate = -2029707091 MCTeleport = 891653640 TSECommand = -1428749433 TSECommandRotateCam = 448051697 NotificationMoneyBanked = 276906331 NotificationMoneyRemoved = 853249803 NotificationMoneyStolen = 82080686

seems to be fine, checked.

**Comment by TheGreenBandit** [comment]
Some natives were also changed ex graphics

**Comment by yasmasdas** [comment]
Some globals and structs also changed

**Comment by SkiddyToast** [comment]
> Some globals and structs also changed

Which globals have changed?

**Comment by yasmasdas** [comment]
I'm not fully aware but I know some in freemode.c did.

**Comment by Primexz** [comment]
> > Some globals and structs also changed
> 
> Which globals have changed?

image
image
image

There are some more.

**Comment by TheGreenBandit** [comment]
How do u know what each does though?

**Comment by Primexz** [comment]
> How do u know what each does though?

I can't know that, as of now I'm just comparing my last commit with the one from the last update. :=)

**Comment by SkiddyToast** [comment]
> There are some more.

Do you happen to know where the new ones were added in the middle?

**Comment by Primexz** [comment]
> > There are some more.
> 
> Do you happen to know where the new ones were added in the middle?

Nope, as described above I am currently still comparing the diffs. Let's see what I still get out

**Comment by Primexz** [comment]
[freemode.patch](https://github.com/YimMenu/YimMenu/files/10571829/freemode.patch)
The full patch from the freemode script.
You can open the file in VS Code to see exactly what Rockstar has changed.
Important: Only Global updates are included in the patch.

**Comment by SkiddyToast** [comment]
I've narrowed it down between these two globals:
```
Global_2672505 is the same
Global_2680247 vs Global_2680249
```

**Comment by TheGreenBandit** [comment]
Why did they skip game version 16.65 and go immediately to 16.66? One of the devs forget what version it was on?

**Comment by SkiddyToast** [comment]
> Why did they skip game version 16.65 and go immediately to 16.66? One of the devs forget what version it was on?

They didn't. 1.65 was a gen 9 only update. You can find it [Here.](https://support.rockstargames.com/articles/12212730545299/GTAV-Title-Update-1-65-Notes-PS5-Xbox-Series-X-S)

**Comment by TheGreenBandit** [comment]
> They didn't. 1.65 was a gen 9 only update.

Ah, that sucks. They shouldve at least pushed content for us pc players

**Comment by Primexz** [comment]
I have now tested the branch for some time.
Except for some features everything seems to run stable

**Comment by TheGreenBandit** [comment]
Ip, name, rod spoofing have apparently been patched rip

**Comment by Yimura** [comment]
List of things that are broken:
- Off Radar Global
- Player Database (because RID's aren't in the rage::rlGamerInfo class anymore)
- Spoofing of values in the send_net_info_to_lobby hook

There are probably many more things broken but at the least menu is usable now.

**Comment by Primexz** [comment]
> List of things that are broken:
> 
> * Off Radar Global
> * Player Database (because RID's aren't in the rage::rlGamerInfo class anymore)
> * Spoofing of values in the send_net_info_to_lobby hook
> 
> There are probably many more things broken but at the least menu is usable now.

updated off radar, hope its ok that this is not an pr :)
```
*script_global(2672505).at(57).as<int*>() = NETWORK::GET_NETWORK_TIME() + 1;
```

**Comment by Yimura** [comment]
> updated off radar, hope its ok that this is not an pr :)
> 
> ```
> *script_global(2672505).at(57).as<int*>() = NETWORK::GET_NETWORK_TIME() + 1;
> ```

Yeah that's fine, if it's something small I prefer it be contributed like this.

Edit:
I removed all `send_net_info_to_lobby` hook related stuff for now, we can always revert it later if we find a way to fix that (although I doubt it'll be easy).

**Comment by Yimura** [comment]
Merging this PR as-is, we can fix other features later on.

**Pull request merged**
