### PR TITLE
Add world model spawning

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Testing the feature:
Add in `BigBaseV2\saved_json_vehicles`
Change extension to json
[maze_bank_test.txt](https://github.com/YimMenu/YimMenu/files/9600761/maze_bank_test.txt)

### CODE REVIEW

**Comment by SkiddyToast** [comment]
IDK if it's needed, but you should also make sure that the original model bypass is being used when spawning the model, just in case.

**Comment by xiaoxiao921** [comment]
I thought about it but it seems we only use the bypass for spawning peds (ped.hpp), and considering model attachment on the json car spawner never used the bypass too I don't think its needed ? I could be wrong

**Comment by SkiddyToast** [comment]
I guess that is the case, I'll go ahead and do a review.

**Review by SkiddyToast — APPROVED** [review]
LGTM

**Pull request merged**
