### PR TITLE
Fix Thread State for Script Functions and cellphone_flashhand

### PR DESCRIPTION
**Pull request by ShinyWasabi**

### CODE REVIEW

**Review by tupoy-ya — APPROVED** [review]
I don't think `idle` and `running` were incorrect before  https://github.com/Yimura/GTAV-Classes/pull/186

**Comment by xiaoxiao921** [comment]
Running is definitly 0 in the enum.
The two changes for the script_vm stuff make sense, you want the thread to be running for running the function inside the script vm, at first glance the cellphone change is wrong, but if it has been tested then lgtm

**Comment by ShinyWasabi** [comment]
> at first glance the cellphone change is wrong, but if it has been tested then lgtm

We were previously setting it to 1, which was `running` in the old enum. And the code used to work just fine. We now set it to `idle`, which is 1 in the new enum.

**Review by xiaoxiao921 — APPROVED** [review]

**Review by gir489returns — APPROVED** [review]

**Comment by gir489returns** [comment]
And this is why I wanted MBG to look it over, but you know, raw testing works too.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
