### PR TITLE
Add proper OOB calculation for CSectorDataNode.

### LINKED ISSUE #2096: [Bug]: invalid sector position (sector node) crash false positive
### Describe the bug

Invalid sector position (sector node) crash false positive spam during auto shop contract "superdollar." 

Occurs as non-host player upon returning to the city after attacking the MOC until mission ends. Spams log and notifications constantly. 

### Steps To Reproduce

1. Join auto shop contract "superdollar" through game phone via quickjoin, or reproduce with another player.
2. Proceed with mission until directed to deliver the bank plates to the drop-off. 
3. Once reaching the city the log and notifications are spammed with "invalid sector position (sector node) crash" false positive.

### Expected Behavior

Lack of false positives.

### Logs and/or screenshots

[redacted_cout.txt](https://github.com/YimMenu/YimMenu/files/12544677/redacted_cout.txt)

### Store

Steam

### Additional context

Haven't been quickjoining much lately but could possibly happen in other missions, contracts, and heists. Only noticed in "superdollar" so far. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by gir489returns**
Closes #2096.

### CODE REVIEW

**Review by Yimura — APPROVED** [review]
Code looks good, waiting for confirmation of the fix from @freemantsinq.

**Comment by gir489returns** [comment]
OP ragequit from the ticket, so we don't have a test case for this. This PR is now in limbo. @Yimura what do you want to do with it?

**Comment by Yimura** [comment]
If it achieves the same or better than the previous implementation of the protection then I'm fine with merging it.

**Comment by gir489returns** [comment]
> If it achieves the same or better than the previous implementation of the protection then I'm fine with merging it.

@maybegreat48 will have to determine that. Although I think this won't stop us from getting crashed because of the CPlayerSectorPosNode offset.

**Comment by gir489returns** [comment]
I have added some code to try and extract the CPlayerSectorPosNode offsets from within the CSectorDataNode. It has to completely reiterate the tree looking for it, but it should work.

**Review by Yimura — APPROVED** [review]
No complaints.

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
Leaving this open for a while so there's time to test this in practice.

**Comment by gir489returns** [comment]
@maybegreat48 had his friend using Stand test steamroller crash on me, however, it seems Stand no longer abuses `CSectorDataNode` anymore to accomplish the crash they use `CPlayerGameStateDataNode`. The only way to know for sure that this works is to find someone that can launch the crash against us. Or, remove this protection entirely as it's obsolete?

**Comment by gir489returns** [comment]
@Yimura I think we should merge this as-is, as all it's doing now is just enforcing the same positional checks as the other nodes are. If problems arise from trying to retrieve the CPlayerSectorPosNode, they will present in the crash log, and we can address it, hopefully with the reporter giving us reproduction steps.

**Comment by xiaoxiao921** [comment]
I wouldn't call this protection obsolete in any case, some other menus could abuse it still

**Comment by gir489returns** [comment]
> I wouldn't call this protection obsolete in any case, some other menus could abuse it still

Word. In that case, then it's ready for merging.

**Comment by 0xEmiil** [comment]
> @maybegreat48 had his friend using Stand test steamroller crash on me, however, it seems Stand no longer abuses `CSectorDataNode` anymore to accomplish the crash they use `CPlayerGameStateDataNode`. The only way to know for sure that this works is to find someone that can launch the crash against us. Or, remove this protection entirely as it's obsolete?

I tested [f9fbf8a](https://github.com/YimMenu/YimMenu/pull/2103/commits/f9fbf8ae1f35b2c16991186d2fbca23f024216d4) with stand ultimate and t21 and no crashes, maybe im wrong and stand ultimate dosent have steamroller crash

**Review by Yimura — APPROVED** [review]

**Pull request merged**
