### PR TITLE
skiddytoast's fragment physics crash protection

### LINKED ISSUE #795: [Bug]: BREAK_OBJECT_FRAGMENT_CHILD Crash
### Describe the bug

- Got Crashed with an Object which breaks your game when u apply this native (BREAK_OBJECT_FRAGMENT_CHILD) | old 2t1 crash?

### Steps To Reproduce

- x

### Expected Behavior

- x

### Screenshots and/or Logs

```
Dumping registers:

RAX: 0x68C37F4F40
RCX: 0x68C37F4FC0
RDX: 0x68C37F4F60
RBX: 0x68C37F57A0
RSI: 0x0
RDI: 0x20D1DA66C50
RSP: 0x68C37F4EB0
RBP: 0x68C37F4FB0
R8:  0x68C37F4F20
R9:  0x68C37F4F70
R10: 0x20D1DA55450
R11: 0x68C37F4EA8
R12: 0xFFFFFDF2E2598650
R13: 0x4
R14: 0x1
R15: 0x3

stack dump [0]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x1472C64 0x7FF7BB012C64
stack dump [1]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x146EA8C 0x7FF7BB00EA8C
stack dump [2]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x147BC8B 0x7FF7BB01BC8B
stack dump [3]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x146B5CC 0x7FF7BB00B5CC
stack dump [4]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x146B251 0x7FF7BB00B251
stack dump [5]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x147B71A 0x7FF7BB01B71A
stack dump [6]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x12E5132 0x7FF7BAE85132
stack dump [7]     C:\Program Files\Epic Games\GTAV\GTA5.exe+0x12E7022 0x7FF7BAE87022
stack dump [8]     C:\WINDOWS\System32\KERNEL32.DLL+0x126BD BaseThreadInitThunk
stack dump [9]     C:\WINDOWS\SYSTEM32\ntdll.dll+0x5DFB8 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```

### Store

Epic Games

### Additional context

- Maybe this is the Pointer for it idk lol (E8 ? ? ? ? F6 46 ? 20)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by TheGreenBandit**
fixes #795

### CODE REVIEW

**Review by SkiddyToast — APPROVED** [review]
LGTM

**Comment by TheGreenBandit** [comment]
Should i make another pr adding superjump? All we have to do is spoof the datanode for it to be undetected right?

**Comment by SkiddyToast** [comment]
Yeah, don't add it to this one, you should make another PR.

**Comment by JDMJay** [comment]
@SkiddyToast @TheGreenBandit Fragment v1 is protected against via this code but the fragment  v2 is not protected against just letting you know

**Comment by SkiddyToast** [comment]
It works against 2take1’s “Fragment” crash, I don’t know what “Fragment V2” is/which menu it’s in.

**Comment by JDMJay** [comment]
fragment v2 is from cherax

**Comment by TheGreenBandit** [comment]
> Yeah, don't add it to this one, you should make another PR.

Yeah was gonna do that, just wanted to make sure it was undetected by running it by you

**Comment by Aure7138** [comment]
> fragment v2 is from cherax

If you mean Crash V2 (the original name in cherax), I think it's another crash

**Review by Yimura — APPROVED** [review]

**Pull request merged**
