### PR TITLE
Update menu for 1.61

### PR DESCRIPTION
**Pull request by Yimura**
# Changes
- Script Hashes
- Updated tlsContext and scrThread classes
- Removed NetArrayHandler hook (crash has been patched <3 Rockstar)

## Pointers
 - Get Network Event Data
 - Received clone sync & Get sync tree for type & Get net object for player & Get sync type info & Get net object
 - Friend Registry

## Classes
- Friends struct updated

## Globals
 - clear_wanted_player
 - Disable Phone
 - No Idle Kick
 - Despawn Bypass
 - get current_personal_vehicle
 - get_personal_vehicle_handle
 - go_into_personal_vehicle
 - Hud Transition State
 - join_type (session)
 - Off Radar
 - Player
 - Mechanic
 - Shop Controller Dismiss Pop-up
 - spawn_global
 - Vehicle

## Locals
- Freemode Mechanic Timer
- LS Customs

# TODO
```
Nothing at the moment
```

# Thanks
 - @maybegreat48 for their TSE hashes and globals
 - @SkiddyToast for some of the patterns in pointers.cpp
 - @MetaClient for their globals and TSE hashes
 - @Adler-D3R for their TSE hashes

### CODE REVIEW

**Comment by maybegreat48** [comment]
New crash TSE: `1348481963`

**Review by maybegreat48 — COMMENTED** [review]
can remove Spaghettios as its probably the same crash as the new hash

**Comment by aa15032261** [comment]
Should we remove the duplicated global in uilt/globals.hpp?

```
inline Vehicle get_personal_vehicle()
{
        return *mobile::mechanic_global.at(298).as<Vehicle*>();
}
```

**Comment by Yimura** [comment]
> Should we remove the duplicated global in uilt/globals.hpp?
> 
> ```
> inline Vehicle get_personal_vehicle()
> {
>         return *mobile::mechanic_global.at(298).as<Vehicle*>();
> }
> ```

If it's a duplicate, then yes, I didn't check if it was a duplicate.

**Comment by Yimura** [comment]
Oh I misunderstood, I moved the entire function to mobile::mechanic instead of keeping it in globals.

**Comment by Yimura** [comment]
I think everything has been updated 🤔 

Binary from the CI/CD: https://github.com/YimMenu/YimMenu/suites/7542356294/artifacts/311088405

**Review by LiamD-Flop — APPROVED** [review]

**Pull request merged**
