### PR TITLE
Hotkey Additions

### PR DESCRIPTION
**Pull request by TheGreenBandit**
the commits left behind the most recent are from the last pr, if more options are converted to commands or anyone has any that they would like as hotkeys that are already commands please provide

### CODE REVIEW

**Comment by tupoy-ya** [comment]
From [TupoyeMenu](https://github.com/tupoy-ya/TupoyeMenu/blob/master/src/services/hotkey/hotkey_service.cpp)
```cpp
register_hotkey("heal", g.settings.hotkeys.heal, RAGE_JOAAT("heal"));
register_hotkey("fillsnacks", g.settings.hotkeys.fill_inventory, RAGE_JOAAT("fillsnacks"));
register_hotkey("skipcutscene", g.settings.hotkeys.skip_cutscene, RAGE_JOAAT("skipcutscene"));
```

**Comment by TheGreenBandit** [comment]
> From [TupoyeMenu](https://github.com/tupoy-ya/TupoyeMenu/blob/master/src/services/hotkey/hotkey_service.cpp)
> 
> ```c++
> register_hotkey("heal", g.settings.hotkeys.heal, RAGE_JOAAT("heal"));
> register_hotkey("fillsnacks", g.settings.hotkeys.fill_inventory, RAGE_JOAAT("fillsnacks"));
> register_hotkey("skipcutscene", g.settings.hotkeys.skip_cutscene, RAGE_JOAAT("skipcutscene"));
> ```

i love the menu bar at the top of ur menu lmao, u should make a pr for it to be added to yim

**Comment by tupoy-ya** [comment]
> i love the menu bar at the top of ur menu, u should make a pr for it to be added to yim

Menu bar was taken from pre #62 version of YimMenu and will only look normal if it's reverted which won't happen.

**Comment by TheGreenBandit** [comment]
I don't know why it a merge branch with nothing in it, but your hotkeys are added now tupoy-ya

**Comment by TheGreenBandit** [comment]
these are the last hotkeys i could think of implementing that are commands, godmode isn't a command and neither is vehicle fly but if someone were to convert those then i would add them

**Comment by Yimura** [comment]
> Shouldn't every option be able to get a hotkey assigned to them? or should that be done when commands are fully implemented

Yeah the current hotkey system requires manually adding each and every settings, in the future we'd probably use some source engine like system where you can bind any key to any command through some dynamic UI.

**Review by Yimura — APPROVED** [review]
Code looks good haven't tested if it all works in-game yet.

**Comment by TheGreenBandit** [comment]
> Code looks good haven't tested if it all works in-game yet.

Want to implement superjump when that pr is pushed as a hotkey in here, then if no one else requests a hotkey that is a command it'll be ready

**Comment by TheGreenBandit** [comment]
if no one has anything else they want as a hotkey that is already say it now otherwise this pr is good to go

**Review by Yimura — APPROVED** [review]

**Pull request merged**
