### PR TITLE
Start Script Protection Toggle, Stand User Marking, More Name Appendages, and Block Stand Elegant Crash

### PR DESCRIPTION
**Pull request by Rxann**
Helps #3002

### CODE REVIEW

**Comment by rkwapisz** [comment]
Earlier I issued a PR for a script handling rework https://github.com/YimMenu/YimMenu/pull/3045 that will impact your implementation.

**Comment by Rxann** [comment]
> Earlier I issued a PR for a script handling rework #3059 that will impact your implementation.

I am aware, I think mine may be a little bit better though, as start script may have some impacts on things, as far as I am aware that users should be able to turn off at their discretion.

**Comment by rkwapisz** [comment]
EDIT: Sorry I didn't properly link my PR: https://github.com/YimMenu/YimMenu/pull/3045

Yes, I agree with your idea of an overall toggle. It can be easily used with my refactor. If anything I think your toggle will be even easier to implement there. Take a look in my PR to see what I did.

**Comment by rkwapisz** [comment]
What is the value of marking users as Stand Users? This assumes that other menus aren't doing the same thing as Stand and, honestly, I don't care what menu people are using. If they're trying to crash me, I just want to block the crash and know they're modding. We can use the existing crash infraction for this.

**Comment by Rxann** [comment]
> What is the value of marking users as Stand Users? This assumes that other menus aren't doing the same thing as Stand and, honestly, I don't care what menu people are using. If they're trying to crash me, I just want to block the crash and know they're modding. We can use the existing crash infraction for this.

I see we might not agree in this area, but I think most YimMenu users would like this feature and it gives extra info on modders. Stand also marks YimMenu users so it may be time we do it back.

**Comment by Rxann** [comment]
> EDIT: Sorry I didn't properly link my PR: https://github.com/YimMenu/YimMenu/pull/3045
> 
> 
> 
> Yes, I agree with your idea of an overall toggle. It can be easily used with my refactor. If anything I think your toggle will be even easier to implement there. Take a look in my PR to see what I did.

I will add what is in your pr to this ASAP.

**Comment by maybegreat48** [comment]
> Stand also marks YimMenu users so it may be time we do it back.

Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless

**Comment by lonelybud** [comment]
i think there was more code pointed out in https://github.com/YimMenu/YimMenu/issues/3002 related to `TSECommandSoundSpam` & some `isnan` checks.

**Comment by Rxann** [comment]
> > Stand also marks YimMenu users so it may be time we do it back.
> 
> 
> 
> Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless

From what I have heard and seen, yes they do specifically mark YimMenu users.

**Comment by Rxann** [comment]
> i think there was more code pointed out in https://github.com/YimMenu/YimMenu/issues/3002 related to `TSECommandSoundSpam` & some `isnan` checks.

We already have isnan checks.

**Comment by rkwapisz** [comment]
> > > Stand also marks YimMenu users so it may be time we do it back.
> > 
> > 
> > Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless
> 
> From what I have heard and seen, yes they do specifically mark YimMenu users.

That's fine, though. What can they do with this information? In what way can they practically affect my experience as a YimMenu user? Likewise, what does it matter that I know they're using Stand? YimMenu won't behave any differently apart from the notification, and there isn't anything we can necessarily do to further protect ourselves against an identified Stand user. Yim's timeout feature is already plenty powerful to essentially let you ignore an player's entire existence in your session.

Also, menus come and go. GTA Online has been out for over 10 years now, and I've seen more menus and bases for this game than I can count. It simply does not matter to me whether someone's using Stand or XForce or 2Take1 or whatever. I don't remember the names of 80% of the menus that were abandoned, I just want to not get crashed.

**And perhaps more importantly - why give Stand the free advertising?**

**Comment by lonelybud** [comment]
> From what I have heard and seen, yes they do specifically mark YimMenu users.

the main thing is that we dont know whether other menus copy the same code or not. The thing is that for now not to worry about it and in future do changes like this https://github.com/lonelybud/lonelyMenu/blob/master/src/core/data/reactions.hpp where every crash is labelled for better debugging and logged to console and there you can label the crash whatever you want.

**Comment by tyackman** [comment]
> > Stand also marks YimMenu users so it may be time we do it back.
> 
> 
> 
> Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless

Fairly certain it's due to how we spoof our host token, I saw a lua script that checked the host token to pick out yim menu users. Also it's impossible to get host if a stand user is forcing host as well.

**Comment by Rxann** [comment]
> > > > Stand also marks YimMenu users so it may be time we do it back.
> 
> > > 
> 
> > > 
> 
> > > Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless
> 
> > 
> 
> > From what I have heard and seen, yes they do specifically mark YimMenu users.
> 
> 
> 
> That's fine, though. What can they do with this information? In what way can they practically affect my experience as a YimMenu user? Likewise, what does it matter that I know they're using Stand? YimMenu won't behave any differently apart from the notification, and there isn't anything we can necessarily do to further protect ourselves against an identified Stand user. Yim's timeout feature is already plenty powerful to essentially let you ignore an player's entire existence in your session.
> 
> 
> 
> Also, menus come and go. GTA Online has been out for over 10 years now, and I've seen more menus and bases for this game than I can count. It simply does not matter to me whether someone's using Stand or XForce or 2Take1 or whatever. I don't remember the names of 80% of the menus that were abandoned, I just want to not get crashed.
> 
> 
> 
> **And perhaps more importantly - why give Stand the free advertising?**

Stand is the best selling mod menu in GTA of all time. Us mentioning
it will not do anything, and if the user plays the game for more than five minutes, someone will most definitely mention it. They can kick you, or crash you if they want to target YimMenu users.

**Comment by xiaoxiao921** [comment]
> > > Stand also marks YimMenu users so it may be time we do it back.
> > 
> > 
> > Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless
> 
> Fairly certain it's due to how we spoof our host token, I saw a lua script that checked the host token to pick out yim menu users. Also it's impossible to get host if a stand user is forcing host as well.

Do you have a link to such lua script doing this?

**Comment by Rxann** [comment]
> > > > Stand also marks YimMenu users so it may be time we do it back.
> 
> > > 
> 
> > > 
> 
> > > Specifically as a YimMenu user? Well doesn't matter, I still don't think we should mark people as stand users, it's essentially pointless
> 
> > 
> 
> > Fairly certain it's due to how we spoof our host token, I saw a lua script that checked the host token to pick out yim menu users. Also it's impossible to get host if a stand user is forcing host as well.
> 
> 
> 
> Do you have a link to such lua script doing this?

I think one of them is called JinxMenu. I remember hearing that that is possibly one of the ones that marks YimMenu users.

**Comment by xiaoxiao921** [comment]
https://github.com/Prisuhm/JinxScript/blob/main/JinxScript.pluto#L2761

The token is randomly generated unless i'm mistaken since a long time now, anything else?

**Comment by 0xEmiil** [comment]
Tbh i think its a good idea to detect Stand, it will help us to prevent things from certain players also the Stand Id that they use its from the game? or how the Stand detect another Stand user?

**Comment by Rxann** [comment]
> https://github.com/Prisuhm/JinxScript/blob/main/JinxScript.pluto#L2761
> 
> 
> 
> The token is randomly generated unless i'm mistaken since a long time now, anything else?

It is randomly generated, but I am not an expert.

Also, for the people against stand user detection, what are the downsides for why you don't want it to be merged?

**Comment by rkwapisz** [comment]
> Tbh i think its a good idea to detect Stand, it will help us to prevent things from certain players also the Stand Id that they use its from the game? or how the Stand detect another Stand user?

Like what? I asked above what we can do with the information, but we have no additional capability in YimMenu to deal specifically with Stand users. Elegant Crash is not something necessarily limited to Stand, and I bet lots of pasted menus have this same thing. There are so many menus out there that I just don't care who is using what.

> > https://github.com/Prisuhm/JinxScript/blob/main/JinxScript.pluto#L2761
> > The token is randomly generated unless i'm mistaken since a long time now, anything else?
> 
> It is randomly generated, but I am not an expert.

Checking for spoofed host tokens is trivial. Just do the math. YimMenu currently randomizes a host token between 0 and 10,000. A uint64 max value is 184,467,440,737,095,551,615.

So what are the chances of rolling a value below 10,000? It's 5.421×10^−20.
For all intents and purposes, it's impossible. You have better odds of picking a particular atom from anywhere in the universe. No one ever playing this game for millions of years will naturally generate a token below 10,000.

If you want less detectable spoofing then generate from a much, much, much, MUCH larger/higher range.

> 
> Also, for the people against stand user detection, what are the downsides for why you don't want it to be merged?

Maintainability vs. usefulness. I still haven't seen a good explanation of why this provides value because we can't do anything with the information. We already identify what crash was attempted on us, so it would be more useful to have a notification like "Blocked Elegant Crash from user XXXX". Heck, you can even mention Stand in the notification if you really want to since it's just a piece of text we can modify in the translations table.

I just don't want people 3 months down the line opening PRs for "We detect Stand so why don't we detect Cherax and 2Take1 too?"

**Comment by Sainan** [comment]
JinxScript is UGC; we would never add a YimMenu detection to Stand itself. Menu classification was actually one of my early goals with the classification system, but rkwapisz brings up some great points about why it's not a particularly good idea when looking into the long-term prospects, so it never transpired.

And I think the fact I'm here commenting tells you something about the long-term prospects of the code being proposed here. (Did anyone even expect otherwise with this being an open-source project?)

**Comment by Yimura** [comment]
~~From what I’m seeing this isn’t really detecting Stand rather just a Lua script made for Stand.~~

And as a second point I wouldn’t want to specifically detect mod menu’s as they may turn around and start targeting us as a retaliation. Combined with the added effort of keeping up a list of mod menu’s in YimMenu as well as different methods on detecting them. On top of that with the nature of YimMenu being opensource allows developers of other menu’s to instantly see what is making them detected and just patch it out.

Generalised identification is fine as it doesn’t specifically target a menu and allows us to act in a different manner.

**Comment by Yimura** [comment]
@Rxann this PR is a good example of why we split up our work into different branches/PRs. There are multiple problems in here that need to be addressed.

Part of this PR is being addressed by someone else already #3045, if you had split this PR up into:
1. Start script protection improvements -> drop it as it's being handle already and don't just steal someone else's work
2. Stand user marking -> denied as we don't want to become a target nor start an incentive
3. More name "appendages" -> fine apart from the specific Stand detection (missing translation though)
4. Block Stand Elegant crash -> fine if it could be tested in a vacuum through an isolated PR

Then we would've been able to properly address each point, now we need to go through each and every pain-point, wait for you to fix them one by one. This will increase the time before it can be merged, increase the review time and require more thinking.

This would've been fine if it had been discussed before that you'd be doing all these things in one PR however we did not receive such a warning/heads up and because of this we've got this extra overhead dealing with it.

**Comment by Rxann** [comment]
> @Rxann this PR is a good example of why we split up our work into different branches/PRs. There are multiple problems in here that need to be addressed.
> 
> 
> 
> Part of this PR is being addressed by someone else already #3045, if you had split this PR up into:
> 
> 1. Start script protection improvements -> drop it as it's being handle already and don't just steal someone else's work
> 
> 2. Stand user marking -> denied as we don't want to become a target nor start an incentive
> 
> 3. More name "appendages" -> fine apart from the specific Stand detection (missing translation though)
> 
> 4. Block Stand Elegant crash -> fine if it could be tested in a vacuum through an isolated PR
> 
> 
> 
> Then we would've been able to properly address each point, now we need to go through each and every pain-point, wait for you to fix them one by one. This will increase the time before it can be merged, increase the review time and require more thinking.
> 
> 
> 
> This would've been fine if it had been discussed before that you'd be doing all these things in one PR however we did not receive such a warning/heads up and because of this we've got this extra overhead dealing with it.

Ah okay, in the future I will separate my pr's. I did not want to spam 4 pull requests so I thought I should make a bigger one, but I see that it is tedious and when it is a topic of discussion like this one, it can be hectic. I will omit the features that have not been approved. For now, is it fine to leave these 2 features in this pr? For the future if I am opening a big or controversial pr, I will ask in the element channel first.

**Comment by rkwapisz** [comment]
> > @Rxann this PR is a good example of why we split up our work into different branches/PRs. There are multiple problems in here that need to be addressed.
> > Part of this PR is being addressed by someone else already #3045, if you had split this PR up into:
> > 
> > 1. Start script protection improvements -> drop it as it's being handle already and don't just steal someone else's work
> > 2. Stand user marking -> denied as we don't want to become a target nor start an incentive
> > 3. More name "appendages" -> fine apart from the specific Stand detection (missing translation though)
> > 4. Block Stand Elegant crash -> fine if it could be tested in a vacuum through an isolated PR
> > 
> > Then we would've been able to properly address each point, now we need to go through each and every pain-point, wait for you to fix them one by one. This will increase the time before it can be merged, increase the review time and require more thinking.
> > This would've been fine if it had been discussed before that you'd be doing all these things in one PR however we did not receive such a warning/heads up and because of this we've got this extra overhead dealing with it.
> 
> Ah okay, in the future I will separate my pr's. I did not want to spam 4 pull requests so I thought I should make a bigger one, but I see that it is tedious and when it is a topic of discussion like this one, it can be hectic. I will omit the features that have not been approved. For now, is it fine to leave these 2 features in this pr? For the future if I am opening a big or controversial pr, I will ask in the element channel first.

I'd recommend closing this PR and just opening up new PRs for each feature separately.

**Comment by maybegreat48** [comment]
> JinxScript is UGC

Yeah, exactly. Just create a lua script or something if you want to detect Stand and other P2Cs

> denied as we don't want to become a target nor start an incentive

We wouldn't become a target, but it's still very useless

**Comment by Yimura** [comment]
Please split the work in this PR up into 2 different ones (aka. the topics I didn't drop).

Currently this PR is in a dirty state from the merged changes in #3045.

**Pull request closed without merging**
