### PR TITLE
Session tab

### LINKED ISSUE #74: Move session join options
**Describe the bug**
Currently session join options have been moved under the "Self" tab but these don't belong here.

**Expected behavior**
It might be better to create a new view category for "lobby" options, where you could then use these same lobby join options.

### PR DESCRIPTION
**Pull request by xM4ddy**
#74

### CODE REVIEW

**Comment by Yimura** [comment]
Bruh stop, leave dependency management to me. There's no need to update vendor currently.

**Comment by Yimura** [comment]
Also a PR is for a single thing to be fixed, added or modified.

As the title of the PR states it's meant to fix issue #74 , but now you're also updating vendors, just stop.

**Comment by xM4ddy** [comment]
Whoops didn't think this would go to here though it would keep the one I created the PR with. I probably need to make a new branch. Again new to github and making mistakes.

**Comment by Yimura** [comment]
You can forcce push your branch to https://github.com/Yimura/YimMenu/pull/76/commits/f568d000b88345de718a35c4fbe323d2900036fa to fix the issue.

**Comment by xM4ddy** [comment]
Sorry took me a sec.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
