### PR TITLE
feat(Network): Log Chat Message

### PR DESCRIPTION
**Pull request by Aure7138**

### CODE REVIEW

**Comment by Demae** [comment]
This can all be parsed through the net message hook so most of this commit is unneeded for this kind of feature, as well as net message allowing parsing of text messages.

**Comment by Aure7138** [comment]
ok, already change to receive_net_message, i have absolutely no idea how to use receive_net_message, all credit goes to @Yimura and @Demae

**Comment by tupoy-ya** [comment]
If you can get `is_team` from net message you can do GTA5 style chat log:
```cpp
LOG(INFO) << player->get_player_info()->m_net_player_data.m_name << (is_team ? " [LOCAL] " : " [ALL] ") << msg;
```

**Comment by Aure7138** [comment]
ok, a sec, yimura show that too

**Pull request closed without merging**
