### PR TITLE
Update to 1.64

### LINKED ISSUE #692: [Bug]: New Update in GTA
### Describe the bug

Welcome back to Los Scumtus with new innovative changes we dont even care about trailer so fuck you and new cars that nobody will use in 1 week. Even on our logo for this update we shit on you except for a combat lesbian, some more npcs you dont care and get 1 call per minute. AND for the best Ron is back because a update without reused locations, npcs wouldnt be our standard. So turn back today. jk

fuck you rockstar for removing the rtti

+ Menu not working because some sigs changed etc. every time the same game

### Steps To Reproduce

Inject YimMenu
Get Crashed
Be Happy

### Expected Behavior

No Crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #695: [Bug]: New version you uploaded still crsahing, is it expected?
### Describe the bug

when trying to inject the version u uploaded 14min ago still crashing idk if is not to be used yet 

### Steps To Reproduce

1. Inject
2. crash
3. :]

### Expected Behavior

Is expected to work or is that in-proggres  version ?

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by maybegreat48**
Some crash protections have been disabled as they do not work with the 1.64, we'll fix this in a later PR.

Closes #692
Closes #695

### CODE REVIEW

**Comment by Clone69420** [comment]
The commented out SE are not updated yet?

**Comment by Yimura** [comment]
> The commented out SE are not updated yet?

It's a draft PR with a reason, this doesn't include a whole lot of things that are required.
- Crossmap
- Signatures
- Updated classes
- ...

**Comment by Loko415** [comment]
Format Metric For Sending updated. Needs new sig would try get it but no ida...

**Comment by GeopJr** [comment]
(reminder to update metadata.json before merging)

**Comment by Yimura** [comment]
Please, if you cannot contribute do not comment on this PR.

**Comment by Fuscina** [comment]
> Format Metric For Sending updated. Needs new sig would try get it but no ida...

They removed that function from the game, they have added new metrics for detecting cheaters.

**Comment by Loko415** [comment]
https://github.com/Primexz/GTAV-Decompiled-Scripts

**Comment by yzzuf** [comment]
Does anyone have the new updated classes?

**Comment by Loko415** [comment]
it loads but it still crashes when you load into storymode*

**Comment by Yimura** [comment]
> it loads but it still crashes when you load into storymode*

Magic word \*DRAFT* PR, this means it isn't ready.

Mainly the classes still need to be updated.

**Comment by Loko415** [comment]
classes causing crashes? oh alright.

**Comment by Yimura** [comment]
TODO:
 - [x] Transition State global
 - [ ] Alternative for CanApplyData (mapping out the synctree or hooking each reader)
 - [x] Join Session type global
 - [x] Snow on ground global
 - [ ] enter_player_interior globals

**Comment by Loko415** [comment]
love you bro that fixed it ahahaahah

**Comment by Yimura** [comment]
> love you bro that fixed it ahahaahah

No it didn't, you'll crash the second you go into online.

**Comment by Loko415** [comment]
true lol

**Comment by Loko415** [comment]
atleast i can use it in singleplayer

**Comment by Yimura** [comment]
PR should be ready to merge into master, we can fix the CanApplyData hook at a later point (aka mapping out the synctrees or switching to hooking the data node readers).

Waiting for https://github.com/Yimura/GTAV-Classes/pull/88 to be merged.

**Review by Yimura — DISMISSED** [review]
Changes were all updates for 1.64, looks good to me.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
