### PR TITLE
feat(Vehicle): Added vehicle window controls on "Fun Features" tab

### PR DESCRIPTION
**Pull request by Democles85**

### CODE REVIEW

**Comment by Tayipc38** [comment]
Could this maybe go in the vehicle controller?

**Comment by Democles85** [comment]
> Could this maybe go in the vehicle controller?

You mean to add a full new tab?

## EDIT 
Oh nvm, I know what you mean. Just thought here would be okay since Seats controls.

## EDIT 2
Getting brain farts from trying to do it in here....

**Comment by Tayipc38** [comment]
If you have difficulty understanding the service, Ill gladly offer some assistance. The seat controls are indeed in the main UI, and there is a duplicate in the vehicle controller. But arbitrary vehicle controls like opening doors or rolling down windows tend to hog space, hence why I had added a separate window.

**Comment by Democles85** [comment]
> If you have difficulty understanding the service, Ill gladly offer some assistance. The seat controls are indeed in the main UI, and there is a duplicate in the vehicle controller. But arbitrary vehicle controls like opening doors or rolling down windows tend to hog space, hence why I had added a separate window.

I will try again today, yesterday was tired and really was out of it, got it working to some extent, but the button was not changing states, so have to check it out or start from beginning. Ty for the assistance, I will gladly take it as I have recently gotten into game modding (recently being 3 - 4 days XD). Here is my discord (best_peerat).

**Pull request closed without merging**
