### PR TITLE
feat(lua): Allow lua scripts to flag modders with a custom reason if needed.

### LINKED ISSUE #2209: [Improvement]: network.flag_player_as_modder should have reason arg
### Which feature

There is this in lua api thingy and you can only flag a player but you can't add a reason to it which is not good:
### `flag_player_as_modder(player_idx)`

Flags the given player as a modder in our local database.

- **Parameters:**
  - `player_idx` (integer): Index of the player.

**Example Usage:**
```lua
network.flag_player_as_modder(player_idx)
```

### Reason

Solution: Add the following thing

### `flag_player_as_modder(player_idx, reason)`

Flags the given player as a modder in our local database.

- **Parameters:**
  - `player_idx` (integer): Index of the player.
  - `reason` (string): Uhhhhhhhhhhh.

**Example Usage:**
```lua
network.flag_player_as_modder(player_idx, "Too fat to handle")
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Closes #2209

### CODE REVIEW

**Comment by xiaoxiao921** [comment]
@pierrelasse Can you test that one please?

**Comment by pierrelasse** [comment]
Okay so,
i used the following code, and it produced this error:
```lua
if ImGui.SmallButton("Modder detection test") then
    network.flag_player_as_modder(player.player, "CUSTOM_REASON", "Being a test object")
end
```
Error:
```
[-][FATAL/lua_manager.cpp:163] x.lua: x.lua:x: sol: no matching function call takes this number of arguments and the specified types
stack traceback:
        [C]: in field 'flag_player_as_modder'
        x:x: in function <x.lua:x>
```

Please tell me if this is not the correct usage. But i looked at the docs commit and this seemed the most correct way of marking a player with a custom reason.

**Comment by xiaoxiao921** [comment]
Can you try

```lua
if ImGui.SmallButton("Modder detection test") then
    network.flag_player_as_modder(player.player, infraction.CUSTOM_REASON, "Being a test object")
end
```

**Comment by pierrelasse** [comment]
> Can you try
> 
> ```lua
> if ImGui.SmallButton("Modder detection test") then
>     network.flag_player_as_modder(player.player, infraction.CUSTOM_REASON, "Being a test object")
> end
> ```
Yes, this works perfectly.
image

**Comment by xiaoxiao921** [comment]
Yeah in fact I just did that, I guess this PR is ready to be merged then

**Comment by pierrelasse** [comment]
Would it make sense to be able to flag a player without them being put as a modder?

**Comment by xiaoxiao921** [comment]
It's doable but i'm not sure what's the point? maybe you meant adding additional notes?

**Comment by pierrelasse** [comment]
> It's doable but i'm not sure what's the point? maybe you meant adding additional notes?

Yeah, or if a detection is not 100%.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
