### PR TITLE
Add Repair PV hotkey

### PR DESCRIPTION
**Pull request by Rxann**
This is my best try at trying to add a hotkey to the menu.

### CODE REVIEW

**Comment by Seanghost117** [comment]
Make sure you are testing and compiling your additions. This won't work because it is missing somethings ^^^

**Comment by Rxann** [comment]
Alr I will test it right now

**Comment by Rxann** [comment]
Okay I am trying to get this to work

**Comment by Rxann** [comment]
So I believe that this is not working because of the third argument in the register_hotkey. Do you believe that I have the correct value for that argument?

**Comment by Rxann** [comment]
Could anyone give me assistance on what I should put for the third argument in the register_hotkey because I do believe this is what is preventing my hotkey from working?
`register_hotkey("repairpv",g.settings.hotkeys.repairpv,RAGE_JOAAT("repairpv"));`

**Comment by Primexz** [comment]
What a weird PR.

1. can't you compile the menu yourself?
2. your hotkey has no logic to execute..


For basic usage checkout #925

**Comment by Rxann** [comment]
I can compile the menu myself. I am just learning how to work with Yim and create things. The thing I don't understand is how I can get my hotkey to repair the current vehicle the player is in.

**Comment by Rxann** [comment]
> What a weird PR.
> 
> 1. can't you compile the menu yourself?
> 2. your hotkey has no logic to execute..
> 
> 
> For basic usage checkout #925

   Where do I put the logic to execute?

**Comment by Primexz** [comment]
> > What a weird PR.
> > 
> > 1. can't you compile the menu yourself?
> > 2. your hotkey has no logic to execute..
> > 
> > 
> > For basic usage checkout #925
> 
>    Where do I put the logic to execute?

Take a look at the PR I linked to.
You need to create a new command.

**Comment by Rxann** [comment]
Okay I will examine it

**Comment by Rxann** [comment]
It successfully works now, I have tested it. The feature has been fully implemented.

**Comment by Primexz** [comment]
> It successfully works now, I have tested it. The feature has been fully implemented.

Looks good, congratulations.
Please run clang-format over your code and then it should be ready for merging.

**Comment by Rxann** [comment]
Okay thanks!

**Comment by Rxann** [comment]
The formatting has been completed!

**Review by Yimura — APPROVED** [review]
Good job on making your first working feature, experiment with adding some different features to get more used to it all.

YimMenu has a lot to offer so it's fairly hard to get used to it all and take full advantage.

**Comment by Rxann** [comment]
Hi, Thank you it was very fun and I am going to try to contribute some other features too!

**Pull request merged**
